### ISSUE TITLE
Is a Chocolatey package interesting?

### ISSUE THREAD

**Issue by ErichDonGubler** [watchexec/watchexec#110]
I'd be more than happy to create an automatically updating Chocolatey package to hand off to whoever wants it -- is that interesting at all? I use Chocolatey to automate my own workflow right now, and this is a slick tool I'd love to add to my automatic toolbelt. :)

**Comment by passcod** [comment]
Absolutely!

**Comment by mitranim** [comment]
It appears that someone else ended up putting this up ([repo link](https://github.com/jonasw234/au-packages/tree/master/watchexec)), but that package is outdated. I'm raising an issue with the maintainer, but intrigued by the "automatically updating" idea. Any chance of getting that to work? The current package has everything hardcoded.

**Comment by passcod** [comment]
I believe it _is_ auto-updated, that's what the update.ps1 file is ([ref](https://docs.chocolatey.org/en-us/create/automatic-packages)), but that script in turn is outdated, due to, a while ago, the gnu build being dropped in favour of the msvc build, and more recently, the tagging scheme changing.
