### ISSUE TITLE
Not working with -f option

### ISSUE THREAD

**Issue by lfilho** [watchexec/watchexec#112]
Hey, just found your project, thanks for it!

I'm just tried a basic usage before using it in a script but it is failing. 
**Host:**
- MacOS High Sierra
- ZSH
- watchexec installed via brew today: `watchexec-1.9.2.high_sierra.bottle.tar.gz`

Repro steps of what I did:
1. `brew install watchexec`
2. `open myFile.csv`
3. `watchexec -f "myFile.csv" ls` (Here `ls` is executed as expected for the first time)
4. Edit `myFile.csv` on Excel and hit save.
5. `ls` is not run, which was not expected.

I also tried with the `-p` option to postpone it. Then on step 3 it doesn't execute `ls` as expected, and on step 5 it is also not executed, whic is also not expected.

I also tried the commands without quotes, i.e.: `watchexec -f myFile.csv ls`. Same thing.

No error is thrown.

**Comment by lfilho** [comment]
If it helps:

![image](https://user-images.githubusercontent.com/282756/53280057-15972a00-36cb-11e9-87cd-b4eaa8662399.png)

**Comment by lfilho** [comment]
Oh, on the commands above, I also tried without quotes, i.e.: `watchexec -f console.plan_.csv ls`. Same thing...

**Comment by lfilho** [comment]
Another experiment: tought Excel could maybe be saving the file in a way that somehow watchexec wasn't getting triggered, so I tested with a simple `test.txt` file... Then edited it with vim and saved it... Same problem...

**Comment by lfilho** [comment]
Also tried with `--`: `watchexec -f test.txt -- ls`. With and without quotes around file name. Same problem.

**Comment by passcod** [comment]
Please run with `--verbose` to get a diagnostic log

**Comment by lfilho** [comment]
After running with `--verbose`, noticed the following:

```
*** Ignoring "/Volumes/Unix/myFolder/test.txt": did not match any given filters
```

The filtering feature uses `globset`(https://crates.io/crates/globset) for it, right? In their page they have examples like this one (`foo.rs`) so I assume that my `test.txt` file should indeed be a valid pattern.

I was able to get it working by passing the full file path:

```shell
watchexec --verbose -f /Volumes/Unix/myFolder/test.txt ls # works
```

But then it isn't a "pattern" anymore. By the way, passing the relative path did not work:

```shell
watchexec --verbose -f ./test.txt ls # doesn't work
```

Looks like a bug when building the pattern for `globset` or a bug in `globset` itself?

**Comment by lfilho** [comment]
The only way I found to make it work was forcing a wildcard into the pattern like so:

```
watchexec --verbose -f */test.txt ls
```

**Comment by passcod** [comment]
Right, so this is actually about how the filtering engine works, specifically around pattern anchoring, see the discussion here: https://github.com/passcod/cargo-watch/issues/82

The filtering probably ought to work or parse differently in order to have better UX, but how that should be hasn't been figured out yet. Closing in favour of the above bug due to it having the info (yes, it's on another repo, but the solution will be implemented here anyway).
