### ISSUE TITLE
Kill long running process

### ISSUE THREAD

**Issue by cw789** [watchexec/watchexec#114]
Is there a way how I can kill long running processes (server) on the exit of watchexec.

**Comment by passcod** [comment]
Sure, that's what should be happening. What's happening for you, what platform, can you show a reproduction?

**Comment by cw789** [comment]
Platform: Linux

Ok. I've found out the behavior I had is special to the linux Erlang processes.
`watchexec --exts ex --restart "mix run --no-halt"` will not kill the Erlang process on exit of watchexec as it is also listening on ^C.
Erlang goes into a kind of "Exit Menu" on ^C in which I thing the exit signal forwarded from watchexec won't be processed anymore.

By using watchexec with starting erlang in background - everything is working as expected.
`watchexec --exts ex --restart "mix run --no-halt &"`

**Comment by cw789** [comment]
PS: Thanks for this very very very cool tool!
