### ISSUE TITLE
Any desire to dual license?

### ISSUE THREAD

**Issue by CameronNemo** [watchexec/watchexec#119]
Would be nice if watchexec was available under an additional license, for example MIT or 0BSD. Many Apache-2.0 projects do this to remain compatible with GPL-2.0 code and similar patent clause incompatibilites.

**Comment by passcod** [comment]
Not my call. @mattgreen?

We'd also need to petition all/most contributors to gain assent, I think.

**Comment by mattgreen** [comment]
What does a dual license do for watchexec? I'm unable to come up with a case in my mind. That doesn't mean there isn't one, but more that I can't envision a scenario in which it helps. Can you elaborate, @CameronNemo?

**Comment by CameronNemo** [comment]
I don't have a concrete integration in mind with GPL2 or CDDL code, but such a scenario is possible. Looking at the moderately sizeable list of contributors, it may be more effort than it is worth.

**Comment by passcod** [comment]
The license does mean that watchexec is incompatible to be combined with GPL-2.0 code in some situations, and that may discourage some users in the first place. However, I believe it's not an issue with LGPL or GPL-3.0. Additionally, I believe this is only a concern for linking, i.e. using watchexec as a library, either through the C or the Rust interface, and that the executable tool form offers sufficient isolation for the licensing incompatibility to not be an issue.

I would put my vote to close this as wontfix if there isn't a concrete and compelling case.

**Comment by mattgreen** [comment]
Agree with @passcod here: this is a good thought but I'd like to see a concrete use case before making this change.
