### ISSUE TITLE
Cargo command not found

### ISSUE THREAD

**Issue by raindev** [watchexec/watchexec#121]
watchexec cannot find `cargo` command even though it's present in `PATH` and I can run it manually. Cargo is installed using rustup, the binary is in `~/.cargo/bin` which is added to `PATH` in `~/.profile`. I'm on Ubuntu 19.04.

I tried to do some debugging on my own by modifying watchexec and found that it does see the correct `PATH`. Setting the environment variable on the [created command](https://github.com/watchexec/watchexec/blob/8e8410e35d132b0a18ea8615a61c40d258bcbd83/src/process.rs#L94) (even though it's supposed to inherit environment accordingly to the docs) doesn't make a difference.

I'm not sure the problem is with with watchexec as running cargo the same way with `sh -c 'cargo watch'` also fails with "sh: 1: cargo: not found".

Using `--no-shell` only changes the error message to "Error: I/O error: No such file or directory (os error 2)".

```
$ watchexec cargo check
sh: 1: cargo: not found
^C

$ cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s

$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/.cargo/bin:~/bin:~/.local/bin

$ ls ~/.cargo/bin/cargo
/home/raindev/.cargo/bin/cargo*

$ head ~/.profile
# Make Cargo binaries available
[ -d ~/.cargo/bin ] && export PATH="$PATH:~/.cargo/bin"

**Comment by passcod** [comment]
If you run `watchexec env` does that help debugging?

**Comment by passcod** [comment]
> I'm not sure the problem is with with watchexec as running cargo the same way with sh -c 'cargo watch' also fails with "sh: 1: cargo: not found".

Ah, I hadn't seen this. The problem is definitely with your rust/rustup install somehow, rather than watchexec. I would look as to why whatever your `sh` loads includes something that resets the `PATH` (as the `PATH` should definitely carry over to child shells, including those run by watchexec).

**Comment by raindev** [comment]
It turned out the problem was caused by use of `~` in my `$PATH`. Thanks @passcod and @Mange for your suggestions.
