### ISSUE TITLE
Random crash on MacOS: "Unable to decode StreamFlags: 4260096"

### ISSUE THREAD

**Issue by judofyr** [watchexec/watchexec#122]
I got this error right now, but I haven't been able to reproduce it…

```
thread '<unnamed>' panicked at 'Unable to decode StreamFlags: 4260096', src/libcore/option.rs:819:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by passcod** [comment]
What version of macos, of cargo watch?

**Comment by passcod** [comment]
This issue was fixed by an fsevent update (see https://github.com/passcod/notify/issues/128 and [notify 4.0.11 changelog](https://github.com/passcod/notify/blob/main/CHANGELOG.md#4011-2019-05-08)), which will be in watchexec 1.10.2 soon.
