### ISSUE TITLE
Execute Script in New CMD prompt

### ISSUE THREAD

**Issue by Smith-Chris1** [watchexec/watchexec#126]
I'm running this on windows via a powershell script. It works well, but if my script takes too long to finish, watchexec can't see new changes to the folder its watching. Is there a way to launch a new cmd or powershell prompt to execute the script in? That way I can leave watchexec running and executing new scripts if the filesystem changes.

Hope that makes sense.

**Comment by passcod** [comment]
I think this would be covered by #67?

**Comment by passcod** [comment]
Someone is (was?) working on this: https://github.com/passcod/cargo-watch/issues/123
