### ISSUE TITLE
Handler trait definition makes it difficult to define third-party handlers

### ISSUE THREAD

**Issue by waynr** [watchexec/watchexec#133]
First off, thanks for the excellent tool! For a long time I just ran `watch ...` to automate iterative development tasks but eventually wrote a small `inotify-wait` script to reduce CPU and disk (cache) usage; but the shell script approach suffers from a number of reliability drawbacks. Last week I began using `watchexec` after discovering it while considering building pretty much the same thing myself.

Anyway, I also came across `cargo-watch` which I am familiarizing myself with in order to implement some features on it and it uses `watchexec` as a library. Which also really cool, it's great to see that my new favorite command line tool is also a library :). The reason I am writing this issue is to bring up some difficulties I have noticed with the `Handler` trait that motivates a change I am about to propose with a PR.

The main difficulty in my view is that the current definition of `Handler` makes it impossible for third-party users to initialize their handler before handing it off to `watchexec::watch`; in fact, we don't hand it off at all since `watch` expects to create new instances itself with a call `Handler::new` using the type parameter. This becomes problematic when third party users want to pass non-`watchexec::Args` parameters to their handler. The way this is done in `cargo-watch` currently is kind of an ugly hack (and is what motivated me to refactor the `Handler` trait):

* Here `cargo-watch` defines a `quiet` flag: https://github.com/passcod/cargo-watch/blob/de7da410e5bf4360d514cb2f708603628c84b4b0/src/args.rs#L76-L81
* Here `cargo-watch` appends the `quiet` flag to the end of the list of commands it passes to `watchexec`:
  * https://github.com/passcod/cargo-watch/blob/de7da410e5bf4360d514cb2f708603628c84b4b0/src/lib.rs#L59-L61
  * https://github.com/passcod/cargo-watch/blob/de7da410e5bf4360d514cb2f708603628c84b4b0/src/lib.rs#L177
* Here `cargo-watch` pops that `quiet` arg off the end of the `watchexec::Args.commands` list to finally set it on the `CwHandler`:
  * https://github.com/passcod/cargo-watch/blob/de7da410e5bf4360d514cb2f708603628c84b4b0/src/watch.rs#L16-L19

I could see someone argue that maybe the maintainer of `cargo-watch` should propose a `quiet` argument to `watchexec::Args`, but it seems to me like that would get unwieldy in the long term assuming more projects start to use `watchexec` as a library and have their own bespoke parameters that they want to pass to their handlers.

The best way I can think of to improve this situation is to leave `Handler` initialization to the caller of `watchexec::watch`. I believe this would greatly ease consumption of `watchexec` as a library, and will reduce the need for hackish workarounds like the one I described above. In fact, this is what I've done in my working branch, which I'll submit as a PR shortly (along with a corresponding `cargo-watch` PR that demonstrates how it improves the situation for a third party library).

**Comment by passcod** [comment]
> could see someone argue that maybe the maintainer of cargo-watch should propose a quiet argument to watchexec::Args

I mean, the truth is (lol I'd forgotten about this hack) that I'm the maintainer of both, so that's how I kinda get away with it (previously, for other features).

Anyway, I'll look at this in more detail, but from descriptions it sounds excellent, thank you!

**Comment by waynr** [comment]
Cool, thanks for the quick acknowledgement! I'm looking forward to your feedback!
