### ISSUE TITLE
add argument for a simple and clear print out of why an action is triggered

### ISSUE THREAD

**Issue by thomasf** [watchexec/watchexec#138]
`-v` just spews out hundreds or thousands of lines so much information that I even can't begin to try to parse it.  It's thousands of thousands of lines and almost all of them says *Ignored* or  which is the opposite of what I am looking for while trying to figure out why the execution just keeps starting over again and again....

When I try something like this or something similar I don't even get a print out of echo for some reason (and trying out other ways to escape the command so that $WATCHECEX_ should be correclty specified)

`watchexec  -e .py  -- sh -c 'echo "path $WATCHEXEC_COMMON_PATH"; tox -p 12'` 

So then I have to move to writing a shell script for it to actually print something useful and some times that just contains the root of the project so I can't use that either.

ff.sh
```sh
#!/bin/sh
echo why: $WATCHEXEC_COMMON_PATH
exec tox -p 12
```

```
watchexec -e .py ./ff.sh
```

I think I need a simple watchexec argument like `--why`  that just prints the reason why an execution  is retriggered because in some scenarios trying to figure out what to ignore or include as watch patterns is just too annoying.

**Comment by passcod** [comment]
Done in 1.15.0
