### ISSUE TITLE
&& doesn't seem to work

### ISSUE THREAD

**Issue by nikitavoloboev** [watchexec/watchexec#143]
I have `main.rs` file and I want to compile and run it on file changes. So I run:

`watchexec --exts rs rustc main.rs && ./main`

But that doesn't seem to work. This `watchexec --exts rs rustc main.rs` does. So I am not sure, perhaps `&&` is not supported?

Also I am curious @passcod as this tool is written in Rust itself, what is your workflow in developing rust programs. Do you use a similar command as above?

**Comment by Mange** [comment]
It's because your shell is seeing the && and waiting for watchexec to finish.

You could quote your command so all of it is sent to watchexec.

```
watchexec --exts rs "rustc main.rs && ./main"
```

**Comment by passcod** [comment]
And there's cargo-watch for the rust workflow.
