### ISSUE TITLE
An option to print a colored message when the command completes

### ISSUE THREAD

**Issue by ethercrow** [watchexec/watchexec#144]
Here's what I do currently:

```
$ watchexec -- 'make build && echo "\n\033[0;32mOK\033[0m\n" || echo "\n\033[0;31mFAIL\033[0m\n"'
```

What I would like to do instead:

```
$ watchexec --colored -- make build
```

Please see a similar issue in another tool for some more motivation and screenshots: https://github.com/commercialhaskell/stack/issues/1109

**Comment by Mange** [comment]
Suggestion: Instead of bloating watchexec, you could have your own wrapper that you can use.

Place this in `~/.local/bin/show-exit`:

```sh
#!/bin/sh

if ("$@"); then
  echo "$(tput setaf 3)Exited successfully$(tput sgr0)"
else
  status=$?
  echo "$(tput setaf 1)Failed with exit code ${status}$(tput sgr0)"
  exit $status
do
```

Then you can use it in front of any other command.

```
watchexec -- show-exit make build
```

I didn't test this script as I'm on my phone right now, but I think it would work.

**Comment by passcod** [comment]
Partial implementation in 1.18.0:

- no colours
- a message is only printed on non-success return

More improvements are likely!
