### ISSUE TITLE
./gitignore files in subdirectories not used

### ISSUE THREAD

**Issue by Chris-Nicholls** [watchexec/watchexec#146]
Git allows you to place .gitignore files in subdirectories, and these are picked up. 
watchexec seems to only search for .gitignore files in the paths explicitly listed and their parents, not subdirectories. 

In my situation I had a .gitignore in a subdirectory that was used to ignore log files. These weren't getting picked up by watch-exec so it kept retriggering whenever the log files were written to. Easy enough to fix not I know the issue, but took a while to discover. 

It seems there was a PR for this from a while ago, but it was closed: 
https://github.com/watchexec/watchexec/pull/17
Any chance we could re-open it?

**Comment by passcod** [comment]
The PR was superseded by other work, so I'm not going to re-open that, but I'll keep this issue open.

**Comment by Chris-Nicholls** [comment]
I created https://github.com/watchexec/watchexec/pull/147 to fix this. 
I didn't touch the behaviour of .ignore files, but I can add that to the PR if you like.

**Comment by passcod** [comment]
That (also doing it for ignore files) would be good, yes please :)




---- On Fri, 06 Mar 2020 23:49:49 +1300 notifications@github.com wrote ----



I created #147 to fix this.
I didn't touch the behaviour of .ignore files, but I can add that to the PR if you like.

**Comment by Chris-Nicholls** [comment]
Ok, I've added similar behaviour for .ignore files too. 
It's not identical, since .gitignore files have a well defined root to search up from, whereas .ignore files don't. So for .ignroe files, it searched subfolders of the watched paths, as well as any found while walking up to `/`

**Comment by passcod** [comment]
That's probably good enough for now, and I'll make a note to review this for 2.0. Thanks!
