### ISSUE TITLE
Display more information about file permission errors

### ISSUE THREAD

**Issue by abitrolly** [watchexec/watchexec#149]
```
Error: I/O error: Permission denied (os error 13)
```

Is it possible to get more descriptive error message in case of this error? In my case the error is likely caused by user unreadable files beneath watched directory. 

```
$ ls -la .local/share/containers/storage/overlay-containers/b34f6ac065645a6d25c794564fdd9ca50c8835acd350c5a8230e16602cc098af
total 12
drwx------. 3 anatoli anatoli 4096 Mar 17 20:57 .
drwx------. 3 anatoli anatoli 4096 Mar 20 08:07 ..
drwx------. 3  100000  100000 4096 Mar 19 15:45 userdata
```

Reporting these files or printing a command to find them could help.

**Comment by passcod** [comment]
need-info label is about answering "Is it possible"

**Comment by Boscop** [comment]
I get the same error.
> Error: I/O error: Permission denied (os error 13)

Yes, please make it show the exact reason that causes this error.

Also, can watchexec please auto-ignore folders/files that the current user doesn't have permission for?

**Comment by abitrolly** [comment]
@Boscop try running with `strace, e.g. `strace watchexec -e .sh ./run.sh`

**Comment by passcod** [comment]
Partially related to upstream due to notify driving some of this

**Comment by passcod** [comment]
See linked notify issues/PR for detail, but this will be addressed in the #205 work.

**Comment by abitrolly** [comment]
@passcod does it really needs to be blocked by async?

**Comment by passcod** [comment]
Bit of a misnomer; this will be unlocked by Notify 5.0.0-pre.13, and the async work is where Notify 5 is used.

**Comment by passcod** [comment]
That's done now. It will print errors like:

```
[[while adding "/home/code/html/watchexec/forbid" to the Native watcher: Permission denied (os error 13) about ["/home/code/html/watchexec/forbid"]]]
```

and that's also a non-fatal error (here, it's still watching the rest of the `watchexec` folder).

**Comment by abitrolly** [comment]
This feature is very helpful. Thanks!
