### ISSUE TITLE
Add option to send different signal to child on graceful exit (e.g. sending SIGTERM on SIGINT)

### ISSUE THREAD

**Issue by alex88** [watchexec/watchexec#151]
First of all a lot for this nice tool!
I'm using it to re-run an elixir script so when I change something it restarts the command.

When I save a file watchexec correctly uses SIGTERM to shutdown the process, when I do ctrl-c instead the child receives INT which by default makes the elixir script pause its execution and show a few commands.

For example:

```
➜ simulator git:(master) ✗ mix run --no-halt
19:25:45.904 [info]  Starting simulator^C # <-- CTRL-C here
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C # <-- CTRL-C again makes the script to exit

➜ simulator git:(master) ✗ mix run --no-halt
19:25:50.452 [info]  Starting simulator
19:25:56.459 [info]  Checking for new content...
19:25:57.345 [info]  SIGTERM received - shutting down # <-- this is with a killall
```

when I run it via watchexec isntead:

```
➜ simulator git:(master) ✗ watchexec -r -- mix run --no-halt                                   
19:26:15.108 [info]  Starting simulator
19:26:16.110 [info]  Checking for new content...
19:26:17.111 [info]  Checking for new content...^C # <-- this CTRL-C terminates watchexec and shows the debug commands in the child 
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution

➜ simulator git:(master) ✗ # <-- If I type c here the child continues in the background while I still have a shell
19:26:19.128 [info]  Checking for new content...
19:26:20.129 [info]  Checking for new content...
19:26:21.130 [info]  Checking for new content...
➜ simulator git:(master) ✗ 
19:26:22.131 [info]  Checking for new content...
19:26:23.132 [info]  Checking for new content...
```

is it an expected behavior? Maybe it would make sense to add an option to send sigterm on watchexec exit or?

**Comment by passcod** [comment]
See the `--signal` option

**Comment by passcod** [comment]
Oh wait

**Comment by alex88** [comment]
Signal does work on file change btw

**Comment by passcod** [comment]
I feel like if you're telling the process to continue and it continues it shouldn't be terribly surprising. But we can certainly see about adding a way to customise the signal on exit.

**Comment by alex88** [comment]
> I feel like if you're telling the process to continue and it continues it shouldn't be terribly surprising. But we can certainly see about adding a way to customise the signal on exit.

you mean the "If I type c here the child continues in the background" part?
That was just to show that the program is actually still alive after watchexec exits. I thought that watchexec will send the same signal it's configured to send when a file changes and the child is still running also on watchexec termination.

(thanks for fixing the title)

**Comment by passcod** [comment]
nah, it just passes the signal along in the normal unix fashion

**Comment by alex88** [comment]
Btw in the meantime I've found that option `-n, --no-shell` works because the child process not finding itself in a shell doesn't prompt anything before terminating

**Comment by MrFoxPro** [comment]
Right now process just dies and it's impossible to capture this event
Can watchexec just pass the same signal to kill process?

**Comment by passcod** [comment]
This is now possible with a combination of `--stop-signal` and `--map-signal` depending on the behaviour you want.
