### ISSUE TITLE
Removed files added to $WATCHEXEC_CREATED_PATH, not to $WATCHEXEC_REMOVED_PATH

### ISSUE THREAD

**Issue by danieljl** [watchexec/watchexec#154]
### Environment
- OS: macOS 10.15.4 (Catalina)
- watchexec version: 1.13.1

### Steps to reproduce:

1. Run
```shell
watchexec -- 'echo "created: $WATCHEXEC_CREATED_PATH\nremoved:$WATCHEXEC_REMOVED_PATH\n---"'
```

2. In another terminal, run
```shell
touch file1 file2 && sleep 2 && rm -f file1 file2
```

Output produced:
```
created:
removed:
---
created: /file1:/file2
removed:
---
created: /file1:/file2
removed:
---
```

The problem occurs intermittently. Occasionally, it returns the correct output:
```
created:
removed:
---
created: /file1:/file2
removed:
---
created:
removed:/file1:/file2
---
```

**Comment by passcod** [comment]
Yeah, unfortunately, going only by what the fs notifications tell us, we can't guarantee correctness in that regard on macOS.

The easy thing to do is to treat all these as "changed" and not anything specific.

The more correct but harder and a lot more expensive thing to do is to keep track of the entire file tree, treat the fs notification as a hint to re-read the entire tree, and then do a diff on that. That's what Apple's own documentation suggests. It's... hard to justify doing that work in watchexec as the main use a very simple "trigger a command when something changes."

**Comment by danieljl** [comment]
Just to clarify, are you saying that in case when the event type is "file removed", macOS' FSEvents is _sometimes_ not reporting the correct event type? (Hence the bug is in FSEvents.)

**Comment by passcod** [comment]
Yes. And it's not a bug, it's a feature (or the consequence of deliberate decisions, rather). FSEvents is just not designed for that kind of granularity, it's designed for the pattern I described above. It was made for Apple's backup solution, where that is completely appropriate. Using it for general-purpose and precise eventing is not actually a supported usecase; _that_ was Notify's mistake of API choice, though I didn't really know all that when macOS support got added... and now I've said goodbye to the project so. Not going back.

**Comment by passcod** [comment]
If you sleep for >60 seconds you _should_ get more consistent results. As far as I understand it, FSEvents has a "batching" behaviour at 30 seconds, so the behaviour is that you're falling between buckets:

```
"Correct":

===== bucket boundary =====
touch   --- recorded as add
                             => "something's been added!"
===== bucket boundary =====  
rm      --- recorded as rm
                             => "something's been removed!"
===== bucket boundary =====

"Incorrect":

===== bucket boundary =====
touch   --- recorded as add
                             => "something's been added!"
rm      --- not overwriting
                             => "something's been added!"
===== bucket boundary =====
```

**Comment by danieljl** [comment]
The batching behavior explains the intermittent issue. Thanks for the detailed explanation!
