### ISSUE TITLE
Call to init_logger makes it difficult to use watchexec as a library

### ISSUE THREAD

**Issue by PhilipDaniels** [watchexec/watchexec#159]
I'm trying to use watchexec as a library from my program. Seems to be the best option to get recursive watching with ignored files that I can find in the Rust ecosystem.

However, within `run.rs\watch()` you currently call `init_logger()`. This is problematic because I am already initialising `env_logger` from within my program, and the second initialisation from `watchexec` then panics (i.e. `env_logger` must only be initialised once).

A library shouldn't initialise the log system, it can simply call the `log` macros as needed. The fix is to move the call to `init_logger()` into main, somewhere very near the beginning. (I don't know what you want to do with this 'debug' flag. Personally I would just get rid of it and call the `debug` log macro whenever needed. `env_logger` is flexible enough to filter on any desired message). I guess `cargo-watch` would also need adjusting, but I haven't looked in detail, the two crates seem very linked.

**Comment by passcod** [comment]
The debug flag is to switch the default filtering level so the `--verbose` cli flag works. `debug!` _is_ used internally.

You're quite right the logger shouldn't be initialised in the library. If you want to make that change I'll gladly merge it in.
