### ISSUE TITLE
Support long paths on windows

### ISSUE THREAD

**Issue by passcod** [watchexec/watchexec#163]
Looks like Rust doesn't yet transparently support long paths on Windows. From this thread: https://twitter.com/zkat__/status/1283223785592680449

The current best way to work around this seems to be embedding a manifest into the executable, that has a property that makes this work magically somehow.

Threads to look at:

- https://github.com/rust-lang/rfcs/issues/721
- https://github.com/rust-lang/rust/issues/11207
- https://github.com/rust-lang/rfcs/pull/2188

~~Not sure this can be done for source builds (with `cargo install`)~~ it can, see below

**Comment by zkat** [comment]
Looks like this way might work: https://github.com/nabijaczleweli/cargo-update/blob/master/build.rs

**Comment by passcod** [comment]
This may or may not still require that the _user_ sets a registry key, see https://github.com/BurntSushi/ripgrep/issues/364

> [In] `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem` [set] `LongPathsEnabled` to 1

**Comment by passcod** [comment]
That's been merged.
