### ISSUE TITLE
Examples of running on single / specific files

### ISSUE THREAD

**Issue by murlakatamenka** [watchexec/watchexec#165]
Please, share share some examples of using watchexec on specific files.

The only thing I found is #112 and [this comment](https://github.com/watchexec/watchexec/issues/112#issuecomment-467193564) with hacks like supplying full path to file or using "*/<filename>" as a pattern. Both options aren't really intuitive, would be glad to know if better solutions exist.

Thanks.

**Comment by passcod** [comment]
You can use the `-w` option to only watch specific files.

    watchexec -w some.file ...

**Comment by murlakatamenka** [comment]
@passcod thank you! :+1: 

Help says this:

```sh
    -w, --watch <path>...            Watch a specific directory
```
which is why I didn't find this option myself! I thought it was meant to be used, for example, with `--exts`, i.e. to specify working dir for further globbing.

Please, adjust the help message for better understanding. How about

```sh
    -w, --watch <path>...            Watch a specific file or directory
```
Explicit is better than implicit, right? :smiley:
