### ISSUE TITLE
Implement negative ignores

### ISSUE THREAD

**Issue by exalted** [watchexec/watchexec#166]
Hi,

It appears to me that currently if I were to run `watchexec --watch ./ --watch ./foo/ command [argument…]`, where `./foo/` is a directory ignored via `git` (which can be seen in `git status --ignored=matching --short | ack -o '(?<=^!! ).*'`), if a file inside `./foo/` directory was to be changed `watchexec` will not run the command because `--no-vcs-ignore` flag was not given.

I think all paths given via `--watch` must override all global and VCS rules in order to be able to make exception to some files to be able trigger a run of command even if those files are ignored globally or via VCS.

**Comment by passcod** [comment]
The way it works is that if no `--watch` is given, `--watch .` is implied.

I also don't think it's worth it to introduce a breaking behaviour change to fulfil that particular usecase.

**Comment by exalted** [comment]
> The way it works is that if no --watch is given, --watch . is implied.

I am sorry I wasn’t clear in my original text. What you’ve just said is perfectly clear in my mind and it makes sense to have a default. That’s not the issue. 

In order to let you understand what I am suggesting here, I’d like to ask you how would you run `whatchexec` so that one file that is originally ignored by VCS to be included in the paths that are monitored, whilst not having to disable VCS ignored rules all at once?

Thanks.

**Comment by passcod** [comment]
No, no, I understand your feature request. I'll just be explicit: I need that feature request to either come without suggestion of implementation, or with a suggestion that's not _breaking the basic behaviour of the program._ The reason I explained how it works was to show why your suggestion would break behaviour.

Interestingly, I believe there's currently a bug that makes your issue a non-issue (accidentally)... but also probably breaks what you'd actually expect. That is, given a directory structure like

```
/path/
/path/.git/...
/path/.gitignore
/path/foo/bar
```

and with `bar` being gitignored,

running `watchexec date` picks up the gitignore, but running `watchexec -w foo date` doesn't, and consequently modifying `bar` runs `date`. :(

----

Probably a decent design for your feature would be to support negative patterns both in the ignore files and in the `--ignore` option, so you'd be able to say `--ignore '!bar'`.

**Comment by exalted** [comment]
Oh, fair enough. I see your point. 

Please, by all means, don’t take this issue then as a suggestion of how this should work / be implemented, and instead as a use case which I think is useful, but cannot be done currently without having to exclude all VCS ignored files. 

Makes sense?

**Comment by exalted** [comment]
P.S.: I am pretty okay with the approach you suggested.

**Comment by passcod** [comment]
Negative ignores are now supported in .ignore (and .gitignore, etc) files. They're not supported in `-f` or `-i` options _yet_, but are supported in the experimental "tagged" filterer (see the release notes for 1.18.0).

**Comment by soenkehahn** [comment]
I'm interested in this usecase. I found the release notes for `1.18.0` here: https://github.com/watchexec/watchexec/releases/tag/cli-v1.18.0. They mention the `TaggedFilterer` struct. But that doesn't seem to exist on current `main` anymore. Is there a way with the current version to achieve this?

**Comment by passcod** [comment]
The original feature request (that `--watch` overrides filters) _has_ actually been implemented since, in #859. For the more generic "negative ignores" you can use filter programs (`--filter-prog`).
