### ISSUE TITLE
Investigate decreasing the default debounce delay

### ISSUE THREAD

**Issue by Calinou** [watchexec/watchexec#168]
Right now, the default debounce delay in watchexec is 500 ms. However, in practice, I've often been able to use debounce delays as low as 50 ms (tested on a SSD). To give the best possible experience, the debouncing delay could be decreased. Of course, this needs rigorous testing with various applications.

While 50 ms might not work for all use cases, I think we could try decreasing the default debounce delay to 300 ms and see if there are any regressions. We can then decrease it further if there are no regressions reported once a new release is made.

**Comment by passcod** [comment]
Sounds good.

**Comment by passcod** [comment]
It's now 300ms in 1.14.1. Let's lower to 150 or so in ~3-6 months (if no issue crop up).

**Comment by passcod** [comment]
Down to 150ms, next decrease in ~3-6 months, perhaps to 100ms.

**Comment by passcod** [comment]
Down to 100ms, let's schedule the last drop to 50ms for the new year.
