### ISSUE TITLE
watchexec restarts even when I make a small adjustments 

### ISSUE THREAD

**Issue by matthiasdebernardini** [watchexec/watchexec#170]
I usually write my files when I use (neo)vim  by pressing `:w` and I was hoping watchexec would restart when I use that command in my editor but it restarts even I add a space. I would like to have it run fewer times.

Is this my editor that is always changing the file? Or is watchexec doing something I'm not expecting?

I'm running `watchexec -e c server`

I was thinking if it is my editor then maybe I can have watchexec look for when a file gets `git add`ed. 

Any help?

**Comment by passcod** [comment]
That's not what watchexec does. You'll need to either use another tool (perhaps a git hook), or to have watchexec call a script that figures out if something changed in git and _then_ restarts your server.

You could possibly approximate that with

   watchexec -w .git -f index -e c -- server

that will watch the git index file, which is what gets updated internally by git when you run `git add`.

**Comment by matthiasdebernardini** [comment]
Thank you very much for the help.

What do people in intellij or other editors do? this seems like it should happen quite often

**Comment by passcod** [comment]
They don't save after just changing whitespace, I suppose. Or more likely they set things up such that rebuilds aren't disruptive, either because the process is fast or because the server is only restarted after the build is done or something (there are examples of how to do that in the cargo-watch readme). IntelliJ and other IDEs and even vim nowadays also have language servers and similar facilities which are more reactive and offload some of the need for watchexec-style reloading. ---- On Thu, 15 Oct 2020 02:06:48 +1300  notifications@github.com  wrote ----
Thank you very much for the help.
What do people in intellij or other editors do? this seems like it should happen quite often

**Comment by passcod** [comment]
Also, re-reading your original question... do you mean that watchexec triggers when you add text in vim even without saving? If so that would sound like either you don't have the right ignores or your vim is pretty badly misconfigured

**Comment by matthiasdebernardini** [comment]
> do you mean that watchexec triggers when you add text in vim even without saving

Yes, I have it this way so that I can store all the history of every change. I personally find it productive to have this. 

I actually can't get 

`watchexec -w .git -f index -e c -- server`

or even,

`watchexec -w .git -- server`

to notice either `git add` or `git commit` or `git push`

Quick question its a logical AND between `-w .git -f index -e c` right?

Also thanks again for replying, even without getting this to work I'm still finding watchexec to be helpful.

**Comment by passcod** [comment]
> Yes, I have it this way so that I can store all the history of every change. I personally find it productive to have this.

Yes, I do that too, but I have it store in a global directory outside of my projects, for this and other reasons. Regardless, the files it generates should be ignored. Run in verbose mode to see what triggers it and write an ignore pattern (put it in a .ignore file if you're committing the history files) for it.

> Quick question its a logical AND between -w .git -f index -e c right?

Oh right, don't use `-e c` with it. And you probably have to pass `--no-vcs-ignores` to get it to not ignore .git actually.
