### ISSUE TITLE
Option to hard-clear instead of soft-clear

### ISSUE THREAD

**Issue by mitranim** [watchexec/watchexec#171]
Currently, `-c` soft-clears the terminal. This is equivalent to scrolling it down. Scrolling up will reveal the older content. Personally, I prefer hard-clearing, when the previous output is actually deleted from the terminal.

Not entirely sure if there's a standard escape sequence for this, and it may vary by terminal, but [this](https://github.com/mitranim/gow/blob/c27e23b21066f44929fd8f3c80513dabc55a414a/gow.go#L83-L86) is what I've been using in [gow](https://github.com/mitranim/gow), and it seems to work well in iTerm2, MacOS Terminal, and MS's new Terminal for Windows under WSL.

Would appreciate such an option for `watchexec`.

**Comment by passcod** [comment]
This was changed back in 2017 actually from hard to soft. Can certainly add an option for hard back in. For reference, `tput reset` is soft, `tput clear` is hard.

**Comment by passcod** [comment]
Relatedly, it would be nice to have a crate which does screen clearing in a cross platform manner... might be something to spin out of watchexec.

**Comment by mitranim** [comment]
`reset` and `clear` behavior seems to be OS specific. A colleague reported `clear` performing a hard clear on their Ubuntu. Meanwhile, on my MacOS 10.14, `clear` is soft. Haven't checked, but the MacOS version probably prints `\x1bc` to stdout, while the Ubuntu version probably prints `\x1bc[3J`.

**Comment by passcod** [comment]
Clearing will once again be "hard" from 1.16.0 **where possible**. There are terminals where that just isn't a thing. If interested, see the [clearscreen](https://docs.rs/clearscreen) where I've done a deep dive on the whole clearing thing.

**Comment by mitranim** [comment]
Very nice, thank you! Also good to know about the inconsistencies. I'll report the results here once 1.16 shows up in `brew`.

**Comment by mitranim** [comment]
Finally got around to testing on MacOS, and it does hard-clear on MacOS. Thanks!
