### ISSUE TITLE
Using `touch` doesn't set path in `ENV` variables

### ISSUE THREAD

**Issue by khepin** [watchexec/watchexec#173]
I'm using the following: `watchexec -v -- sh -c "printenv | grep -i watchexec"` to print all the `ENV` vars set for the command that is being called when an event happens.
If I save a file through a text editor, I'll get: `WATCHEXEC_WRITTEN_PATH=/Users/<...>/Makefile`, but if I use the `touch` command on that file, the output of `grep` is empty.
I've run the verbose output and it might be related to the detected file operation being "empty". However in my case I'd still want to know which file got an event even if the operation was empty. This is the output in verbose mode:

*Saving file via editor:*
```
*** Paths updated: [PathOp { path: "/Users/<...>/Makefile", op: Some((empty)), cookie: None }, PathOp { path: "/Users/<...>/Makefile", op: Some(WRITE), cookie: None }]
*** Waiting for process to exit...
*** Launching child process
*** Assembled command "sh" "-c" "sh -c printenv | grep -i wat"
*** Waiting for filesystem activity
WATCHEXEC_WRITTEN_PATH=/Users/<...>/Makefile
*** Received SIGCHLD
```
*using touch*
```
*** Paths updated: [PathOp { path: "/Users/<...>/Makefile", op: Some((empty)), cookie: None }]
*** Waiting for process to exit...
*** Launching child process
*** Assembled command "sh" "-c" "sh -c printenv | grep -i wat"
*** Waiting for filesystem activity
*** Received SIGCHLD
```
First line here lets me know that the change was properly detected with the right file path. Since the operation is "empty" though it seems none of the operation specific flags is being set.

My preference would be to have a `WATCHEXEC_FILE_PATH` var always be set that would be independent of any operation that happened, but that's just my preference.

Thank you for making and working on `watchexec`, it's a great tool and I really appreciate the work that has been put into it.

**Comment by khepin** [comment]
Forgot to mention, this was on MacOS.

**Comment by passcod** [comment]
Oh, that's an interesting case. Definitely something we'd want to support.

**Comment by edvald** [comment]
> My preference would be to have a WATCHEXEC_FILE_PATH var always be set that would be independent of any operation that happened, but that's just my preference.

+1 on this, as well as a corresponding `WATCHEXEC_OP` or something to that effect.

And another +1 on the good work! We're exploring it's use to improve file watching in [Garden](https://github.com/garden-io/garden).

**Comment by passcod** [comment]
This should work now! Even if macOS doesn't give us metadata eventing, it will appear in the new `WATCHEXEC_OTHERWISE_CHANGED_PATH` variable
