### ISSUE TITLE
ARMv8 build

### ISSUE THREAD

**Issue by koasmox** [watchexec/watchexec#175]
I would love to easily get to run `watchexec` on an RPi3, i.e. a build to the [`aarch64-unknown-linux-gnu`](https://doc.rust-lang.org/beta/rustc/platform-support.html) architecture would be nice.

Workaround:

```shell
apt install cargo
cargo install watchexec
```

**Comment by passcod** [comment]
That's done as of 1.15.0

**Comment by koasmox** [comment]
Thx
