### ISSUE TITLE
Obtain directory path

### ISSUE THREAD

**Issue by 251** [watchexec/watchexec#176]
Hi, I'm running watchexec on a directory with `watchexec -w /path/dir script.sh`. Another process creates subdirectories and copies files into those directories. The thing is, that I don't get the subdir path (`/path/dir/subdir`) from watchexec.        `${WATCHEXEC_CREATED_PATH}` and `${WATCHEXEC_META_CHANGED_PATH}` both contain `/file1.txt:/file2.txt:/file3.txt:...`. What am I doing wrong?

**Comment by passcod** [comment]
Do you mean that you're getting full file paths (which contain the subpath you're looking for, just not on its own), or that you're getting only the filenames or something else? Also, what platform?

**Comment by 251** [comment]
Let's say `subdir` gets created and `file1.txt` etc. are copied into it:
```
/path/dir/subdir/file1.txt
/path/dir/subdir/file2.txt
/path/dir/subdir/file3.txt
```
Then I get: `/file1.txt:/file2.txt:/file3.txt` in both environment variables but not the `subdir` path.

Linux 5.4.0-47-generic x86_64 GNU/Linux (Ubuntu 18.04.5)
watchexec 1.14.1 (watchexec-1.14.1-x86_64-unknown-linux-gnu.tar.xz)

**Comment by passcod** [comment]
Ah, yes, you should also have a `WATCHEXEC_COMMON_PATH` which will have the absolute path that's a common parent to all changed files. (Avoids env overflow when there's lots of changes.)

**Comment by 251** [comment]
Oh dear, I just realised I copied the wrong line from the README. I wasn't interested in the `${WATCHEXEC_META_CHANGED_PATH}` variable at all and thought I'm using `${WATCHEXEC_COMMON_PATH}`. :unamused: Thanks a lot for pointing me in the right direction.
