### ISSUE TITLE
Missing some modifications

### ISSUE THREAD

**Issue by mwean** [watchexec/watchexec#177]
I'm trying to migrate from `entr`, but it seems like `watchexec` is missing some of the modifications that `entr` picks up. Specifically, I have a file (a SQLite WAL, if it matters) where the file is accessed and updated, but `watchexec` isn't triggered.

My `watchexec` command is `watchexec -v --no-ignore --no-default-ignore echo update`

I can see the access, modification, and inode change times are all updated:

```
$ stat -f "%a - %m - %c" chat.db-wal
1615753045 - 1615753049 - 1615753049
$ stat -f "%a - %m - %c" chat.db-wal
1615753213 - 1615753213 - 1615753213
```

The strange thing is it _does_ see the modification if I `touch` the file. Is there some kind of update that `watchexec` can't see?

**Comment by passcod** [comment]
Notify v4 doesn't handle IN_ACCESS events iirc, that might be it? Don't know if there's a way for entr to report the events it's seeing

**Comment by mwean** [comment]
It says it's using "kqueue(2) or inotify(7)". I don't see any way to get verbose output.

**Comment by passcod** [comment]
kqueue on bsd, inotify on linux, we also use inotify via the underlying library notify, which doesn't report access events (it does in v5 which is in progress)

If you're on bsd though that will be using polling, there's no kqueue support in notify

**Comment by passcod** [comment]
or mac, same as bsd

**Comment by mwean** [comment]
Ah yeah I'm on mac, so I should probably just stick with entr :( thanks for your help!

**Comment by passcod** [comment]
oh, on mac. different story, yeah.

on mac, notify uses a different API from apple, fsEvents, which is a lot more efficient but also only reports batches of modifications, which delays up to 30 seconds. using kqueue would probably have been the better choice but, hindsight, etc.

check back later! a kqueue backend for notify is on the cards, it might happen
