### ISSUE TITLE
Split value of --shell to parse for options

### ISSUE THREAD

**Issue by ngirard** [watchexec/watchexec#181]
Heya,
I was unsure whether writing e.g.
```sh
watchexec -w . --shell "bash -o errexit" ls
```
is possible, until I tried it.
Perhaps it could be mentioned in the README / cli help ?

Cheers, and thanks for the new release and your efforts with packaging. The deb packages were especially appreciated !

**Comment by passcod** [comment]
We could instead split on spaces and accept arguments! It would be quite simplistic (anything quoted won’t work properly), but it would allow basic shell options such as this.

**Comment by ngirard** [comment]
Well sure ! I didn't want to bother you with a feature request, but I guess it wouldn't be too painful to add.

Documentation-wise, it would then be worth reminding people to make sure they add such `-c` option to their unix shell -- not sure about the equivalent for `cmd.exe` at the time of writing.

**Comment by passcod** [comment]
I'll probably let watchexec manage the `-c` option and equivalent by itself and just insert the options if present. If one wants something more complex it can be done with `--shell=none` and having the shell invocation as the command.

**Comment by ngirard** [comment]
Aha. Makes sense !

**Comment by ngirard** [comment]
Nice ! Thanks for your work !

**Comment by passcod** [comment]
Released in 1.15.1
