### ISSUE TITLE
Issues with termination on Windows

### ISSUE THREAD

**Issue by passcod** [watchexec/watchexec#184]
Need to investigate if/why that's still an issue.

From these:
- https://github.com/passcod/cargo-watch/issues/86
- https://github.com/passcod/cargo-watch/issues/126

**Comment by timonsku** [comment]
I'm seeing a similar issue on Linux via SSH at least. I have a Python script running and ctrl+c does not exit watchexec.
Command being `sudo watchexec python myscript.py`

**Comment by passcod** [comment]
If trivial python works but your script doesn't I'm going to say it's probably your script? If it's doing anything fancy with the terminal or spawning child processes or job control...

Can you:
- write something in your Python to log out any signals received
- check if it works without sudo (running directly as root, if your program requires it)
- reduce your Python script to a reproduceable case
- enable watchexec's verbose logs

**Comment by passcod** [comment]
Was an issue with command-group, has since been patched.

**Comment by timonsku** [comment]
ah sorry didn't realize I never responded to this, glad you found the cause
