### ISSUE TITLE
Reset terminal state when command ends

### ISSUE THREAD

**Issue by passcod** [watchexec/watchexec#186]
It would be good and probably solve a few issues to reset the terminal state when the command ends. Specifically thinking of Alternate Screen and Raw Mode.

May be what's happening in #185.

Could be good to include in spinoff util crate suggested in #171.

**Comment by passcod** [comment]
This is implemented library-side, just needs a CLI option

**Comment by ModProg** [comment]
Thinking about it, this sounds like a sensible default, maybe it makes more sense to add a flag to disable this?

**Comment by ModProg** [comment]
Reading it, it looks like it will also clear so maybe only sensible to enable automatically together with `--clear`.

**Comment by passcod** [comment]
This is slated to arrive next version in the form `--clear=reset`.

**Comment by passcod** [comment]
Done in 1.22.0.
