### ISSUE TITLE
WinSxS errors since 1.15.2

### ISSUE THREAD

**Issue by jdknezek** [watchexec/watchexec#192]
Since 1.15.2, when installing via `cargo install`, I am unable to run the program on Windows.

The error I receive on the CLI is:

```
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

Checking the Windows Event Viewer Application error log, I find the following error:

```
Activation context generation failed for "C:\Users\$USER\.cargo\bin\watchexec.exe". The setting http://schemas.microsoft.com/SMI/2020/WindowsSettings^activeCodePage is not registered.
```

In case it helps, my environment versions are:
- Windows: Version	10.0.19042 Build 19042
- rustc: 1.51.0 (2fd73fabe 2021-03-23)
- cargo: 1.51.0 (43b129a20 2021-03-16)

Installing `--version 1.15.1` fixes the problem.

Please let me know if there's anything I can do to help debug! Thank you!

**Comment by jdknezek** [comment]
Trying out this latest commit, I now get an error on `^longPathAware`. I think maybe the different settings need to live under different namespaces based on https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema ? I'm poking around.

**Comment by jdknezek** [comment]
It's ugly, but this seems to work (based on master):

```xml
        <windowsSettings>
            <ws:longPathAware xmlns:ws="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</ws:longPathAware>
            <ws:activeCodePage xmlns:ws="http://schemas.microsoft.com/SMI/2019/WindowsSettings">true</ws:activeCodePage>
            <ws:heapType xmlns:ws="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</ws:heapType>
        </windowsSettings>
```

In particular it looks like each of those settings ONLY exists under the specific year's namespace (from https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema):

```xml
  <!-- WindowsSettings elements from XML namespace http://schemas.microsoft.com/SMI/2005/WindowsSettings
  -->
  <ElementType name="dpiAware" /> 

  <!-- WindowsSettings elements from XML namespace http://schemas.microsoft.com/SMI/2011/WindowsSettings
  --> 
  <ElementType name="autoElevate" /> 
  <ElementType name="disableTheming" /> 
  <ElementType name="disableWindowFiltering" /> 
  <ElementType name="highResolutionScrollingAware" /> 
  <ElementType name="printerDriverIsolation" /> 
  <ElementType name="ultraHighResolutionScrollingAware" /> 

  <!-- WindowsSettings elements from XML namespace http://schemas.microsoft.com/SMI/2016/WindowsSettings
  -->
  <ElementType name="dpiAwareness" />
  <ElementType name="longPathAware" />

  <!-- WindowsSettings elements from XML namespace http://schemas.microsoft.com/SMI/2017/WindowsSettings
  -->
  <ElementType name="gdiScaling" />

  <!-- WindowsSettings elements from XML namespace http://schemas.microsoft.com/SMI/2019/WindowsSettings
  -->
  <ElementType name="activeCodePage" />

  <!-- WindowsSettings elements from XML namespace http://schemas.microsoft.com/SMI/2020/WindowsSettings
  -->
  <ElementType name="heapType" />
```

**Comment by passcod** [comment]
> In particular it looks like each of those settings ONLY exists under the specific year's namespace

Ugh. Really? 🤮

**Comment by passcod** [comment]
Not sure why CI was fine with it

**Comment by passcod** [comment]
Thanks for trying it out though!

**Comment by jdknezek** [comment]
Yeah, CI passing is curious! But it's worked on two different machines of mine now so 👍 hopefully!
