### ISSUE TITLE
Doesn't work for apps that use `/dev/tty` ?

### ISSUE THREAD

**Issue by abitrolly** [watchexec/watchexec#194]
Can't monitor TUI app with `watchexec` 1.15.3.

```bash
$ git clone https://github.com/awesome-gocui/gocui
$ cd gocui/_examples
$ watchexec -n -r -e go go run keybinds.go
2021/05/07 11:52:59 Failed to initialize tcell screen: open /dev/tty: no such device or address
panic: Failed to initialize tcell screen: open /dev/tty: no such device or address


goroutine 1 [running]:
log.Panicln(0xc00004ff50, 0x1, 0x1)
	/usr/lib/golang/src/log/log.go:368 +0xae
main.main()
	/tmp/gocui/_examples/keybinds.go:37 +0xb3
exit status 2
^C
```

`go run keybinds.go` without `watchexec` gives this.

![image](https://user-images.githubusercontent.com/8781107/117425026-0fe43280-af2b-11eb-9842-fcd4976976f0.png)

**Comment by passcod** [comment]
Yeah, that's not supported (yet).

**Comment by passcod** [comment]
Yeah, alright, so /dev/tty isn't available, but most "production" TUIs work fine, as they don't use that device. E.g. vim, less, etc.

gocui's dependency's tcell actually changed from going the way most programs do it to using /dev/tty recently: https://github.com/gdamore/tcell/pull/433

**Comment by abitrolly** [comment]
I looked a bit for alternatives and found out https://github.com/wtetsu/gaze which worked for me.

**Comment by abitrolly** [comment]
I wish I could tell, but I don't know how terminal sharing works between processes.
