### ISSUE TITLE
[feature request] Run command on a specific event type.

### ISSUE THREAD

**Issue by queeup** [watchexec/watchexec#196]
I really like to have trigger command with a specific event (just on CREATE event for example) like `inotifiywait` without needing a wrapper (`inotifywait --event create`)

~~Is there a way to run command on CREATE? Without scripting? Like `inotifywait --event create`~~

**Comment by passcod** [comment]
Not directly at the moment, but you can write a wrapper script that "filters" on the presence of `WATCHEXEC_CREATED_PATH`, for example

**Comment by queeup** [comment]
Thank you. Is it possible to feature request for this? May I edit this issue as a feature request?

**Comment by passcod** [comment]
Absolutely, do go on

**Comment by queeup** [comment]
Let me write it down one example for making it with wrapper:

```bash
test -n "${WATCHEXEC_CREATED_PATH}" && \
    (printf "${WATCHEXEC_CREATED_PATH} directory created."; ls ${WATCHEXEC_CREATED_PATH}) || :
```

**Comment by archiif** [comment]
For Windows:
```bat
IF DEFINED WATCHEXEC_CREATED_PATH echo "%WATCHEXEC_CREATED_PATH% path created"
```

**Comment by passcod** [comment]
This is now possible with the (experimental) tagged filterer mode:

```
$ env WATCHEXEC_FILTERER=tagged watchexec -f "kind=Create(*)" ...
```

Keeping this open until the feature makes it out of experimental options :)

**Comment by passcod** [comment]
Has been fully possible for a while with `--fs-events`.
