### ISSUE TITLE
Question: Loading Bash Profile

### ISSUE THREAD

**Issue by d4hines** [watchexec/watchexec#199]
Hi!
`watchexec` is really handy. But I'm having trouble getting it to interact  with my bash environment.

Suppose I have the following at the beginning of my .bash_profile:
```
alias foo='echo hello world'
```
When I run `watchexec ... foo`
bash complains:
```
bash: foo: command not found
```
How can I force bash to respect my .bash_profile? I'm using a modified version of the defaults that ship with Ubuntu, which includes:
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
However, I tried putting my alias above that line and got the same results.
Thanks!

**Comment by passcod** [comment]
Try with `--shell=bash`. By default it uses `sh`, which is probably not bash (on ubuntu it's probably dash).

**Comment by d4hines** [comment]
I tried with `--shell=bash` and get the same error. Any ideas to try?

**Comment by passcod** [comment]
This has less to do with watchexec and more with how shells behave. In this case, [the relevant section](https://man.archlinux.org/man/core/bash/bash.1.en#INVOCATION) from the bash manpage:

> A login shell is one whose first character of argument zero is a `-`, or
> one started with the `--login` option.
> 
> An interactive shell is one started without non-option arguments (unless
> `-s` is specified) and without the `-c` option whose standard input and
> error are both connected to terminals (as determined by `isatty(3)`),
> or  one  started with the `-i` option.  `PS1` is set and `$-` includes
> `i` if bash is interactive, allowing a shell script or a startup file to
> test this state.
> 
> The following paragraphs describe how bash executes its startup files.
> If any of the files exist but cannot be read, bash reports an error.
> Tildes are expanded in filenames as described below under "Tilde Expansion"
> in the EXPANSION section.
> 
> When bash is invoked as an interactive login shell, or as a
> non-interactive shell with the `--login` option, it first reads and
> executes commands from the file `/etc/profile`, if that file exists.
> After  reading  that  file,  it looks  for `~/.bash_profile`,
> `~/.bash_login`, and `~/.profile`, in that order, and reads and executes
> commands from the first one that exists and is readable.  The
> `--noprofile` option may be used when the shell is started to inhibit
> this behavior.
> 
> [...]
> 
> When an interactive shell that is not a login shell is started, bash
> reads and executes commands from `~/.bashrc`, if that file exists.
> This may be inhibited by using the `--norc` option.
> The `--rcfile` file option will force bash to read and execute commands
> from file instead of `~/.bashrc`.

So, you need to invoke bash as a login shell for it to read the profile scripts:

    $ watchexec --shell='bash --login' -- command...

Some examples of behaviour for reference (`~/.bashrc` has been edited so its first line contains `echo Hi from bashrc`):

```
$> bash
Hi from bashrc
[passcod@kaydel-ko passcod.name]$
```

```
$> watchexec --shell=bash date
Sat 12 Jun 2021 13:38:25 NZST
```

```
$> watchexec --shell='bash --login' date
Hi from bashrc
Sat 12 Jun 2021 13:38:36 NZST
```

```
$> watchexec --shell='bash --rcfile $HOME/.bashrc' date
Sat 12 Jun 2021 13:39:03 NZST
```

```
$> watchexec --shell='bash --rcfile $HOME/.bashrc --login' date
Hi from bashrc
Sat 12 Jun 2021 13:39:16 NZST
```

Two things to note:

1. (as per manpage excerpt above) your bashrc will probably contain a line like this:

   ```bash
   [[ $- != *i* ]] && return
   ```

   which will stop executing the bashrc if not running interactively.

2. This restriction may be for good reasons: I'd recommend having your aliases in files separate from your bashrc/bash_profile/etc and sourcing that file from your bashrc, and then using just that file from the watchexec invocation:

   ```
   $ watchexec --shell='bash --rcfile $HOME/.bash_aliases --login' -- aliased_command
   ```

Left to your discretion is how to alias this watchexec invocation so it's not a verbose pain to use...

**Comment by d4hines** [comment]
First, thanks for the detailed reply @passcod! 🙏

With some additional help from StackOverflow, I discovered the correct incantation is something like:
```
watchexec --shell='bash --login -O expand_aliases' -- some_alias
```
And, as you suggested, I can bundle this lengthy command into another alias for deftness 😎

Appreciate the help!
