### ISSUE TITLE
The --watch-when-idle switch masks all further events

### ISSUE THREAD

**Issue by pvonmoradi** [watchexec/watchexec#200]
I'm using `watchexec 1.16.1` on Xubuntu 18.04. To my understanding, if I use `-W`switch, events should be masked **while** the command is still running. After the command exists, any events should execute the command again.  
This is not the case for me:  

https://user-images.githubusercontent.com/1058151/123958506-649fa900-d9c2-11eb-8d3d-99fab979bdf8.mp4

As you can see, in first experiment (with `-W` switch), I was expecting late events to actually fire but only the first one got executed.  
The functionality without (`-W`) (second experiment) is correct according to manpage.

**Comment by passcod** [comment]
Hmm, yes, you're correct.

**Comment by passcod** [comment]
Also want to thank you for an _excellent_ bug report! The video was very helpful 💜

**Comment by pdecat** [comment]
I had the same issue, and can report the change from the linked PR works for me!

```cargo install --force watchexec-cli --branch on-update/bug-200 --git https://github.com/watchexec/watchexec.git```

**Comment by passcod** [comment]
@pdecat thanks for the report! what OS are you running? I'm basically blocking until I have time to test on windows

**Comment by pdecat** [comment]
You're welcome :slightly_smiling_face:  I'm running Ubuntu and Arch, no Windows.

**Comment by passcod** [comment]
Tested and fixed on Windows, so merged. This will get released hopefully this weekend, as time allows.
