### ISSUE TITLE
Can not watch /sys/class files

### ISSUE THREAD

**Issue by pvonmoradi** [watchexec/watchexec#201]
Is it possible to watch Linux virtual files like `/sys/class/net/wlp3s0/statistics/rx_bytes` with watchexec?  
```
watchexec -w /sys/class/net/wlp3s0/statistics/rx_bytes --changes-only -p -- 'echo "Fired!" | ts'
watch -n0.5 -d cat /sys/class/net/wlp3s0/statistics/rx_bytes
```
I've tested the commands above. Regular `watch` works fine but `watchexec` doesn't fire once:  

https://user-images.githubusercontent.com/1058151/123963209-7b94ca00-d9c7-11eb-81c8-090500fa6b43.mp4

```
λ watchexec --version && watch --version
watchexec 1.16.1
watch from procps-ng 3.3.12
```

**Comment by passcod** [comment]
Only with polling. I don't think /sys implements the inotify interface.
