### ISSUE TITLE
Trigger event only when file contents change

### ISSUE THREAD

**Issue by qtfkwk** [watchexec/watchexec#204]
Apologies if this has already been addressed somewhere. I searched but did not find anything.

The cargo-watch (and watchexec) documentation suggests that the command should be run when watched files *change* or are *modified*; however after using cargo-watch a little bit it seems the command is still ran when files are *saved* but not *modified*.

I'm wondering if there is any option or perhaps a planned feature that I'm missing that would detect a *save* event (write to a watched file), but also tracks files' content by hash (SHA256?) to tell if it *actually changed*. If the file did not change, there is little point in running the command, right?

Events like new or moved files should not be affected because those should undoubtedly cause the command to run.

cargo-watch has otherwise been a great help in streamlining my workflow... Thanks!

**Comment by qtfkwk** [comment]
Probably would want to add a maximum file size option for a contents change feature and set a sane default to accommodate the typical maximum size of a source code file (1 MB?).

Yep, agree on a non-crypto hash... speed is the priority here.

Took a look at https://github.com/watchexec/watchexec/issues/67 ... a contents change feature would definitely prevent that and deviate from current behavior... I'd recommend it not being the default. Also I'm assuming that it would actually require a change in watchexec that would be utilized by cargo-watch?

**Comment by passcod** [comment]
Implemented as filter programs in #571, see https://github.com/watchexec/watchexec/discussions/592#discussioncomment-5896857

**Comment by qtfkwk** [comment]
Very cool! Thank you for this.
