### ISSUE TITLE
[Question] How to run function instead of command?

### ISSUE THREAD

**Issue by rEnr3n** [watchexec/watchexec#206]
Sample script:

```
notify() {
  file="$WATCHEXEC_CREATED_PATH"
  echo "$file"
}

watchexec -p notify
```

Running it gives me an error "command not found". I could put the function to another script but I prefer against doing it. How can I go about this?

**Comment by passcod** [comment]
You can't. That's not how programs work on the shell.

You can inline the entire function in the watchexec command if you want:

```
watchexec ... <<EOF
foo() {
}

foo
EOF
```

or something, but I suspect that's not what you want to do. Unfortunately, there's just no way to do what you want with watchexec.

Perhaps you'd be better served with something like `inotify-wait`:

```bash
while true; do
  inotify-wait ...
  yourfunction
done
```

**Comment by rEnr3n** [comment]
Did you mean `inotifywait`? I'm actually looking for alternatives as I'm getting issues with it.

**Comment by passcod** [comment]
Yeah, that. You could _possibly_ send a signal to the calling script, something like this:

```bash
trap yourfunction USR2

watchexec -- "kill -USR2 $$"
```

**Comment by chasecaleb** [comment]
> You can't. That's not how programs work on the shell.

You're right that they don't work like this automatically, but if you export the function it works.

---

Here's a simple solution:

``` bash
on_change() {
    echo "On change called for: $WATCHEXEC_COMMON_PATH"
}
# Makes the function visible to child processes.
export -f on_change
watchexec -- on_change
```

**Comment by passcod** [comment]
Good tip! Note that this is a bashism or other shell -ism (it's not in POSIX `export`) and may not work if `sh` is not `bash`.
