### ISSUE TITLE
Upgrade to notify 5.0.0

### ISSUE THREAD

**Issue by xanderio** [watchexec/watchexec#208]
This version of notify if still in pre-release.

The upcoming 5.0.0 release of `notify` includes some breaking API changes, but also a `kqueue` backend, which allows BSD users to not be force to use a PollWatcher.

I did some initial testing on how complicated an update to the 5.0.0 version will be and my initial impression is the while not impossible, it'll require a bit of work. The way events are reported to the library consume was completely overhauled.

The [`RawEvent`](https://docs.rs/notify/4.0.17/notify/struct.RawEvent.html) struct is gone and its replaces with a new [`Event`](https://docs.rs/notify/5.0.0-pre.12/notify/event/struct.Event.html) struct. I'm not sure what the best cause of action is in the case, for now i see two options. Either convert the new `Event` into one or more `PathOp`s or rewrite things to more in line with the new `Event`. All thought the last option would probably entail a breaking API change for this create.

**Comment by passcod** [comment]
This is already in progress in the `tokio` branch, see #205 for status.

**Comment by xanderio** [comment]
Thanks, for clearing this up. I saw that issue, but i was simply not aware at this also included the upgrade to notify 5.0.0
