### ISSUE TITLE
How to best use with a tool like pdb?

### ISSUE THREAD

**Issue by max-sixty** [watchexec/watchexec#209]
Firstly, thank you for the brilliant tool — I've spent many years using things like `pytest -f` and https://github.com/joeyespo/pytest-watch with varying success, and `watchexec`'s configurability (e.g. for which files to watch & ignore) and reliability makes this sort of iterative testing much easy and fun.

One issue I have — and I'm not sure whether this is sufficient to reproduce, happy to provide more details — is using it in combination with something like `--pdb`, which drops to a debugger on an error; e.g.:

```
# in python project

❯ watchexec -rn -- pytest --pdb
Test session starts (platform: darwin, Python 3.8.10, pytest 6.2.4, pytest-sugar 0.9.4)
rootdir: /Users/maximilian/workspace/xarray, configfile: setup.cfg, testpaths: xarray/tests, properties
plugins: anyio-2.2.0, cov-2.12.0, testmon-1.1.1, xdist-2.3.0, sugar-0.9.4, forked-1.3.0, accept-0.1.4
collecting ...

――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR at setup of TestDatetimeAccessor.test_field_access[year] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[...]
        self.times = pd.date_range(start="2000/01/01", freq="H", periods=nt)

>       raise ValueError
E       ValueError

/Users/maximilian/workspace/xarray/xarray/tests/test_accessor_dt.py:29: ValueError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/maximilian/workspace/xarray/xarray/tests/test_accessor_dt.py(29)setup()
-> raise ValueError
(Pdb)   # success, and works when entering commands etc
```

It drops into a debugger successfully.

But here's the issue — when exiting with `C-c`, it exists to the shell, but `pdb` somehow isn't killed, and subsequently appears in later prompts; e.g. see below after hitting return a couple of times:

```
 --KeyboardInterrupt--
(Pdb) ⏎                                                                                                                                                                        

# Back to the shell
❯
# <Enter>
❯
(Pdb)   # this shouldn't be here! pdb should be dead
```

Let me know if more detail is helpful — thanks again.

**Comment by passcod** [comment]
That _should_ be taken care of via process groups, but I'm guessing the debugger does Weird Stuff that detaches it from that. Maybe sets up a new session for itself.

You can try with `--no-process-group` to disable the process group... a bit counter-intuitive but it could help target the right thing.

**Comment by passcod** [comment]
Also going via a shell (instead of using `-n`) may help, as the shell would be killed and probably take care of its descendants.

**Comment by max-sixty** [comment]
`--no-process-group` seems to help a lot! It now prints something a couple of seconds later, but that's the end of it:

```
(Pdb) ⏎                                                                                                                                                                        

❯

❯


❯
=========================================================================== short test summary info ===========================================================================
FAILED xarray/tests/test_accessor_dt.py::TestDatetimeAccessor::test_field_access[year] - ValueError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: Quitting debugger !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Results (15.95s):
       1 error

❯
```

Running with / without a shell (in this case, fish), didn't seem to affect it, either with / without process groups.

Thanks for the fast response! I'll close because I'm set, cheers!

**Comment by max-sixty** [comment]
FYI @passcod while the `--no-process-group` solves the leaking process problem, after one restart, `pdb` won't display keystrokes. They do seem to register — i.e. typing `print("hi")` will print `hi` — but the `print("hi")` characters won't be shown at the prompt.

I'm guessing this is difficult and at least partly the fault of pdb (I wonder whether gdb has the same issue?) so no need to reopen, and I continue to heart `watchexec` for the non-pdb use cases!

**Comment by passcod** [comment]
Hmm, try resetting the terminal before running the command, for that. Something like (with a shell) `-- 'tput reset; your command'`. pdb should probably be doing that in some way itself, but it may be that the way it's restarted under watchexec prevents it from doing so.

**Comment by max-sixty** [comment]
FYI I've been doing more python debugging recently, and had been manually restarting the debugger, which inspired me to come back here and find there was a solution!

But I tried the `tput reset` suggestion, but I haven't got it working with the latest version unfortunately.

A few findings:
- `watchexec -r --no-process-group -e py --shell=bash -- 'tput reset; pytest --pdb'` doesn't show any input at all 
after the first restart. It does retain all input — so typing `print("abc")` shows:
  ```
  (Pdb) abc
  ```
- As before, without the `tput reset`, we get that too.
- `watchexec -r --no-process-group -e py --shell=fish -- 'tput reset; pytest --pdb'` is quite weird — it shows _some_ keystrokes. And it retains some of them, and repeats others from previous lines. It almost feels like someone is trolling.
- `watchexec -r -e py -- 'fish -c "pytest --pdb"'` is the same as the initial result

Notably `watchexec -r -e py -- 'read -p "Enter some input:" x; echo $x'` _does_ work — so I'm guessing it's something to do with the TTY rather than stdin...

I would really love to get this working, to replicate the manual thing I do of `C-c, <up>, <return>, (wait!)` — happy to try anything.

Thanks a lot in advance.

**Comment by max-sixty** [comment]
A couple of other notes; 
- `--clear=reset` doesn't allow _any_ input, even before the first restart. That's the case with the `read` example as well as the `pytest` one
- https://github.com/watchexec/watchexec/issues/655 is possibly related?

**Comment by passcod** [comment]
Yeah I'm guessing this is #655, it seems similar in cause

**Comment by max-sixty** [comment]
OK, feel free to close as a dupe. Thanks.
