### ISSUE TITLE
watchexec seems to change how some options are passed to child commands

### ISSUE THREAD

**Issue by max-sixty** [watchexec/watchexec#214]
Again, thanks a lot for `watchexec`, it's great.

It's possible this is a problem with fish shell or "the user", but it is a bit surprising:

```sh
pytest -k 'dataset or dataarray'
```

...works great — the string is passed to pytest, which interprets it as a filter — but prefixing with `watchexec`...

```sh
watchexec -- pytest -k 'dataset or dataarray'
```

...raises an error: 

```sh
ERROR: file or directory not found: or
```

...suggesting that `watchexec` might be changing how the string is passed to pytest such that it's being passed like `pytest -k dataset or dataarray` — could that be happening?

**Comment by passcod** [comment]
Yeah, it does. Try with `-n`.

**Comment by passcod** [comment]
Or wrap the entire command in quotes

**Comment by max-sixty** [comment]
Thanks @passcod !
