### ISSUE TITLE
Unexpected end of filter rule when command run through watchexec

### ISSUE THREAD

**Issue by paw-lu** [watchexec/watchexec#222]
I'm looking to run this command through watchexec:

```sh
# This will actually fail, but enough for this example
% rsync --filter=":- .gitignore"
```

When trying to run through watchexec:

```sh
% watchexec -- rsync --filter=":- .gitignore"
unexpected end of filter rule: :-
```

Having a hard time understanding what watchexec is doing here that changes the interpretation of the `filter` arg value.

**Comment by passcod** [comment]
You'll want to either quote the entire command or to pass `-n` to watchexec

**Comment by paw-lu** [comment]
`-n` works here. Appreciated! Why does running in the shell cause issue with the `filter` arg value?

**Comment by passcod** [comment]
For historical reasons, the default behaviour, which is likely to get changed in a future breaking change (this is a somewhat common issue, but also this tool has not broken back compat yet — makes for a rather high bar), is to accept things like

    watchexec -- date \; date

Which runs

     sh -c "date ; date"

That is, we take all arguments and join them with spaces. Unfortunately there's no good way to handle arguments with spaces in them in this context. (You may think there is, but I've been attempting this dance in many ways for several years, and the corner cases are _biting_.)

So your command runs this:

    sh -c "rsync --filter=:- .gitignore"
