### ISSUE TITLE
Pure 64 bit builds for windows

### ISSUE THREAD

**Issue by lublak** [watchexec/watchexec#223]
Currently, it would be very practical if pure 64bit builds for windows were also available.
This would facilitate the use in nanoservers.
Nanoservers only allow the use of pure 64 bit applications.

**Comment by passcod** [comment]
I don't understand what that means, practically speaking. Can you clarify? The windows builds produced here _are_ 64-bit. What do I need to do to build "pure" 64-bit builds?

**Comment by lublak** [comment]
@passcod I think I made a mistake with the name of x86_64. x86 so 32 bit and 64 bit. I thought it was an anycpu build.
Of course if it is 64 bit it should work great in a nanoserver. I will try it out in the next few days.
