### ISSUE TITLE
`watchexec` fails with Permission denied (os error 13) when running `cargo doc`

### ISSUE THREAD

**Issue by oliver-impero** [watchexec/watchexec#226]
Running `cargo doc` works, but `cargo watch -x doc` fails with

    Error: I/O error: Permission denied (os error 13)

When I try `watchexec` directly, it also fails. Any idea why? :)
```
$ export RUST_BACKTRACE=full
$ export COLORBT_SHOW_HIDDEN=1
$ RUSTDOCFLAGS="--enable-index-page -Zunstable-options" watchexec -r -e rs "cargo doc --workspace"
Error:
   0: I/O error: Permission denied (os error 13)

Location:
   /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/core/src/result.rs:1911

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::h61c5d51fa255e2f0
      at <unknown source file>:<unknown line>
   2: eyre::capture_handler::h97979793fd56faca
      at <unknown source file>:<unknown line>
   3: watchexec::main::h517283b99160e813
      at <unknown source file>:<unknown line>
   4: std::sys_common::backtrace::__rust_begin_short_backtrace::h98321e7cc3bc7c59
      at <unknown source file>:<unknown line>
   5: std::rt::lang_start::{{closure}}::h4d5ee13323a10513
      at <unknown source file>:<unknown line>
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6743157f0325d450
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/core/src/ops/function.rs:259
   7: std::panicking::try::do_call::hc65378359d322d46
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:406
   8: std::panicking::try::h52b83ca0140efb28
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:370
   9: std::panic::catch_unwind::h0ba25f4b0d3448dc
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panic.rs:133
  10: std::rt::lang_start_internal::{{closure}}::ha65f28100c5ad390
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/rt.rs:128
  11: std::panicking::try::do_call::h5db5edfaf5b749d9
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:406
  12: std::panicking::try::h62409771d6cd0419
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:370
  13: std::panic::catch_unwind::h386261fb8f018fab
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panic.rs:133
  14: std::rt::lang_start_internal::h699f3530566c1833
      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/rt.rs:128
  15: main<unknown>
      at <unknown source file>:<unknown line>
  16: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  17: _start<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by passcod** [comment]
Sure, some subdirectory isn't readable by the current user, or some other permission issue like that. Cargo watch can't yet tell you which path it's failing to watch (will be in next version), but if you run `tree` or `find .` or `du`, those might tell you. ---- On Wed, 24 Nov 2021 02:04:00 +1300  ***@***.***  wrote ----

Running cargo doc works, but cargo watch -x doc fails with

Error: I/O error: Permission denied (os error 13)



When I try watchexec directly, it also fails. Any idea why? :)

$ export RUST_BACKTRACE=full

$ export COLORBT_SHOW_HIDDEN=1

$ RUSTDOCFLAGS="--enable-index-page -Zunstable-options" watchexec -r -e rs "cargo doc --workspace"

Error:

   0: I/O error: Permission denied (os error 13)



Location:

   /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/core/src/result.rs:1911



  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::h61c5d51fa255e2f0

      at <unknown source file>:<unknown line>

   2: eyre::capture_handler::h97979793fd56faca

      at <unknown source file>:<unknown line>

   3: watchexec::main::h517283b99160e813

      at <unknown source file>:<unknown line>

   4: std::sys_common::backtrace::__rust_begin_short_backtrace::h98321e7cc3bc7c59

      at <unknown source file>:<unknown line>

   5: std::rt::lang_start::{{closure}}::h4d5ee13323a10513

      at <unknown source file>:<unknown line>

   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6743157f0325d450

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/core/src/ops/function.rs:259

   7: std::panicking::try::do_call::hc65378359d322d46

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:406

   8: std::panicking::try::h52b83ca0140efb28

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:370

   9: std::panic::catch_unwind::h0ba25f4b0d3448dc

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panic.rs:133

  10: std::rt::lang_start_internal::{{closure}}::ha65f28100c5ad390

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/rt.rs:128

  11: std::panicking::try::do_call::h5db5edfaf5b749d9

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:406

  12: std::panicking::try::h62409771d6cd0419

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panicking.rs:370

  13: std::panic::catch_unwind::h386261fb8f018fab

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/panic.rs:133

  14: std::rt::lang_start_internal::h699f3530566c1833

      at /rustc/db062de72b0a064f45b6f86894cbdc7c0ec68844/library/std/src/rt.rs:128

  15: main<unknown>

      at <unknown source file>:<unknown line>

  16: __libc_start_main<unknown>

      at <unknown source file>:<unknown line>

  17: _start<unknown>

      at <unknown source file>:<unknown line>
