### ISSUE TITLE
deb package install fails if /usr/bin/watchexec already exists

### ISSUE THREAD

**Issue by ngirard** [watchexec/watchexec#233]
Using Watchexec 1.15.1, then 1.18.0 on Ubuntu 21.10.

I stumbled upon this error message when running the following command, which used to work fine:
```sh
watchexec -p -w ~/Obsidian -e md -i './at/' "just handle_md"
Error: I/O error: Bad file descriptor (os error 9)
```

Updated from v1.15.1 to v1.18.0 to no avail.
Suggested `RUST_LOG=1` didn't help.
Adding `--verbose` to invocation didn't help either.
Trying to increase verbosity as [offered by latest release](https://github.com/watchexec/watchexec/releases) using `-vvv` failed with
```
error: The argument '--verbose' was provided more than once, but cannot be used multiple times
```

I'm *not* feeling lucky today !
Any thoughts ?

Cheers

**Comment by passcod** [comment]
If `--verbose` didn't give you a lot of output and `-vvv` didn't work I'm inclined to think you didn't actually upgrade to 1.18. Can you provide:
- output of `watchexec --version`
- logging output from `--verbose`

**Comment by ngirard** [comment]
> I'm inclined to think you didn't actually upgrade to 1.18

As a matter of fact, you're right !
I didn't pay much attention to the output of `dpkg -i` when performing the upgrade, and it turns out that it had failed:

```sh
LANG=C sudo dpkg -i watchexec-1.18.0-x86_64-unknown-linux-gnu.deb
(Reading database ... 524320 files and directories currently installed.)
Preparing to unpack watchexec-1.18.0-x86_64-unknown-linux-gnu.deb ...
Unpacking watchexec-cli (1.18.0) ...
dpkg: error processing archive watchexec-1.18.0-x86_64-unknown-linux-gnu.deb (--install):
 trying to overwrite '/usr/bin/watchexec', which is also in package watchexec 1.15.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 watchexec-1.18.0-x86_64-unknown-linux-gnu.deb
```

**Comment by passcod** [comment]
Guess you need to uninstall the old one first, I'll make a note in the release.

**Comment by ngirard** [comment]
Sure.

Relevant info: https://askubuntu.com/questions/1290262/unable-to-install-bat-error-trying-to-overwrite-usr-crates2-json-which

**Comment by passcod** [comment]
That's probably the same underlying cause. Something to do with this? https://watchexec.github.io/docs/inotify-limits.html or other ulimits

**Comment by ngirard** [comment]
Yeah, I should check that. I already bumped that value years ago, I guess it was reset after a system upgrade.

Thanks for your feedback !

**Comment by ngirard** [comment]
> That's probably the same underlying cause. Something to do with this? https://watchexec.github.io/docs/inotify-limits.html or other ulimits

There might be another problem.
After doing
```
echo 1000000 | sudo tee /proc/sys/fs/inotify/max_user_watches
```
(100,000)
I'm still getting the same error message:
```
[[Native watcher failed to instantiate: Too many open files (os error 24)]]
```

whereas the number of files to watch is just
```sh
find . -type f -name '*.md'|wc -l
4179
```

I should perhaps open a new issue for this ?

**Comment by passcod** [comment]
Given the error code it's likely to be one of these two:

>        EMFILE The per-process limit on the number of open file
>               descriptors has been reached.
> 
>        ENFILE The system-wide limit on the total number of open files
>               has been reached.

(from the inotify_init(2) manpage)

So you'll need to check your system ulimits. Maybe try rebooting in the first instance?

**Comment by ngirard** [comment]
I'm about to file a new issue related to the `Too many open files` error.

This issue is now only about the deb package installation.

**Comment by ngirard** [comment]
I could upgrade flawlessly from v0.18.0 to v0.18.4 using the deb package, so it seems like this issue can be closed as well !
