### ISSUE TITLE
-e .ext doesn't work since the last release.

### ISSUE THREAD

**Issue by thomasf** [watchexec/watchexec#236]
what used to work:

```
watchexec -e .go
```

is now:

```
watchexec -e go
````

I don't know if this is an intended change or not, it does not seem to be listed in the change log.
Many (most?) unix like tools expect the dot to be a part of the extension name so this is a kind of surprising behavior.

**Comment by passcod** [comment]
Totally my oversight. Thanks for reporting!

**Comment by passcod** [comment]
Testing a fix now, should be released soon

**Comment by passcod** [comment]
Released now as 1.18.1.
