### ISSUE TITLE
Windows: "invalid signal `SIGTERM`" error

### ISSUE THREAD

**Issue by rgwood** [watchexec/watchexec#239]
Hi, watchexec seems to have stopped working on Windows as of v1.18. I get an "invalid signal `SIGTERM`: unknown control name" error whenever I try to use it.

watchexec v1.18.1, Windows 11, PowerShell 7.2:

```
❯ watchexec -- echo "hello"
Error:
  × invalid signal `SIGTERM`: unknown control name
```

watchexec v1.17.1, Windows 11, PowerShell 7.2:

```
❯ watchexec -- echo "hello"
hello
```

watchexec v1.18.1, Debian 11, zsh:

```
❯ watchexec -- echo "hello"
hello
```

P.S. `watchexec` is a super useful tool, thank you for making it!

**Comment by passcod** [comment]
Hmm. Thanks for reporting! Can you provide at least the last bunch of lines from a run with `-vvv`? It's going to be extremely verbose, but I'm looking for any hint of where this is coming from to narrow it down. I'll try to get a Windows dev box going.

**Comment by rgwood** [comment]
Sure thing. No additional output with `-vvv`, unfortunately:

```
❯ watchexec -vvv -- echo "hello"
Error:
  × invalid signal `SIGTERM`: unknown control name
```

Happy to try other things if that would help, I'm not much of a Rust programmer but I know my way around the basics.

**Comment by passcod** [comment]
That's enough of a clue, thank you :)

**Comment by mcoret** [comment]
Passing --signal BREAK or --signal CLOSE on the command line seems to work on Windows.

**Comment by passcod** [comment]
Good finding! I'll fix it after work tonight

**Comment by passcod** [comment]
Releasing now as 1.18.2

**Comment by rgwood** [comment]
Confirmed that v1.18.2 works. Thank you for the speedy fix!
