### ISSUE TITLE
"OS error 2" after updating to 1.8.2

### ISSUE THREAD

**Issue by evanleck** [watchexec/watchexec#240]
I just updated watchexec to 1.8.2 via Homebrew on macOS 12.1 and now get an error running the following command:

```
$ watchexec -w app/assets "make build -q || make build"
[[io(spawing process group): No such file or directory (os error 2)]]
```

But running the command `make build` without watchexec works just fine.

**Comment by passcod** [comment]
Log with `-vvv` please

**Comment by evanleck** [comment]
@passcod, sorry, here ya go https://gist.github.com/evanleck/403d8bf4acb762fc7e13484441d991eb

**Comment by passcod** [comment]
Alright, I must have messed up a default, use with `--shell=sh` for now and I'll fix soon

**Comment by evanleck** [comment]
@passcod, thanks, that works! FWIW I'm using Fish shell, but I hadn't had any issues until this update.

**Comment by passcod** [comment]
Will go in 1.18.3

**Comment by evanleck** [comment]
@passcod thanks!
