### ISSUE TITLE
watchexec getting tripped up by .gitignore files outside of the watched directory

### ISSUE THREAD

**Issue by luboslives** [watchexec/watchexec#246]
This is strange because watchexec should not even be looking here and processing these ignore files. I'll give you a simplified breakdown.

The command:
`watchexec -p --no-meta -e jpg,jpeg -w /home/mywebsite.com/html/wp-content/uploads optimize_jpgs.sh`

The error:
`Error: related: [IgnoreFileRead { file: "/home/mywebsite.com/html/wp-content/plugins/.../.gitignore", err: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }]`

_(Occurs twice in two different plugin directories)_

The reason:
`SELinux is preventing /root/.cargo/bin/watchexec from read access on the file .gitignore.`
and
`SELinux is preventing tokio-runtime-w from read access on the file .gitignore.`

So watchexec needs to be watching the uploads directory but these files are in the sibling plugins directory. Is it as simple as missing a trailing slash?

I've had other problems getting SELinux to cooperate with watchexec but maybe that's for another issue.

**Comment by luboslives** [comment]
Version 1.18.2

**Comment by passcod** [comment]
What's your working directory in this case? I.e. why are you using the absolute path here

**Comment by passcod** [comment]
Also if you could give a `-vvv` log, even partial, up where it says `globset filterer built`.

**Comment by luboslives** [comment]
> What's your working directory in this case? I.e. why are you using the absolute path here

I'm running it from an auto-starting systemd service, which requires absolute paths

**Comment by passcod** [comment]
It requires absolute paths for some things, but probably not that: you could set the `WorkingDirectory=` to the absolute path, and use an `ExecStart=/path/to/watchexec ...` and it would do the same thing. That's orthogonal, though, and won't fix the problem.

The main issue is that Watchexec tries to be correct in ignoring paths, so it goes to what it thinks is the "origin" of a project, which in your case is likely to be `/home/mywebsite.com/html`, and looks up ignorefiles from there. The main idea being that if you're working in a subdirectory but an ignore in a parent (or sibling/cousin etc, it can get complex) directory in the same project is saying "ignore .xyz files", it's unexpected that watchexec wouldn't ignore .xyz files.

If that's incorrect, there's currently no way to override that: I'll have to add an option.

The `IgnoreFileRead` error you're getting is a runtime error, and it shouldn't abort watchexec (if it does, that's a further issue), so it's more like a notice/warning in that case.

**Comment by passcod** [comment]
It may create other problems, but you could do things with systemd's chroot/filesystem isolation features (as a workaround).

**Comment by luboslives** [comment]
Thanks for the explanation, it seems like it's mainly an SELinux problem then. When I set it to permissive mode, no errors.

I try to create a policy exactly as its diagnostic tool suggests, but it still performs the same block 🙃 I'd have to learn how to allow read access on dot-files in users' home directories... if SELinux was at all easy to learn.

**Comment by passcod** [comment]
1.19 will have a new option `--project-origin` to override this.
