### ISSUE TITLE
Native watcher failed to instantiate: Too many open files (os error 24)

### ISSUE THREAD

**Issue by ngirard** [watchexec/watchexec#251]
Using Watchexec 1.18.0 on Ubuntu 21.10.

As already mentionned in #233, the same invocation of watchexec now raises
```
[[Native watcher failed to instantiate: Too many open files (os error 24)]]
```
whereas it used to run flawlessly.

@passcod commented:

> Given the error code it's likely to be one of these two:
> 
> > ```
> >    EMFILE The per-process limit on the number of open file
> >           descriptors has been reached.
> > 
> >    ENFILE The system-wide limit on the total number of open files
> >           has been reached.
> > ```
> 
> (from the inotify_init(2) manpage)
> 
> So you'll need to check your system ulimits. 

I managed to solve this by adding
```
ngirard          -       nofile          65536
```
to `/etc/security/limits.conf` and then restart my system.
I didn't find an authoritative documentation, but I found [this page](https://djangoadventures.com/how-to-increase-the-open-files-limit-on-ubuntu) to be a good read.

I'm reporting this here because:

1. Since it was not straightforward, I wish to suggest adding some guidance it to watchexec's README.
2. Since the error message was scarce: how about supplementing it with an additional pointer to the solution ?
3. I'm confused by Watchexec's behaviour in this scenario. Indeed, an error is reported, but the program keeps running. If the native watcher couldn't be instantiated, why not exiting the program ? Also, after such error message, I'm left with the feeling that the program won't keep running properly.

**Comment by passcod** [comment]
Some errors not being fatal anymore _is_ mentioned in the release notes. This one probably should be, though, so I'll upgrade it, and add some help text for potential solutions.

**Comment by ngirard** [comment]
Rather than modifying `/etc/security/limits.conf` as I wrote before, it's best to add a `.conf` file into `/etc/security/limits.d`. The contents should be the same as described above.
For reference, see `man pam_limits`.

**Comment by passcod** [comment]
Will be done in 1.18.6.

**Comment by passcod** [comment]
Released now.

**Comment by ngirard** [comment]
Great, thanks !
