### ISSUE TITLE
io(spawing process group): No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ngirard** [watchexec/watchexec#252]
Using Watchexec 1.15.1, then 1.18.0 on Ubuntu 21.10.

I'm filing it as a bug since the [changelog for v1.18.0](https://github.com/watchexec/watchexec/releases/tag/cli-v1.18.0) says
> Any change in behaviour other than listed below is a bug.

With watchexec 1.15.1, I was using the following invocation flawlessly:
```sh
watchexec -p -w ~/Obsidian -e md -i './at/' "just handle_md"
```
Now, the same invocation using watchexec 1.18.0 triggers
> [[io(spawing process group): No such file or directory (os error 2)]]

1. The invocation needs to be changed as
    ```sh
    watchexec -p -w ~/Obsidian -e md -i './at/' -- just handle_md
    ```
    I may have missed it but I couldn't find this change to be documented in the README or mentioned in the release notes.

2. I would expect watchexec to exit early in such scenario, rather than keep running.

**Comment by passcod** [comment]
This has been fixed already, please update

**Comment by passcod** [comment]
In 1.8.3

**Comment by ngirard** [comment]
Indeed, that's nice !

Apparently I cannot close this issue myself, please do so whenever you want.
