### ISSUE TITLE
Modified file appears 3 times in WATCHEXEC_WRITTEN_PATH, cannot debounce

### ISSUE THREAD

**Issue by ngirard** [watchexec/watchexec#253]
Using Watchexec 1.15.1, then 1.18.4 on Ubuntu 21.10.

The following invocation used to work flawlessly using v1.15.1 when a markdown file was modified:
```sh
watchexec -p -w ~/Obsidian -e md -i './at/' "just handle_md"
```

Now, using v1.18.4, when `f.md` is modified, `WATCHEXEC_WRITTEN_PATH` contains `f.md:f.md:f.md`.
I've tried using `--debounce`, with a value ranging from 50 to 1000, to no avail.

**Comment by passcod** [comment]
Mm, yes, I suppose the file paths could get deduped. The "issue" here is likely that the file does indeed get three events that get classified as a write (see `--print-events` output).

You're still getting one command run, that's what debouncing is about.

**Comment by ngirard** [comment]
> The "issue" here is likely that the file does indeed get three events that get classified as a write (see `--print-events` output).

Indeed:
```
[EVENT 0] Event source=Filesystem kind=Modify(Data(Any)) path=/path/to/f.md filetype=file
[EVENT 1] Event source=Filesystem kind=Modify(Data(Any)) path=/path/to/f.md filetype=file
[EVENT 2] Event source=Filesystem kind=Access(Close(Write)) path=/path/to/f.md filetype=file
```

Is there anything I can do on my side, besides the `--debounce` option ?

**Comment by passcod** [comment]
Well, you dedupe the variable yourself, I suppose. I'm unfamiliar with `just` and how it's using this such that it's causing issue

**Comment by ngirard** [comment]
(FWIW, I just added 1 char to a 501 char file)

**Comment by ngirard** [comment]
> I'm unfamiliar with `just` and how it's using this such that it's causing issue

[`just`](https://github.com/casey/just) executes any kind of script you want[](url). Here I'm executing a bash script.

**Comment by passcod** [comment]
(That doesn't really matter, it's more about how the program that edited the file behaves. Watchexec doesn't know about file content.)

**Comment by ngirard** [comment]
(sure !)

**Comment by ngirard** [comment]
I can confirm that v0.15.1 returns only one value in `WATCHEXEC_WRITTEN_PATH`.

Would it help if I tried using other versions inbetween ?

**Comment by passcod** [comment]
No, that's fine, I know when it happened (1.18.0) and why the behaviour changed internally.

**Comment by ngirard** [comment]
Alright ! Thanks for your time and your support !

**Comment by passcod** [comment]
Will be in the next release (1.18.6), which I'll finish ~this week.

**Comment by ngirard** [comment]
Great, thanks !

**Comment by passcod** [comment]
Released now.
