### ISSUE TITLE
Regression: .git is no longer ignored in subdirectories

### ISSUE THREAD

**Issue by aaronjensen** [watchexec/watchexec#255]
- Watchexec's version: 1.18.5
- The OS you're using: macOS monterey
- A log with `-vvv` (if it has sensitive info you can email it at felix@passcod.name — do that _after_ filing so you can reference the issue ID): will email
- A sample command that you've run that  has the issue

```
watchexec -p -vvv --  'echo test'
```

After upgrading `1.17.1 -> 1.18.5` watchexec no longer ignores `.git` directories in subdirectories. For example, if I watch a directory that contains several directories that are git repos it will track changes to `.git/index.lock`. This is a problem for https://github.com/raxod502/straight.el which does exactly that.

**Comment by aaronjensen** [comment]
Possibly related, `WATCHEXEC_IGNORE_FILES` does not work to ignore `**/.git/**/*`, and neither does `~/.config/watchexec/ignore`, but `.ignore` does.

**Comment by passcod** [comment]
> Possibly related, WATCHEXEC_IGNORE_FILES does not work to ignore **/.git/**/*, and neither does ~/.config/watchexec/ignore, but .ignore does.

1. How did you set `WATCHEXEC_IGNORE_FILES`? (I can't see it pick up anything in the log, but I can see it try to load an empty path... which is odd)
2. Do you have `XDG_CONFIG_HOME` set? If not, `~/.config/watchexec/ignore` won't be looked at.

---

Right, the `.git` etc ignores by default are `/.git`, which is too strict. I'll relax that. As a workaround, you can use `.git` in your ignores: that will match `/path/to/.git`, which `**/.git/**/*` won't (it will only match `/path/to/.git/file`).

This may also be related to #250.

**Comment by aaronjensen** [comment]
1. By setting an env var and exporting it

<img width="945" alt="CleanShot 2022-02-06 at 19 06 01@2x" src="https://user-images.githubusercontent.com/8588/152707467-0b70bbb1-af4f-42b2-88a3-5b8abb134c6d.png">


2. I didn't, but setting it does not change the behavior, at least on macOS.

<img width="951" alt="CleanShot 2022-02-06 at 19 03 52@2x" src="https://user-images.githubusercontent.com/8588/152707399-4404bd1b-fbf2-4536-bbfe-48e72d2fe6a6.png">

**Comment by passcod** [comment]
`WATCHEXEC_IGNORE_FILES` should contain _paths to files_ that contain ignores. Not actual ignores.

From the release notes:

> any files listed in the new `WATCHEXEC_IGNORE_FILES` environment variable (format is as for the system `PATH` variable)

And the man page:

> `$WATCHEXEC_IGNORE_FILES`: a list of paths to additional ignore files to be loaded.

**Comment by passcod** [comment]
Ah, I'm getting confused. The default ignore will be `**/.git/**`, which should work, but the issue is something else:

Also from the release notes:

> contextual ignores: git ignores won't be loaded for a Mercurial project, for example.

So, the default `**/.git/**` ignore won't be inserted if a Git project isn't detected, and your working directory isn't. Subdirectories aren't considered (should they be? perhaps).

I'll look further as to why `.git` in `~/.config/watchexec/ignore` doesn't work.

**Comment by aaronjensen** [comment]
Ah, my mistake. In any case, that doesn't work for me either...

<img width="953" alt="CleanShot 2022-02-06 at 19 14 17@2x" src="https://user-images.githubusercontent.com/8588/152707764-e7a2ed3d-aa42-4995-aef8-c801a123ca10.png">
<img width="951" alt="CleanShot 2022-02-06 at 19 37 38@2x" src="https://user-images.githubusercontent.com/8588/152708731-5b8d5202-4d3d-4caf-b41c-f3b3fe11f11a.png">

**Comment by passcod** [comment]
Ah, I've found the issue. There's a bug where if no project type is detected, it won't load global ignores! 👿 Obviously not intended. Look for a bugfix release shortly :)

**Comment by passcod** [comment]
Released in 1.18.6.

**Comment by aaronjensen** [comment]
@passcod great, thank you.
