### ISSUE TITLE
Setting environment variables in the child process

### ISSUE THREAD

**Issue by calavera** [watchexec/watchexec#263]
**Is your feature request related to a problem? Please describe.**

I'd like to use the library embedded into a project, but I need to set several environment variables in the child process. I cannot find a way to set them.

**Describe the solution you'd like**

The InitConfig, or RuntimeConfig, could have an option to set environment variables that get propagated to the child process.

**Describe alternatives you've considered**

The only alternative that I can find is to shell out to the watchexec command and set the variables into that process. I'd like to avoid installing the cli if possible.

_If proposing a new CLI option, option names you think would fit._

The cli doesn't really need an option since the variables will be inherited from the parent process, but if you want, using something like a list of `--env` flags, like docker does, could work: `watchexec --env FOO=BAR --env BAZ=QUX ...`

**Comment by passcod** [comment]
This is done with the pre spawn handler, which gives you mutable access to the Command that's about to be spawned, including setting environment variables:

```rust
config.on_pre_spawn(move |prespawn: PreSpawn| async move {
    if let Some(mut command) = prespawn.command().await {
        command.env("FOO", "BAR");
    }

    Ok::<(), Infallible>(())
});
```
