### ISSUE TITLE
Native fs watcher error with 1.18.8

### ISSUE THREAD

**Issue by evanleck** [watchexec/watchexec#268]
**What used to happen**

Watching a directory of files worked.

**What happens now**

Watching a directory of files does not work i.e. updates to files within that directory do not trigger anything.

**Details**

- Latest version that worked: 1.18.7 i.e. prior to 1.18.8
- OS: macOS
- A debug log with `-vvv`: https://gist.github.com/evanleck/30b5c75d4309e364949682d4d3ec7cc2

A relevant section:

```
2022-03-16T21:10:26.971639Z ERROR watchexec::fs: notify watch() error err=Error { kind: Generic("Too many open files (os error 24) about [\"/Users/evan/Code/oft/prepaid-web/app/assets/scripts/lib/events.js\"]"), paths: [] }
2022-03-16T21:10:26.971669Z ERROR watchexec::watchexec: runtime error err=Native fs watcher error
[[Error (not fatal)]]
Native fs watcher error
```

This happens when running `watchexec -w app/assets "make build -q || make build"` where the app/assets directory has, according to Finder, 331 items in it. The error below is what I see without `-vvv` but `make build` only gets triggered once on start up and never again.

```
[[Error (not fatal)]]
Native fs watcher error
```

**Comment by passcod** [comment]
Hmm, okay, I'll revert back to fsevents on mac until #245 is in.

**Comment by passcod** [comment]
Out in 1.18.9
