### ISSUE TITLE
Watchexec fails when directory has no project origin.

### ISSUE THREAD

**Issue by kosayoda** [watchexec/watchexec#271]
Version: watchexec 1.18.10
Kernel: Linux 5.16.16-zen1-1-zen

![image](https://user-images.githubusercontent.com/41782385/160300677-fc992fdc-7983-4842-8a36-84a1192bbe6b.png)

Fairly certain the culprit is d38428f297c. Previously, the current directory is used when the project origin is not found, now it just fails.

**Comment by passcod** [comment]
Aha, well I shot myself in the foot with that error message huh

**Comment by passcod** [comment]
Released in 1.18.11, let me know if that works for you!
