### ISSUE TITLE
How do I filter my folders properly?

### ISSUE THREAD

**Issue by Vzz1c** [watchexec/watchexec#272]
watchexec -i "target/**" make test
=======================
This command means to monitor the current folder for changes and execute the command. Why does the new file in the [target] folder trigger an event when the filter has been set? I'm missing something, I can't find the document

**Comment by passcod** [comment]
It may be a bug. Are you able to provide a `-vvv` log, like the bug template asks you for?

**Comment by Vzz1c** [comment]
> It may be a bug. Are you able to provide a `-vvv` log, like the bug template asks you for?
Maybe it's a translation problem, I mean only filtering the changes in the [target] folder, but creating a new file in the [target] directory will trigger the event

**Comment by Vzz1c** [comment]
I want to monitor the git working directory to add, delete, change and commit, I filtered the [.git] directory, although the [.git] folder is filtered, but the new files or folders that appear in the [.git] directory will still trigger the event, so it will cycle through the events leading to errors, how do I set it up correctly?
