### ISSUE TITLE
Wait for command completion before restarting it

### ISSUE THREAD

**Issue by Yamakaky** [watchexec/watchexec#274]
**Is your feature request related to a problem? Please describe.**
I use `watchexec` with a program that handles unix signals for cleanup. `watchexec -r` doesn't seem to wait for the process to end before starting a new one. The program I run opens a HTTP server, so the new one fails since the port is already taken. Also, if there is a bug during cleanup and my program stays open, it will stay in the background.

Edit: this specific problem seems to be fixed by using `--no-shell`, my bad for not seeing it. However, `watchexec` doesn't wait during its own exit (SIGINT, SIGTERM), so the program stays running after watchexec is stopped.

**Describe the solution you'd like**
`watchexec -r` should wait for the program to end before starting a new one. Optionally, a switch may be added (`--kill-timeout` ?) for the time `watchexec` should wait before sending a `SIGKILL`.

**Additional context**
Test program:
```python
#!/usr/bin/env python3

import signal
import time
import sys

print("start")

def stop(a, b):
    print("signal")
    time.sleep(100)
    sys.exit(0)
    print("stop")

signal.signal(signal.SIGTERM, stop)

while True:
    time.sleep(0.1)
```
Command line:
`watchexec -r 'python3 a.py`

List running processes:
`pgrep -l python3`

`watchexec` is awesome, I use it all the time!

**Comment by passcod** [comment]
This is definitely not what should be happening, especially with the process being spawned and killed in a group. That said, we've seen other problems with python doing this previously.

What `--restart` does:
1. Kills the process group (with SIGKILL)
2. Waits for the process group to exit
3. Spawn a new one

While I acknowledge your feature request of a gentler behaviour that implements "signal + timeout + kill" (similar to service managers on unix), to investigate the underlying issue, could you try with `--no-process-group` and/or `--shell=none` to see if that helps python behave?

**Comment by Yamakaky** [comment]
See my edit for `shell=none` ^^

**Comment by passcod** [comment]
Alright, great :) yeah, there's definitely an issue with python here, I'm not sure why. I think this will coincide with the work on #140 whenever I get to it: more active management of subprocesses and specifically making sure they're tracked down and terminated more effectively. Also may be covered with upcoming (post-2.0) work on a "pty mode" — no issue to track it yet, but is a dependency of #88.

**Comment by Yamakaky** [comment]
Does `watchexec` wait on shutdown? I couldn't find it in the code.

**Comment by matu3ba** [comment]
`doesn't wait during its own exit (SIGINT, SIGTERM), so the program stays running after watchexec is stopped.`

watchexec was not designed to keep track of and kill children processes as that is work for a process supervision tool.
Processes on Unix are terminated once their parent process is terminated by the Kernel.

You can think of it in terms of complexity like 1. process supervision (like what pid 1 does) < 2. repl < 3. programs, if you have separate process groups to prevent influence of signaling between processes.

BTW: I had the very same problem.

**Comment by passcod** [comment]
watchexec may not currently do it, but it's not a deliberate design choice to never do it, it's because it's a complicated task and i only have limited time
