### ISSUE TITLE
Flag for "don't ignore anything"

### ISSUE THREAD

**Issue by max-sixty** [watchexec/watchexec#275]
**Is your feature request related to a problem? Please describe.**

I often want to see what files a process changes, and I run something like this and then run the process:

```
 watchexec --no-vcs-ignore --no-default-ignore --print-events -- echo 1
```

But I realize there are actually 4 separate ignore flags that I should be passing to see every file change:

```
        --no-default-ignore    Skip auto-ignoring of commonly ignored globs
        --no-global-ignore     Skip auto-loading of global or environment-wide ignore files
        --no-project-ignore    Skip auto-loading of project ignore files (.gitignore, .ignore, etc)
        --no-vcs-ignore        Skip auto-loading of VCS (Git, etc) ignore files
```

**Describe the solution you'd like**
What do you think about having `--no-ignore` (or a different name) to not have any ignores?

**Describe alternatives you've considered**

`fd` & `rg` both use `-u` as unrestricted, so passing `-uu` is unrestricted in hidden files _and_ ignores. I'm not sure there's a hierarchy here such that we can progressively add on `u`s, though.

**Comment by passcod** [comment]
The `-u` `-uu` thing is interesting but as you say, probably not applicable here. There's one added complexity for Watchexec in that `--no-ignore` was the previously-used name for `--no-project-ignore`, so it could be a bit confusing to have it "come back" as a different option! But doable, after 2.0.

Good idea! I'll add it to the pile :)

**Comment by passcod** [comment]
As of 1.23.0 this is reduced to 2 flags: the existing `--no-default-ignore`, and the new `--no-discover-ignore`

**Comment by passcod** [comment]
As of next version, there's `--ignore-nothing`. 2.1 will still have `--no-ignore` for naming consistency, which will have `--ignore-nothing` as alias, but at least this is now done.
