### ISSUE TITLE
Why these commands cannot be executed?

### ISSUE THREAD

**Issue by frederikhors** [watchexec/watchexec#282]
**Is your feature request related to a problem? Please describe.**

I'm using [`modd`](https://github.com/cortesi/modd) which allow for commands like:

```
daemon: go build -o main.exe ./cmd/main && ./main.exe
```

I wanna use `watchexec` but with every option I tried I cannot run the second command (`./main.exe`), with or without shell it block on the first one only (`go build`).

Is there a way to accomplish this?

Even if you try the command below the "Hello" never gets printed:

`watchexec --shell=pwsh.exe -- dir && echo "Hello"`

Why?

**Comment by passcod** [comment]
The modd configuration file runs the entire line as the executed command. When you run `something && somethingelse` _on your shell`, though, _your shell_ runs `something && somethingelse`. That is, the only thing watchexec sees is the first bit: `watchexec --shell=pwsh.exe -- dir`.

What you mean to do is wrap the command in quotes so it gets passed to watchexec entirely:

```
watchexec --shell=pwsh.exe -- 'dir && echo "Hello"'
```

or whichever quoting style works best in your shell

**Comment by frederikhors** [comment]
Can I do this without sell, with `--shell=none`?

**Comment by frederikhors** [comment]
Because i need to use the same script on Windows & Linux.

**Comment by frederikhors** [comment]
Using with `shell=none` it doesn't work:

```
[[Error (not fatal)]]
io(spawning process group): The system cannot find the path specified. (os error 3)
```

**Comment by passcod** [comment]
Just don't specify the shell and it will use the default on platform?

**Comment by frederikhors** [comment]
I cannot because on Windows I need to use "pwsh.exe" (PowerShell 7) and not the default "powershell.exe".

**Comment by passcod** [comment]
Well, your script will need to do some switching based on platform. Watchexec doesn't currently support selecting a different shell based on the platform or presence or something like this

**Comment by frederikhors** [comment]
Oh. I think I have not expressed myself well.

I need a way to run two commands, one after the other, using the syntax `command1 && command2` with `--shell=none`.

**Is this possible?**

**Comment by passcod** [comment]
Fundamentally, no. The `&&` syntax requires a shell.

Watchexec could in the future allow to run two separate commands, possibly one after the other has succeeded, but that's pretty far in the future.

It's unlikely even with that capability that Watchexec will _ever_ support parsing a command and splitting it out into multiple commands based on `&&` or other syntax due to the sheer complexity of doing the task properly.

**Comment by passcod** [comment]
What modd does is it implements a very basic shell which does do that parsing, via https://pkg.go.dev/mvdan.cc/sh/v3/syntax

I have not evaluated it for completeness, but in any case it's not that modd supports some kind of shell-less portable syntax, it's that there is a shell.

I suppose if you already have modd deployed you could perhaps use it as a shell _in_ watchexec, but that doesn't feel particularly nice.

**Comment by frederikhors** [comment]
Nope. I wanna remove as much as possible. I think starting a new pwsh.exe only because of this is a pity.

I think you can at least read and split command on '&&' like modd does using shell=none.

But I'm not an expert here and I thank you again.

**Comment by passcod** [comment]
That is incredibly fraught and would only introduce more bugs to the rest of the users; I've explained how modd actually does it, but consider a simple case of splitting on `&&`:

```
watchexec --shell=no-shell-just-magic -- echo "a && b"
```

There are many more examples of edge cases. You need a full shell, whether you provide your own or not.
