### ISSUE TITLE
Add some kind of  separator between each run

### ISSUE THREAD

**Issue by c02y** [watchexec/watchexec#283]
**Is your feature request related to a problem? Please describe.**

I don't want `-c` since it clean all my terminal output history(I'm using tmux if it matters), but the output of all runs are displayed together in the terminal, I couldn't tell when it is restarted easily.

**Describe the solution you'd like**

Is there any kind of separator such as `==============================================` between each run so that I 
know where it is restarted by watchexec? And it is better to display the commands for watchxec before each run.

**Describe alternatives you've considered**

If proposing a new CLI option, option names you think would fit.

**Additional context**
Add any other context about the feature request here.

**Comment by passcod** [comment]
Could be done, certainly, but as workaround you can always add an `echo` to do this yourself

**Comment by passcod** [comment]
You can also pass the `-x` option to a unix shell to get the commands being run, e.g.

```
watchexec --shell='sh -x' -- 'echo ===============; your command'
```

**Comment by c02y** [comment]
Yeah, just try it, it works expected, thanks. I'll close it then.
