### ISSUE TITLE
Lib: Watchexec simply hangs and isn't responsive

### ISSUE THREAD

**Issue by SuperCuber** [watchexec/watchexec#295]
Version: `watchexec = "=2.0.0-pre.14"`
OS: Linux (Ubuntu)

<details>
<summary>Code</summary>

  ```rust
    pub(crate) async fn watch(opt: Options) -> Result<()> {
      let mut init = InitConfig::default();
      init.on_error(PrintDebug(std::io::stderr()));
  
      let mut runtime = RuntimeConfig::default();
      runtime.file_watcher(Watcher::Poll(Duration::from_millis(100))); // the same without this line
  
      let we = Watchexec::new(init, runtime.clone())?;
  
      async {
          println!("starting... (this is printed)");
      }.await;
  
      runtime.on_action(move |action: Action| {
          dbg!(&action);
          async { Ok::<(), Infallible>(()) }
      });
  
      we.main().await.context("run watchexec main loop")??;
      Ok(())
  }
  ```
</details>

Expected: `action` should be printed whenever something changes in the directory
Actual: nothing happens. `ctrl-c` is ignored, and I have to `kill -9` the process to get it to exit.

Not sure what I'm doing wrong here...

**Comment by SuperCuber** [comment]
> So here, you're initialising watchexec, and then you're adding the on_action to your config instance

I simply copied the example code from https://docs.rs/watchexec/2.0.0-pre.14/watchexec/index.html - perhaps it's outdated from how things are done now?

**Comment by passcod** [comment]
Ah, good point, yes, that example code is (and always was, apparently) wrong on that point

**Comment by SuperCuber** [comment]
I'll take this opportunity to also ask, how do you use GlobsetFilterer? The `ignores` argument takes an iterator of `(String, Option<PathBuf>)` with no explanation of what that is... I tried passing `Some(".".into())` and `None` and in both cases it didn't filter out what I wanted.

**Comment by passcod** [comment]
It's `(glob pattern, path the pattern should apply in or None for global)`

**Comment by passcod** [comment]
You can check out the GlobsetFilterer usage in the CLI: https://github.com/watchexec/watchexec/blob/main/cli/src/filterer/globset.rs for more

**Comment by passcod** [comment]
Hmm, that said, it _should_ work as-is, according to [these tests I just added](https://github.com/watchexec/watchexec/pull/299). Check out the logs to see what it's (not) doing?

**Comment by passcod** [comment]
Right, because watchexec's `tracing` doesn't set that feature, it won't emit to `log`. At least for debugging right now, use a [tracing subscriber](https://docs.rs/tracing-subscriber/)

**Comment by SuperCuber** [comment]
FWIW this works as I expect:
```rust
    filter
        .add_filters(&[
            Filter {
                in_path: None,
                on: Matcher::Path,
                op: Op::NotGlob,
                pat: Pattern::Glob(format!("{}/", opt.cache_directory.display())),
                negate: false,
            },
            Filter {
                in_path: None,
                on: Matcher::Path,
                op: Op::NotEqual,
                pat: Pattern::Exact(opt.cache_file.to_string_lossy().into()),
                negate: false,
            },
            Filter {
                in_path: None,
                on: Matcher::Path,
                op: Op::NotGlob,
                pat: Pattern::Glob(".git/".into()),
                negate: false,
            },
            Filter {
                in_path: None,
                on: Matcher::Path,
                op: Op::NotEqual,
                pat: Pattern::Exact("DOTTER_SYMLINK_TEST".into()),
                negate: false,
            },
        ])
        .await?;
```

Not sure if `/` will work on windows tho, or if I need MAIN_SEPARATOR

**Comment by passcod** [comment]
Yay for the tagged filterer! `/` will work fine.

**Comment by SuperCuber** [comment]
> Yay for the tagged filterer! `/` will work fine.

Tested it, `Pattern::Exact` did not work with `.to_string_lossy()`'s formatting that has `/` while `Pattern::Glob` did.

**Comment by passcod** [comment]
Hmm, right. That's annoying, I'll consider that a bug
