### ISSUE TITLE
Don't mask segfault

### ISSUE THREAD

**Issue by Yamakaky** [watchexec/watchexec#36]
```
void main() {
    int *a = 0;
    *a;
}
```
`watchexec 'make t && ./t` don't show that the program segfaults.

**Comment by mattgreen** [comment]
Since I explicitly `fork`/`exec` right now, I think I need to reset the signal disposition immediately before `exec` myself. Will give that a try and report back.

**Comment by Yamakaky** [comment]
Thanks. I lost 30min not understanding why the program I was testing simply stopped in the middle of nowhere XD

**Comment by mattgreen** [comment]
What would you expect to happen? I can think of two different things:

1. `watchexec` halts
2. `watchexec` reports that child process died due to $BAD_SIGNAL

Option 2 seems more ergonomic, though it requires we assemble a list of bad signals.

**Comment by Yamakaky** [comment]
Option 2 for me, 1 would just be annoying.

**Comment by passcod** [comment]
1.18.0 implements this (finally!)
