### ISSUE TITLE
Show the command return value if non-zero

### ISSUE THREAD

**Issue by Yamakaky** [watchexec/watchexec#37]
Maybe with a switch to activate/deactivate.

**Comment by Mange** [comment]
You can wrap your command in a shell and do this yourself instead. ☺️

    watchexec -- bash -c 'your-command || echo "Exited with $?"' 

I'm on mobile, so please excuse my formatting. 

(Note: I am not a contributor on this project.)

**Comment by mattgreen** [comment]
I'm going to lump #36 in with this as well.

I'd prefer if it was opt-in to hold to the Unix tradition of not saying anything unless absolutely necessary, as I expect people will be using it with programs that handle exit codes incorrectly (thus getting spammed with "Program exited with code 3" or whatever) when doing work.

Opt-in makes it harder to realize there's a problem like this, however, so it's not a perfect solution. This is more a UX than a technical issue, so any feedback/ideas are appreciated.

**Comment by passcod** [comment]
That's now (at long last) done.
