### ISSUE TITLE
(documentation) Add examples to demonstrate usage of $WATCHEXEC_ variables

### ISSUE THREAD

**Issue by indigoviolet** [watchexec/watchexec#372]
**Is your feature request related to a problem? Please describe.**
It would be nice to have examples of how to use the `WATCHEXEC_` environment variables in the documentation, since it's a bit tricky with the path delimiter and `WATCHEXEC_COMMON_PATH`. 

**Describe the solution you'd like**
Here are three possibilities, written with `$PATH` because it's already in my environment:

1. Bash/zsh

```shell
(IFS=:; for i in $(echo "$PATH"); do echo $i; done)
```

2. xargs
```shell
echo "$PATH" | xargs --delimiter=: -IARG echo ARG
```

3. GNU Parallel

```shell
parallel --delimiter=: 'echo {}' ::: $PATH
```

Here's a real life usage example with `parallel`:

```shell
watchexec 'parallel --verbose --delimiter : "jupytext -sync $WATCHEXEC_COMMON_PATH/{}" ::: $WATCHEXEC_WRITTEN_PATH'
```

**Comment by passcod** [comment]
These are great! Tbh it's not a feature I use myself, so it's nice to have some actual examples here :)

**Comment by passcod** [comment]
I'm on the path to deprioritise these variables in favour of the new options available via `--emit-events-to` which scale better and are generally less of a pain to use.
