### ISSUE TITLE
Have Ctrl-C kill watchexec when using a long debounce time

### ISSUE THREAD

**Issue by drewkett** [watchexec/watchexec#375]
**Is your feature request related to a problem? Please describe.**
I use `watchexec` as a simple mechanism to autocommit all files in a notes repo. To keep the number of commits down, I use a long debounce time. With a long debounce time, ctrl-c will seemingly always wait the full debounce time to kill `watchexec` even if the underlying command isn't running and no files have changed.

**Describe the solution you'd like**
It would be nice if ctrl-c when the underlying command isn't running anyway would kill `watchexec`.

**Describe alternatives you've considered**
I can't think of any useful alternatives.

**Comment by passcod** [comment]
I guess we could have urgent events (like a ctrl-c) interrupt the debounce loop.

**Comment by calebschoepp** [comment]
+1 I would find this feature very useful.
