### ISSUE TITLE
Windows version detected as virus

### ISSUE THREAD

**Issue by jonasw234** [watchexec/watchexec#378]
Hi,

I’m the maintainer of the [Chocolatey package for watchexec](https://community.chocolatey.org/packages/watchexec).
During the (semi-automated) approval process the package contents are automatically uploaded to VirusTotal for virus checking.
For this version, there were [11/61 detections for watchexec-1.20.5-x86_64-pc-windows-msvc.zip](https://www.virustotal.com/gui/file/1e440070b1fa7528cd333d725e5b7c35d7851746bc3a1a8edf10cc3e4094fe6c/detection/f-1e440070b1fa7528cd333d725e5b7c35d7851746bc3a1a8edf10cc3e4094fe6c-1660161419).
Do you have any idea why there might be so many false positives this time?

- Watchexec's version: 1.20.5 x64
- The OS you're using: Windows

Thank,
Jonas

**Comment by passcod** [comment]
How fun! Nothing actually changed codewise.

**Comment by jonasw234** [comment]
I’ve contacted the AV vendors where I could find the form to report a false positive. Hopefully they’ll update their signatures once they properly analyzed the file. Since it’s mostly generic detections I’m assuming they flagged default parts of a compiled rust binary.

**Comment by jonasw234** [comment]
New detection rate is down to [2/62](https://www.virustotal.com/gui/file/1e440070b1fa7528cd333d725e5b7c35d7851746bc3a1a8edf10cc3e4094fe6c?nocache=1). Hopefully McAfee and VIPRE will update their signatures soon as well.
