### ISSUE TITLE
support shell completions, for example by having `watchexec -e h,cpp -- replcmd`

### ISSUE THREAD

**Issue by matu3ba** [watchexec/watchexec#381]
**Summary**
I have an everyday use case of a bunch of unit tests for which I need tabcompletion, because they have long names.
watchexec with usage of string capture breaks this autocompletion (for me in bash) and requires me to tediously write `watchexec -e h,cpp '` before prompt and `'` after prompt.

**No known reliable (shell) workarounds**
So far, 1. I found no reliable workaround to get the command prompt text to create the necessary new command text and 2. some shells dont even support anything like this via sending broken command to shell window-specific history + reading back as "get prompt text workaround" (one can do Ctrl-c to abort directly after starting).

**Use case**
As of now, to get `watchexec -e h,cpp 'LD_LIBRARY_PATH=./longpathprefix/ otherlongpath/longname_oftestbinary` I
- 1. use neovim command to paste `LD_LIBRARY_PATH=./longpathprefix/ otherlongpath/` to terminal with cursor being at end of prompt
- 2. add the prefix of the testbinary and use tab-completion
- 3. Jump with cursor to start of line to prefix with `watchexec -e h,cpp '` and to end to postfix with `'`.
- 4. press enter

**Background**
As user-friendliest approach I do see `fd`, which uses `fd -e zip -x unzip` and all following arguments are part of the command.
bear changed to `bear -- <your-build-command>`, but I find personally `--` slower to type and less readable.

**Feature**
Inspirated by `fd`, I find `-x` similar to what 7zip uses for proper working expansion not cluttering the workspace usable, because `-e` and `-exts` are already used. Alternatively, `--` as traditional and known separator could be used.

**Additional context**
Of course, it would be better, if we dont need to work around shell shortcomings. 
1. If anyone has a collection of shells for which an automatic workaround that enables tab-completion of the test binary is viable, feel free to post it here.
2. If you ran into the same problem and you found another solution, please post it here.
3. If you know good shell implementations that sidestep the problem and allow querying the command prompt, feel free to post it here.

**Comment by passcod** [comment]
watchexec does support `--`

**Comment by matu3ba** [comment]
Uh, interesting, because the help page does not mention or specify the behavior.

`--` does not run the commands correctly for me or what I would expect on chaining commands:
0. Assume `min.c` with
```c
#include <stdio.h>
int main() {
	printf("hello world1!\n");
}
```
1. Start the repl with `watchexec -e c -- gcc min.c && ./a.out`
2. No output.
3. Changing the string to `printf("hello world2!\n");` neither makes printing work.
4. Repeat as often as wanted.
5. `C-c` (SIGINT) prints the last change (in the simple case of 1 change `hello world2!`.

If I use however `watchexec -e c 'gcc min.c && ./a.out` it works as expected.

What I would expect is that commands after `--` would behave like [python subprocess run](https://docs.python.org/3/library/subprocess.html#subprocess.run) with or without option `shell=True` or some sort of specification of the expected behavior.

So far I dont understand the difference to omitting `--`.

**Comment by passcod** [comment]
That's because

```
watchexec -e c -- gcc min.c && ./a.out
```

is run by your shell as

```
watchexec -e c -- gcc min.c
```

followed by

```
./a.out
```

Watchexec doesn't see the `&& ./a.out`. That's just how shells work.

**Comment by matu3ba** [comment]
True. Closing, because can not be fixed in `watchexec` as shell limitation.

Looks like I need to work around by usíng another shell like fish or zsh (with plugin) instead of bash or build my own tab-completion solution.
