### ISSUE TITLE
Update to Notify 5.pre.16

### ISSUE THREAD

**Issue by Type1J** [watchexec/watchexec#382]
watchexec version 2.0.0
Windows (and Windows WSL2)

This issue in notify: https://github.com/notify-rs/notify/issues/359 causes watchexec to panic when a watched file is removed, then recreated.

The issue can be reproduced by `mv watched_file.txt watched_file.txt.bak && mv watched_file.txt.bak watched_file.txt`.

Please update to the version with the fix in place.

**Comment by passcod** [comment]
Thanks for patching the upstream! I'll get a release with pre.16 going

**Comment by passcod** [comment]
Sorry it took so long! This is released in 1.20.6
