### ISSUE TITLE
Option to ignore files created during command.

### ISSUE THREAD

**Issue by vandenoever** [watchexec/watchexec#40]
Some commands like rustfmt can modify content or mtime of a file and trigger `watchexec` to start a new run.
This can lead to infinite loops. It would be nice to have an option to ignore any file changes during the run.

Alternatively, add an option to look at file content (e.g. via sha1) to detect actual changes in the content.

**Comment by mattgreen** [comment]
I've thought about a few ways to stop infinite loops. I think your way is pretty good, to be honest.

Right now watchexec is not set up to handle it well, however. For 2.0, I'm going to look at restructuring it to use an event-loop style of programming. My hope is I can tag events as they occur with metadata such as the current time and use that to compare whether to act on them.

**Comment by vandenoever** [comment]
Some inspiration: [Fac](http://physics.oregonstate.edu/~roundyd/fac/) uses ptrace to figure out which files are changed when a command is run. In this way it knows when to run again.

**Comment by michalrus** [comment]
But, still, I would like the run to be killed and restarted, but only if the change was triggered by me, and not the autoformatter running as `watchexec`’s child.

**Comment by passcod** [comment]
On Linux, with root permissions, this would actually be partially possible (the kernel interface “fanotify” reports the process ID for some change events). In the rest of the situations, falling back to ptrace first and time checking second could work out nicely.

**Comment by passcod** [comment]
This would be partially resolved by #123

**Comment by passcod** [comment]
Re-reading, I think this is now done (via #123 and now `--on-busy-update=do-nothing`), as per the OP requirement:

> have an option to ignore any file changes during the run

The more technical "ignore things changed by the command we run" is unlikely to happen cross-platform at this point.
