### ISSUE TITLE
[FR] Static build

### ISSUE THREAD

**Issue by rockandska** [watchexec/watchexec#455]
Hi,

Is there any plan to have a static build to avoid this kind of error when not having the right version of glibc ?
```
watchexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by watchexec)
```

Regards

**Comment by rockandska** [comment]
The musl version seems statically linked and seems to work, so only glibc version seems not static

**Comment by passcod** [comment]
Use the musl version if you want a static build, yes
