### ISSUE TITLE
No output is shown if command allocates a TTY

### ISSUE THREAD

**Issue by Mange** [watchexec/watchexec#47]
I'm trying to run a command that wraps `docker-compose`, which in turn allocates a TTY to make the command itself believe that the output is to a terminal, despite it being passed through the Docker container to the outside.

`watchexec` does not show any output if a TTY is involved.

Here's a test case:

```bash
echo foo
# foo
script -qc 'echo foo'
# foo
watchexec -- echo foo
# foo
# ^C
watchexec -- script -qc 'echo foo'
#^C
```

`script -c` runs the given script in a new TTY, so it's a simple way of dealing with this.

---

I also believe this is the cause of other problems I've had in a different project where I couldn't start a debugger in my tests running with `watchexec` as there's no working `stdin` at that point. I think that problem started happening somewhere between 1.4 (working) and 1.6 (not working).
Trying this in different versions of `watchexec` might be useful, if that is related.

**Comment by mattgreen** [comment]
In cases like this, it is useful to look at similar utilities and imitate them. entr, for instance, allocates a TTY at startup to support invocation from text editors. Would this fit your use case?

**Comment by Mange** [comment]
Sorry for not getting back to you sooner. I missed the email. 

I have not tried entr before, but if it supports running "docker-compose run", then it suits my purposes.

If you need help debugging this, I might be able to make a minimal Rust application that showcases this problem and a solution for you, or find the commit that broke this in watchexec.

**Comment by mattgreen** [comment]
That'd be great. I'd be glad to fix this for the next release.

**Comment by mattgreen** [comment]
Tried to replicate this working on 1.4.0 - 1.6.0 and not having luck. What platform are you running on? Based on your usage of `script`, I presume Linux.

**Comment by Mange** [comment]
Yes, I'm on Linux.

Den tor 20 apr. 2017 17:54Matt Green <notifications@github.com> skrev:

**Comment by mattgreen** [comment]
I think I see what the problem is, but I'm not sure how to fix it. We want the child process' newly opened TTY to be hooked to the parent's STDOUT, correct?

**Comment by Mange** [comment]
Yes, but also stdin and stderr for when running an interactive command.

Den tor 20 apr. 2017 18:33Matt Green <notifications@github.com> skrev:

**Comment by Mange** [comment]
A very late follow-up: `entr` works correctly for me, yes.

**Comment by georgecrawford** [comment]
`entr` also works for me

**Comment by Mange** [comment]
I opened up a PR that solves the issue for me: #102. Maybe others want to try it out themselves too!
