### ISSUE TITLE
watchexec library not working properly

### ISSUE THREAD

**Issue by dhruvsol** [watchexec/watchexec#485]
Hey,
I am trying the library to make a cli out of it was checking the demo function mentioned here 
https://github.com/watchexec/watchexec/tree/main/crates/lib/examples 

it checks for the file change in the pathset but as soon as some change happened  the command starts executing an infinity loop

**Comment by dhruvsol** [comment]
some better implementation for the library. that will make life easy to build it

**Comment by passcod** [comment]
Ah, that demo hasn't really been updated for all the stuff in the library. Try with this modification: https://github.com/watchexec/watchexec/pull/486

Nevertheless, it is a decent starting point.

**Comment by dhruvsol** [comment]
Thanks will try that, and is there some discord server or anything where I can ask doubts?

**Comment by passcod** [comment]
No
