### ISSUE TITLE
.gitignore and unix path separator doesn't work on Windows

### ISSUE THREAD

**Issue by apokaliptis** [watchexec/watchexec#487]
I'm trying to use this on a Hugo website project that uses Pagefind for search, which has to run after Hugo, which means I can't use Hugo's built-in test server. When I run `watchexec --print-events -r "yarn run test"`, watchexec seemingly ignores my .gitignore file and continuously rebuilds on changes to Hugo's `public` directory.

```.gitignore
# My .gitignore file.
node_modules/
resources/
public/
.hugo_build.lock

# YARN Modern
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
```

When I add the flag `-i {public,public\\**,resources,resources\\**}` works for ignoring the public, resources and their contents (apparently Hugo or Pagefind triggers a modify event on the public folder itself), however using `/` instead of `\\` for cross-platform compatibility fails to work.

- Watchexec's version: `1.21.0`
- The OS you're using: `Windows 11`
- A sample command that you've run that has the issue: `watchexec --print-events -r 'yarn run test'`

**Comment by passcod** [comment]
Just going to mark this as part of #188.

If you could give a log that would be nice

Also, are you running the command that uses `-i ...` on a windows shell (cmd, powershell) or in a windows bash or similar? If the latter (and _possibly_ in powershell? not sure), can you check it's not an issue with the shell doing expansion before passing the arguments to watchexec?

**Comment by apokaliptis** [comment]
I use PowerShell 7.3.2, but I just tested on CMD and the same thing happens.

I attached a log file below, letting the following command run for about 5 seconds before hitting CTRL-C:
```
watchexec --print-events -r 'yarn run test' -vvv --log-file ../watchexec.log
```
[watchexec.log](https://github.com/watchexec/watchexec/files/10758005/watchexec.log)

---

Here's the same thing with `-i ...` using `/` path separators:
```
watchexec --print-events -r 'yarn run test' -i '{public,public/**,resources,resources/**}' -vvv --log-file ../watchexec.log
```
[watchexec.log](https://github.com/watchexec/watchexec/files/10758188/watchexec.log)

---

And finally, here is a successful result using escaped Windows path separators:
```
watchexec --print-events -r 'yarn run test' -i '{public,public\\**,resources,resources\\**}' -vvv --log-file ../watchexec.log
```
[watchexec.log](https://github.com/watchexec/watchexec/files/10758210/watchexec.log)

Sorry for the late response, but hopefully this is helpful.

**Comment by apokaliptis** [comment]
Both commands are still not working as expected. Also, using `--log-file ../watchexec.log` no longer appears to be working.

**Comment by passcod** [comment]
@apokaliptis can you try again with 1.22.3?

(Also `--log-file=../path` will work, or using `--` to separate the command.)
