### ISSUE TITLE
Update resolved variables placed in command line

### ISSUE THREAD

**Issue by Ktoks** [watchexec/watchexec#488]
**Is your feature request related to a problem? Please describe.**
When running watchexec -w <somefile> <somecommand with a subcommand resolved to a variable "n=$(someothercommand)">
The value in "n" does not update on each run of the command - this causes watch to fail on the 2nd run, because the directories my "somecommand" creates depend on the value in "n" changing when "$(someothercommand)" is run.
I've attempted to add quotes in different ways to ensure the subcommand is run again, instead of keeping the same resolved value.

**Describe the solution you'd like**
I'd like there to be some feature that reruns the entire command- including subcommands.

**Describe alternatives you've considered**
I've considered piping the subcommand in, but in this case- I think that would be complicated.

I would propose naming the option --keep-subcommands or -k.

**Comment by passcod** [comment]
That's not a watchexec issue. That's an issue to how you pass your command in.

For example, this works:
![image](https://user-images.githubusercontent.com/155787/214969699-91097495-0a8f-4478-af0a-d674f49ce804.png)

**Comment by Ktoks** [comment]
I'm passing it in the same way you are:
![image](https://user-images.githubusercontent.com/36412717/214991600-ed3efc86-2b25-48e6-ba84-d6e1683d9b0d.png)
I wonder if it's a difference between x86 musl unknown linux, and the version you're using?

**Comment by Ktoks** [comment]
I tried it with single quotes, double quotes, with parens, without parens, backticks, etc... Nothing seems to work as intended here - It might be a difference between targets, I'm using x86_64-unknown-linux-musl.

**Comment by passcod** [comment]
look, give me an example *with single quotes* that dosen't work, and i'll help you

if you need an explainer of why your screenshot doesn't work, it's because your shell is running the subshell in the string **before even calling watchexec**. there's nothing i can do to "fix" that. that's how shells work.
