### ISSUE TITLE
List of origins with accompanying type

### ISSUE THREAD

**Issue by jayvdb** [watchexec/watchexec#495]
**Is your feature request related to a problem? Please describe.**
I would like to be able to find the path of a specific type of origin. `origins` gives me a list of them, but I dont know what type they are. `types` gives a me a list of types found, but not which path is the root for that type.

**Describe the solution you'd like**
Another function which returns a set of tuple `(path, type)`

**Describe alternatives you've considered**

**Additional context**

**Comment by passcod** [comment]
This is a bit of a misunderstanding of what types() does: it tells you the detected project types _at that one origin path_.

While there could be a function to do as you want, it would only be a more efficient version of:

- for path in origins()
  - if types(path) contains wantedType
     - return path

**Comment by jayvdb** [comment]
fwiw, I found another crate which does what I was looking for, and it was [transferred](https://github.com/jayvdb/lets_find_up/issues/2) to me for maintenance, but I still think this feature request would make `origins` more useful.  That said, if you dont agree, please close this issue, as I am not searching for a solution right now.
