### ISSUE TITLE
git-config needs updated to gix-config

### ISSUE THREAD

**Issue by roblperry** [watchexec/watchexec#503]
- Watchexec's version 2.1.1
- macOS 13.2.1 

Downstream crates using `watchexec` such as `create-rust-app` fail due to a compile-time bug in various `git-config` modules. For example: https://github.com/Wulf/create-rust-app/issues/140.  

This issue does not appear when building `watchexec` unless a `cargo update` is performed, which seems ultimately inevitable. 

I admit that I don't understand why this is a problem for downstream crates, but given that `create update` will need run sooner or later and that https://crates.io/crates/git-config/0.16.2 indicated that `gix-config` should be used, instead of `git-config`, it seems to me that updating `watchexec` to do so should be done as soon as convenient. 

P.S. I have testing my proposed fix via
```
[patch.crates-io]
ignore-files = { path = "{bla...bla...bla}/watchexec/crates/ignore-files" }
```

**Comment by passcod** [comment]
Done with library 2.2.0 and cli 1.22.0.
