### ISSUE TITLE
Error being thrown while stopping long running process

### ISSUE THREAD

**Issue by calebschoepp** [watchexec/watchexec#524]
I'm trying to use the Watchexec library in a Rust project. I'm on MacOS. The command that I'm running is a long running process (won't stop until it is killed). Whenever a user modifies a file I want to stop the process and restart it. I'm using `Outcome::both(Outcome::Stop, Outcome::Start)` to achieve this. The process is properly being stopped and restarted however it keeps throwing the following error:

```
2023-03-09T20:56:08.288961Z ERROR watchexec::command::supervisor: while waiting on process err=io(waiting on process group): blocking waitpid returned pid=0
2023-03-09T20:56:08.289134Z ERROR watchexec::watchexec: runtime error err=io(waiting on process group): blocking waitpid returned pid=0
```

I'm seeing this log because I've configured `init_config.on_error(PrintDebug(std::io::stderr()));`. I should also note that I'm using  grouped commands `runtime_config.command_grouped(true);`.

Does anyone know what would be causing these errors?

**Comment by passcod** [comment]
Yeah, you can see this here: https://github.com/watchexec/watchexec/blob/main/crates/cli/src/config/init.rs#L17-L27

These errors happen but are considered spurious and not significant; iirc they're a result of issuing one too many wait()s where the process group has already gone.

**Comment by calebschoepp** [comment]
I see, thank you.

How can I get these error messages to stop appearing? Both `init_config.on_error(PrintDebug(std::io::sink()));` and `init_config.on_error(());` are not preventing these errors from being logged.

**Comment by passcod** [comment]
These are only quick conveniences, but you can give your own callback and filter off from there, as the CLI does (see link above).

**Comment by passcod** [comment]
I've added examples to the docs for this: https://docs.rs/watchexec/latest/watchexec/error/enum.RuntimeError.html

**Comment by calebschoepp** [comment]
Thanks for the thorough response. All very helpful. Turns out the issue I was facing was that another part of my app was picking up the trace messages with a `tracing_subscriber`. I ended up having to filter out the `watchexec` traces.

```rust
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("watchexec=off".parse()?),
        )
        .with_ansi(std::io::stderr().is_terminal())
        .init();
```
