### ISSUE TITLE
Stops working properly on my Linux system

### ISSUE THREAD

**Issue by unphased** [watchexec/watchexec#525]
Please delete this template text before filing, but you _need_ to include the following:

- Watchexec's version:  1.21.1
- The OS you're using: Ubuntu 20.04
- A log with `-vvv --log-file` (if it has sensitive info you can email it at felix@passcod.name — do that _after_ filing so you can reference the issue ID)

pastebin used because github did not accept size of log. https://pastebin.com/njabGztj

See below for what I did, corresponding to the above output.

- A sample command that you've run that has the issue

`watchexec -w nvim/init.lua -vvv --log-file watchexec.log -- 'echo "====="; env | grep WATCHEXEC'`

Actions:
```sh
touch init.lua
touch init.lua
# ^ to test it working properly. it does. The event I check is WATCHEXEC_WRITTEN_PATH
nvim init.lua
# Save from nvim twice.
```

On the first save from nvim it shows 

```
=====
WATCHEXEC_COMMON_PATH=/home/slu/.vim/nvim
WATCHEXEC_RENAMED_PATH=init.lua
```

On the second save from nvim it shows

```
=====
WATCHEXEC_REMOVED_PATH=init.lua
WATCHEXEC_COMMON_PATH=/home/slu/.vim/nvim
WATCHEXEC_META_CHANGED_PATH=init.lua
```

After this point, no amount of saving from nvim or touching this file from command line cause any further events or logfile input. Seems to be hung. 

When this started occurring i also noticed that alacritty upon starting a new instance reported that it could not watch the config file citing too many open files. I have since then killed various apps that had lots of files open (like Slack had like 1740 files open). I thought this was also due to a really long running tmux server instance, but the behavior is very reproducible here in the same way whether I use tmux or not. Rebuilding watchexec did not change behavior. Though that simply rebuilt and reinstalled 1.21.1 again. I think it is something going on with the state of the operating system... I expect after a reboot the problem will go away. 

Honestly I have never seen inotify based watching systems on Linux be robust. I had high hopes for watchexec but it is starting to feel like being able to reliably watch files on linux for weeks or months is just not in the cards. I will keep trying to use watchexec though. Maybe there are other low level watch methods I could tell watchexec to use?

**Comment by passcod** [comment]
Have you increased your inotify limits? That's probably the source of your troubles

**Comment by passcod** [comment]
You can totally use `--force-poll` to poll the filesystem, but it's probably slower than inotify.

**Comment by passcod** [comment]
Fanotify would in theory be a lot more efficient and scalable but 1) it's not implemented in watchexec, and 2) it would require root, which has obvious security implications.

**Comment by unphased** [comment]
OK I guess I guessed right that it's using inotify instead of epoll by default. I was browsing the strace output and was leaning towards it using epoll but that just shows how little I know.

I grabbed this tool https://github.com/mikesart/inotify-info and it says

```
------------------------------------------------------------------------------
INotify Limits:
  max_queued_events    16384
  max_user_instances   128
  max_user_watches     65536
------------------------------------------------------------------------------
        Pid  App                        Watches   Instances
        7879 xdg-desktop-portal-gtk          91   1
        7636 gsd-xsettings                   85   1
        7590 gvfsd-trash (deleted)           69   1
        6659 systemd (deleted)               67   7
     2333584 dropbox                         55   1
        6801 tracker-miner-fs                29   1
        7700 snap-store                      22   1
     1745769 nautilus                        17   1
       14039 update-notifier                 14   1
        7187 gnome-shell                     12   1
     1727062 chrome                          10   1
      290799 file-roller                      8   1
        7875 xdg-desktop-portal               6   1
      316389 sdkmanager-gui                   4   1
        6823 dbus-daemon                      4   1
     2689467 gnome-screenshot                 3   1
     1727110 chrome                           3   1
     2780479 nvim                             3   1
      316516 sdkmanager-gui                   3   1
     1309924 alacritty                        2   1
      884149 alacritty                        2   1
        7623 gsd-sound                        2   1
     2907961 alacritty                        2   1
     3713609 kwalletd5                        2   2
        6798 pulseaudio                       2   2
        7463 evolution-source-registry        2   1
        7430 ibus-daemon                      2   1
        7434 ibus-dconf                       1   1
        6862 gvfs-afc-volume-monitor (deleted)   1   1
     2836508 watchexec (deleted)              1   1
        6876 goa-daemon                       1   1
        6887 goa-identity-service             1   1
        7145 dbus-daemon                      1   1
        7173 gnome-session-binary             1   1
        7746 ibus-engine-simple               1   1
        7435 ibus-extension-gtk3              1   1
        7437 ibus-x11                         1   1
        7441 ibus-portal                      1   1
        7477 evolution-calendar-factory       1   1
        7501 evolution-addressbook-factory    1   1
        7601 gsd-color                        1   1
        7605 gsd-housekeeping                 1   1
------------------------------------------------------------------------------
Total inotify Watches:   536
Total inotify Instances: 50
------------------------------------------------------------------------------
```
right now which is not enough to reach any of my system limits.

**Comment by unphased** [comment]
I ran `kill -9 2836508` but it did not change behavior from what was described above. I'm fairly sure if i reboot the system this will not be reproducible so I'm hoping to gather some ideas on what else I can probe to try to find a root cause. Let me see if I can make it work again by switching to epoll though.

**Comment by passcod** [comment]
epoll is for watching file descriptors which would... make a very poor filesystem watcher

**Comment by unphased** [comment]
On my macOS system this is how it reports saving the file from neovim.

```
=====
WATCHEXEC_CREATED_PATH=init.lua
WATCHEXEC_WRITTEN_PATH=init.lua
WATCHEXEC_COMMON_PATH=/Users/slu/.vim/nvim
WATCHEXEC_META_CHANGED_PATH=init.lua
WATCHEXEC_RENAMED_PATH=init.lua
```

But I already know to expect completely different reported events across these different operating systems.

**Comment by unphased** [comment]
> epoll is for watching file descriptors (like sockets) which would... make a very poor filesystem watcher. epoll is used to watch the inotify file descriptor internally, but it's not really the same class of api

Thanks for clarifying. that was helpful!

**Comment by unphased** [comment]
Thanks! No idea why this worked well earlier and then it didn't, but I can't even rule out right now whether i neglected to test linux at all prior to this... ok, so it worked after I changed the command to watch this dir for lua file extension changes. That works well for this use case and I will figure out the path filtering stuff later. 

I take it perhaps the reason it behaves like this is maybe that it's going to be looking at the old file and nvim will be doing the usual renaming old file and creating the saved file as a new file so that's why (and possibly not a bug) that events don't get picked up at all afterward.
