### ISSUE TITLE
`--restart` in 1.22.0 no longer terminates and restart child process correctly

### ISSUE THREAD

**Issue by luislavena** [watchexec/watchexec#544]
**What used to happen**

Previous versions (1.21.1) correctly terminates and restart a child process on first events received while 1.22.0 does not.

**What happens now**

It randomly terminates the child process and requires multiple events being triggered (Eg. by using `touch`) for the child process to be restarted.

**Details**
- Latest version that worked: 1.21.1
- Earliest version that doesn't: 1.22.0
- OS:
- A debug log with `-vvv --log-file`: [watchexec.2023-03-20T19-25-01Z.log](https://github.com/watchexec/watchexec/files/11022305/watchexec.2023-03-20T19-25-01Z.log)

Script used to reproduce:

```bash
#!/usr/bin/env sh

counter=0

while true
do
	echo "Loop number:" $((++counter))
	sleep 5
done
```

Thank you!
❤️ ❤️ ❤️

**Comment by passcod** [comment]
Ah, I see the issue. This is known but I don't remember which existing bug it is; a workaround I think is to set --stop-timeout to something very short like 50ms

**Comment by passcod** [comment]
Will be fixed in 1.22.1

**Comment by passcod** [comment]
1.22.1 should have fixed it, can you provide a log @kutu ?

**Comment by kutu** [comment]
[watchexec.2023-03-22T08-54-52Z.log](https://github.com/watchexec/watchexec/files/11038129/watchexec.2023-03-22T08-54-52Z.log)

started watchexec
`watchexec --log-file -vvv -r -w gulpfile.coffee npm -- run gulp -- watch`
i saved gulpfile.coffee file
waited 60 seconds
watchexec restarted
and i pressed ctrl+c

**Comment by kutu** [comment]
it works with
`--stop-timeout 0`
or with
`--stop-signal kill`
