### ISSUE TITLE
Watching from a different drive doesn't filter correctly

### ISSUE THREAD

**Issue by regystro** [watchexec/watchexec#546]
Hi.

Running on Windows 10 64bit 22H2
Version: watchexec 1.22.0 (645d87d 2023-03-18)

- Sample command: `E:\_temp\watchexec>watchexec -vvv --log-file --workdir "E:\hugo" echo "meh"`

watchexec bypasses --workdir and uses the current CWD: `E:\_temp\watchexec` instead of `E:\hugo`

Changes to `E:\hugo` are not monitored, but to `E:\_temp\watchexec` instead. See `new_file.txt` in the log.

The path passed to --workdir was also tested without double quotes, and all possible single and double slash and backslash combinations. Also tried with --project-origin "E:\hugo" to enforce, but same result.

[watchexec.2023-03-21T15-31-00Z.log](https://github.com/watchexec/watchexec/files/11030133/watchexec.2023-03-21T15-31-00Z.log)

**Comment by passcod** [comment]
not a bug. workdir sets the workdir **of the command** not of watchexec itself. change the workdir of your calling process or shell if that's what you want

**Comment by regystro** [comment]
OK, then I must be facing https://github.com/watchexec/watchexec/issues/250 or https://github.com/watchexec/watchexec/issues/487.

What I'm trying to accomplish is to call watchexec to watch a specific directory and honor the .gitignore file in a subfolder.
So far I haven't been able to do it. Based on this folder structure:

```
E:
|- folder_to_watch
|--- .gitignore
|--- private
|--- public
|----- ...
```

.gitignore contains (whatever combo you can guess, I tried them all) to ignore the "private" subfolder:
```
private
private/
private/*
private/**
...
```
Then calling watchexec from e.g `C:\`
`watchexec --watch "E:\folder_to_watch" echo "meh"`
and copying a file to `E:\folder_to_watch\private` triggers the command.

That's why I though workdir could help me there, but I was wrong.

**Comment by passcod** [comment]
Is there a reason you're not calling watchexec from `E:\`? That would be the easiest

**Comment by regystro** [comment]
> Is there a reason you're not calling watchexec from `E:\`? That would be the easiest. Though your thing should work in principle, yes.

I'm calling it from a batch file that can be in another drive. I use watchexec to watch a folder for new files and trigger a command to send me a message when that happens. I know that's not the usual use, but it suits my needs. I also know I can CWD to the folder_to_watch prior to calling watchexec from the batch file, but like you said, it should work with `--watch` in principle.

> Can you give a new log with the command you're now running?

Here you are. I moved `E:\folder_to_watch` to `E:\_temp\folder_to_watch` to keep out of the log all `E:\` root entries. Result is the same:

[watchexec.2023-03-21T23-25-53Z.log](https://github.com/watchexec/watchexec/files/11034828/watchexec.2023-03-21T23-25-53Z.log)

Commandline: `watchexec -vvv --log-file --watch "E:\_temp\folder_to_watch" echo "meh"`

**Comment by passcod** [comment]
Ah, sorry, can you give a log with `-vvvv`? (one more v, which includes the details of how events get filtered)

**Comment by passcod** [comment]
But also try with the ignore `**\\private\\**\\*`, just to see if it's #487

**Comment by passcod** [comment]
Let me know if 1.22.2 fixes your issue (should be out in ~half an hour)

**Comment by regystro** [comment]
I just tried 1.22.2 but no luck. The .gitignore filters still don't apply. To isolate the problem I ran watchexec from `E:\_temp\folder_to_watch` (the usual way, not from another drive) and these are my findings:

- These two work as expected:
`watchexec.exe -vvv --log-file "." -i "{private,private\\**}" echo "meh"`
`watchexec.exe -vvv --log-file "." --ignore-file ignorelist.txt echo "meh"`
[ignorelist.txt](https://github.com/watchexec/watchexec/files/11044777/ignorelist.txt)
Whatever file event you trigger inside `private` folder is ignored

- This fails (with this [gitignore.txt](https://github.com/watchexec/watchexec/files/11044855/gitignore.txt)):
  -  `watchexec.exe -vvv --log-file "." echo "meh"`
[watchexec.2023-03-22T21-17-39Z.log](https://github.com/watchexec/watchexec/files/11044848/watchexec.2023-03-22T21-17-39Z.log) -> private folder is not ignored

  - `watchexec.exe -vvvv --log-file "." echo "meh"`
[watchexec.2023-03-22T21-21-59Z.log](https://github.com/watchexec/watchexec/files/11044887/watchexec.2023-03-22T21-21-59Z.log) -> private folder not ignored and terminal flooded with "cannot send event from fs watcher: sending into a full channel" errors

So my guess is that the issue is how the subfolder filters in the .gitignore are being parsed/translated. Once you can translate the filters in .gitignore to those used in --ignore-file, it should work.

**Comment by passcod** [comment]
Thanks for your debugging :) My next project for watchexec is to rewrite the gitignore handling anyway, so that will cover that.
