### ISSUE TITLE
How can we watch for scripts that are not named by extension? 

### ISSUE THREAD

**Issue by unphased** [watchexec/watchexec#562]
I have python and shell scripts that are not named with `.py` or `.sh` extensions and the interpreter is specified with a `#!` shebang at the top of the file. `file` can be used to determine that they are executables. I'd like a way similar to `--exts` to tell watchexec to watch these types of files.

**Describe the solution you'd like**
No preference on how it's implemented. So far to work around this i have to watch all files which is not ideal.

**Comment by passcod** [comment]
Ooh, interesting. There's nothing really there for it at the moment; I can see two ways to implement:

1. Gather executable bit information, and filter on that (relatively easy).
2. Do data reading and match on contents (relatively hard).

Both could co-exist, (2) sounds incredibly powerful in particular. I'll have a think!

**Comment by unphased** [comment]
Thanks and I have a very related request, for a common use case, which is I'd like to watch for `git ls-files` files. I don't know if it's supported but I had encountered some strange behavior using the `-w` flag to specify a list of files (it doesn't really work right to watch specific files, because editors do weird things when saving to a file). Ideally we can have a simple way to tell watchexec a list of files (which we can populate e.g. with `git ls-files`) and it will treat this as a whitelist. As an alternative to the ignorefile blacklist behavior.

**Comment by passcod** [comment]
watching individual files is inefficient anyway, so if a filelist is done it would resolve directories and then post-filter on filenames, also covered in #190

could you open a new issue for the filelist feature so i can track those separately thx

**Comment by unphased** [comment]
Oh good, that makes it something I can implement in a wrapper for the time being. I’ll bring it up as a separate issue later, thanks!

**Comment by passcod** [comment]
See #571 for a new kind of filter that can handle these kinds of situations.

**Comment by passcod** [comment]
#571 has landed, which lets you implement this kind of filter.
