### ISSUE TITLE
Need more instructions on using json-stdin

### ISSUE THREAD

**Issue by wll8** [watchexec/watchexec#567]
**Is your feature request related to a problem? Please describe.**
Need more instructions on using json-stdin

**Describe the solution you'd like**
The content obtained by json-stdin is deterministic and predictable.

**Additional context**
- watchexec 1.22.2
- win10 x64

``` js
[
  { kind: 'source', source: 'filesystem' },
  { kind: 'fs', simple: 'modify', full: 'Modify(Any)' },
  {
    kind: 'path',
    absolute: 'D:\\git2\\watchexec-bin\\lib\\win32\\x64\\info.json',
    filetype: 'file'
  }
]
```

I am using nodejs to call watchexec .

When using the json-stdin parameter, is the order of the tags data in the returned json fixed? For example, the first item is the source, the second item is the event, and the third item is the file?

Is there any exact way for me to handle the outputted json data?

This is the document I refer to: https://man.archlinux.org/man/community/watchexec/watchexec.1.en#emit

I tried the environment variable way, but it was in danger of being truncated. I tried using json-file, it has no effect. How can I conveniently use the command line to get changed files?

**Comment by passcod** [comment]
The JSON content _is_ deterministic, and has a schema as described, but doesn't guarantee order or number (as that's not meaningful). Filter/map on the `kind` field. Something like this maybe:

```js
const changedPaths = event.tags.map(tag => tag.kind === 'path' && tag.absolute).filter(Boolean)
```

**Comment by passcod** [comment]
Can you clarify by "json-file has no effect"?

```
$ watchexec --emit-events-to=json-file 'node -e \'require("fs")
   .readFileSync(process.env.WATCHEXEC_EVENTS_FILE, "utf-8")
   .split("\n")
   .filter(line => line.trim().length)
   .map(line => JSON.parse(line))
   .forEach(event => console.log(event))\''

{
  tags: [
    { kind: 'source', source: 'filesystem' },
    { kind: 'fs', simple: 'modify', full: 'Modify(Metadata(Any))' },
    {
      kind: 'path',
      absolute: '/home/code/js/tamanu/README.md',
      filetype: 'file'
    }
  ]
}
```

**Comment by passcod** [comment]
If you want an easier way, probably just use the `stdin` variant:

```
$ watchexec --emit-events-to=stdin cat

modify:/home/code/js/tamanu/README.md
```

**Comment by wll8** [comment]
> process.env.WATCHEXEC_EVENTS_FILE

Looks like I was using it the wrong way before. I thought WATCHEXEC_EVENTS_FILE was for setting the file location. Thanks to your example, I realize it's for getting the file location.

**Comment by wll8** [comment]
> The JSON content _is_ deterministic, and has a schema as described, but doesn't guarantee order or number (as that's not meaningful). Filter/map on the `kind` field. Something like this maybe:
> 
> ```js
> const changedPaths = event.tags.map(tag => tag.kind === 'path' && tag.absolute).filter(Boolean)
> ```

If the order and number of tags are indeterminate, how do I know what files changed in what way?

So this is a wrong way of handling json: [watchexecEvent.js#L24](https://github.com/wll8/watchexec-bin/blob/567afdf3eeb97fceca78570e15c8cd20e8103750/watchexecEvent.js#L24)

``` js
function handleJsonStr(str) {
  let list = []
  try {
    const json = JSON.parse(`[${str.split(`\n`).join(`,`)}]`)
    const map = {}
    json.forEach(({tags = []}) => {
      const [, {simple, full} = {}, {absolute, filetype} = {}] = tags
      const data = {
        full,
        simple,
        absolute,
        filetype,
      }
      const key = JSON.stringify(data)
      if(map[key] !== true && absolute) {
        list.push(data)
      }
      map[key] = true
    })
  } catch (error) {
    // ...
  }
  if(list.length) {
    return list
  }
}
```

**Comment by wll8** [comment]
For the `environment` method, there is a phenomenon:
- create file 1
- Change name 1 to 2
- Change name 2 to 1

The resulting sequence of events is this:
``` js
{
  COMMON_PATH: 'D:\\git2\\watchexec-bin',
  CREATED_PATH: '1',
  type: 'created'
}
{
  COMMON_PATH: 'D:\\git2\\watchexec-bin',
  RENAMED_PATH: '1;2',
  type: 'renamed'
}
{
  COMMON_PATH: 'D:\\git2\\watchexec-bin',
  RENAMED_PATH: '1;2',
  type: 'renamed'
}
```

Strangely, the RENAMED_PATH of the two renames are the same! Is this a bug? Will it be fixed?

**Comment by wll8** [comment]
If using `stdin`, the event list is as follows:

``` txt
D:\git2\watchexec-bin>watchexec --emit-events-to=stdin findstr .
[[Command exited with 1]]
create:D:\git2\watchexec-bin\1
modify:D:\git2\watchexec-bin\1
modify:D:\git2\watchexec-bin\2
modify:D:\git2\watchexec-bin\2
modify:D:\git2\watchexec-bin\1
```

There is no renamed , and there is no who renamed who.

It seems that the output results of several ways of --emit-events-to are completely different. 😭😭😭

**Comment by passcod** [comment]
This is explained in the help:

> One thing to take care with is assuming inherent behaviour where there is only chance. Notably, it could appear as if the `RENAMED` variable contains both the original and the new path being renamed. In previous versions, it would even appear on some platforms as if the original always came before the new. However, none of this was true. It's impossible to reliably and portably know which changed path is the old or new, "half" renames may appear (only the original, only the new), "unknown" renames may appear (change was a rename, but whether it was the old or new isn't known), rename events might split across two debouncing boundaries, and so on.

In general, this is just not information that we can obtain reliably. You should _not_ assign any meaning to the order of events or the order of paths or tags. What you can assign meaning to is that tags (eg file events and paths) within a same event will be about the same underlying filesystem action.

**Comment by wll8** [comment]
Thanks for your patience and help.

So when renaming, you can't always get the path before and after modification accurately.

This library provides a method, don't know if it will work properly across platforms.
https://github.com/shama/gaze#events

**Comment by passcod** [comment]
All that does is use Node's implementation, and [look](https://nodejs.org/dist/latest-v19.x/docs/api/fs.html#fswatchfilefilename-options-listener) at what's specifically called out in the Node documentation:

> When a file being watched by fs.watchFile() disappears and reappears, then the contents of previous in the second callback event (the file's reappearance) will be the same as the contents of previous in the first callback event (its disappearance).
>
> This happens when:
>
> - the file is deleted, followed by a restore
> - the file is renamed and then renamed a second time back to its original name

What some libraries do is _guess_. Most of the time they're right. Sometimes they're very wrong. I chose to _not_ guess.

**Comment by passcod** [comment]
That said some platforms do provide some of that information; in those cases that will be called out in the `full` field, something like `Modify(Rename(From))` and `Modify(Rename(To))`.

**Comment by wll8** [comment]
This answer is brilliant. 

last question. When I create (or copy) a large file, the create/modify event is triggered immediately, and the file is not created yet. Is there any way to make the event be fired after the file operation is over? This can be very useful.

**Comment by passcod** [comment]
Not yet, but in future you'll be able to watch for file close events

**Comment by wll8** [comment]
Well, looking forward to watchexec getting better and better, it's good to see it's being actively updated.

Finally a little suggestion
- Even if I use a program that supports markdown (such as vscode) to open the md document of watchexec, there still seems to be some problems in the display

Thanks again for your patient help, wonderful answer.
