### ISSUE TITLE
Nested .gitignore breaks all ignores

### ISSUE THREAD

**Issue by Cammisuli** [watchexec/watchexec#578]
When using `watchexec` on a workspace that has folders with `.gitignore` files that contain `*` (which basically tells git to ignore this whole folder), it completely breaks ignores for the rest of the workspace. 

You can clone this repro repo to see it in action:
https://github.com/Cammisuli/watch-exec-repro

Steps to reproduce:
1) clone repo
1) Open in vscode with rust analyzer (this just enables that files in the `target/` directory is automatically changed)
1) run `watchexec --project-origin=.  -- echo '$WATCHEXEC_WRITTEN_PATH'`
1) change `src/main.rs` (add a comment or whatever)
1) See output
	* the expected output should be just `main.rs`, but we get everything in `target/` as well.

1) Stop the `watchexec` command
1) Delete `this-should-ignore-children/.gitignore` (or change the glob to something else)
1) run `watchexec --project-origin=.  -- echo '$WATCHEXEC_WRITTEN_PATH'`
1) change `src/main.rs`
1) Output is only `src/main.rs` 

- Watchexec's version
 ```watchexec --version
watchexec 1.22.2 (2023-03-22) 
build-date: 2023-03-22
release: 1.22.2
features: 
```
- The OS you're using
```
macOS 13.3.1 (22E261)
```
- A log with `-vvvv --log-file` 
[watchexec.2023-05-02T18-19-42Z.log](https://github.com/watchexec/watchexec/files/11376435/watchexec.2023-05-02T18-19-42Z.log)

I'll try and investigate this myself and post any findings.

**Comment by Cammisuli** [comment]
It looks like the `GitIgnoreBuilder` (https://github.com/watchexec/watchexec/blob/bccc0292a0f15ae508e926b0320667d08f823d6a/crates/filterer/globset/src/lib.rs#L61-L61) needs to be created for each ignore file.

Probably something needs to be done here instead:
https://github.com/watchexec/watchexec/blob/bccc0292a0f15ae508e926b0320667d08f823d6a/crates/ignore-files/src/filter.rs#L78-L78

**Comment by passcod** [comment]
Yep, this (bug and reason for it) is known, and the [next priority](https://cohost.org/passcod/post/1201832-watchexec-1-22-0-and). However, I don't have time at the moment to work on it.

**Comment by Cammisuli** [comment]
I don't mind working on this if you don't have time. 

If you have notes you want to share, or other pointers, I can begin fixing this.

**Comment by passcod** [comment]
Ultimately I want to replace all ignore handling, but a good start is probably to fix this particular issue, which is to use `ignore` properly, that is to make a gitignore instance per ignore file, and rewrite the ignore-files crate to handle both the building of that structure and the querying upon filtering. Likely a trie would be the ideal way to go but a vec or standard tree would probably work to start.

(My current understanding is that a gitignorebuilder is for a single directory; I believe that if two files apply to a single directory they can be handled by one builder. However that might be too much complexity for too little gain.)
