### ISSUE TITLE
Fine grained information about what is updated

### ISSUE THREAD

**Issue by netheril96** [watchexec/watchexec#59]
> Processes  started  by  watchexec  have  the $WATCHEXEC_UPDATED_PATH environment variable set to the path of the first modification observed. In addition, the $WATCHEXEC_COM-
       MON_PATH environment variable is set to the common path of all observed modifications.

This is not enough for some of my applications. I want to have more information. A possible implementation may have:

* $WATCHEXEC_BASE_DIR: The base dir from which the following paths are relative to
* $WATCHEXEC_ADDED_PATH: A list of paths added during the watch, separated by system specific path separator (":" or ";")
* $WATCHEXEC_REMOVED_PATH
* $WATCHEXEC_CONTENT_CHANGED_PATH
* $WATCHEXEC_META_CHANGED_PATH

**Comment by mattgreen** [comment]
Pretty good ideas here. I'm a bit busy with other projects so I'll mark this as help wanted and we'll see if someone bites.

**Comment by passcod** [comment]
This was probably resolved when the PR was merged, actually.
