### ISSUE TITLE
How to correctly use `Watchexec::main()`?

### ISSUE THREAD

**Issue by emilHof** [watchexec/watchexec#603]
Hey Félix, sorry to be bothering you so soon again hehe!

After your help with the new `lib3.0.0` feature of having multiple `Command`s under a single `Watchexec`, i have been trying to make use of this!

Now, it seems like I am running into a strange issue, which i do not believe is a bug, but rather a misuse/misunderstanding of `Watchexec::main()` on my end!

Concerning this function:

```rust
async fn start_scheduler(
    subsys: SubsystemHandle,
    state: RuntimeState,
    cargo_options: CargoOptions,
    watcher_config: WatcherConfig,
    mut req_rx: Receiver<InvokeRequest>,
) {
    let (function_tx, function_rx) = mpsc::channel::<FunctionData>(10);
    let function_rx = Arc::new(Mutex::new(function_rx));

    let wx = crate::watcher::new(watcher_config.clone(), state.ext_cache.clone(), function_rx)
        .await
        .expect("watcher to start");

    let wx_handle = wx.main();
    tokio::pin!(wx_handle);

    loop {
        tokio::select! {
            Some(req) = req_rx.recv() => {
                if let Some((name, api)) = state.req_cache.upsert(req).await {
                    if !watcher_config.only_lambda_apis {
                        info!(function = name, "starting new lambda");
                        let function_data = function_data(name, api, cargo_options.clone());
                        _ = function_tx.send(function_data).await;
                        _ = wx.send_event(Event::default(), watchexec::event::Priority::Urgent).await;
                    }
                }
            },
            _ = &mut wx_handle => {
                info!("watcher main finished");
            },
            _ = subsys.on_shutdown_requested() => {
                info!("terminating lambda scheduler");
                return;
            },

        };
    }
}
```
Essentially, it creates a `Watchexec` with some config and a `function_rx` that receives new `Command`s to spawn. A `tokio::select!` loop then waits for new `functions` to be received, which are then forwarded to the `Watchexec` to be spawned as new `Command`s, or `main()` to finish, or for a `shutdown_request`.

Now, since `Watchexec::main()` can only be called once without `panic`, the `select!` loop only gets a pinned reference to the `JoinHandle` of `Watchexec::main()`. 

What is odd about this, is that it does not seem to be working properly, and i am unsure of why...

In turn, if a new `Watchexec` were to be spawned for every function within it's own `Subsystem`, it does work and the new `Command` is spawned by the new `Watchexec`...

```rust
async fn start_scheduler(
    subsys: SubsystemHandle,
    state: RuntimeState,
    cargo_options: CargoOptions,
    watcher_config: WatcherConfig,
    mut req_rx: Receiver<InvokeRequest>,
) {
    loop {
        tokio::select! {
            Some(req) = req_rx.recv() => {
                if let Some((name, api)) = state.req_cache.upsert(req).await {
                    if !watcher_config.only_lambda_apis {
                        info!(function = name, "starting new lambda");
                        {
                            let function_data = function_data(name, api, cargo_options.clone());
                            let (function_tx, function_rx) = mpsc::channel::<FunctionData>(10);
                            let function_rx = Arc::new(Mutex::new(function_rx));
                            let wx = crate::watcher::new(watcher_config.clone(), state.ext_cache.clone(), function_rx)
                                .await
                                .expect("watcher to start");
                            _ = function_tx.send(function_data).await;
                            _ = wx.send_event(Event::default(), watchexec::event::Priority::Urgent).await;

                            subsys.start("lambda runtime", move |s| async move {
                                tokio::select! {
                                    _ = wx.main() => {
                                        info!("watcher main finished");
                                    },
                                    _ = s.on_shutdown_requested() => {
                                        info!("terminating watcher");
                                    }
                                }
                                Ok::<(), ServerError>(())
                            });
                        }
                    }
                }
            },
           _ = subsys.on_shutdown_requested() => {
              info!("terminating lambda scheduler");
              return;
            },
        };
    }
}
```

This is quite little context too, so if it would be hard to help with this and pinpoint what is really going wrong here, that is totally understandable haha! There's also a good chance i am doing something wrong somewhere else, so please do not worry if you are unable to say where i am making my mistakes ! :D

**Comment by passcod** [comment]
i'd just drop the watchexec::main handle if you're not doing anything with it. no point keeping it around. i don't think that's your issue, but without seeing the action handler where most of the, well, action happens, can't do much

**Comment by emilHof** [comment]
oh, okie! i was not aware that discarding the handle would really affect anything, that is actually very good to know haha!

also, you were completely right! the issues was apparently using `mpsc::recv()` instead of `mpsc::try_recv()`, as the `action_handler` would get stuck waiting for new messages and thus never actually returning... it is quite embarrassing how long i've been stuck on this issues and it turned out just changing this:
```rust
while let Some(function) = function_rx.lock().await.recv().await {
```
to this:
```rust
while let Ok(function) = function_rx.lock().await.try_recv() {
```
completely solved it...

thank you so much for pointing out that the issues is likely in the `action_handler`, you're a frickin genius Félix!! thank youu! :))
