### ISSUE TITLE
Quoted program names are not handled properly for CMD

### ISSUE THREAD

**Issue by m-haug** [watchexec/watchexec#613]
watchexec 1.22.3 does not handle cmd quoting properly on Windows.

This came up when investigating https://github.com/tectonic-typesetting/tectonic/issues/1003. See there for the actual command that caused the issue. However, the issue also reproduces with the watchexec binary:

```shell
$ watchexec --version
watchexec 1.22.3 (eb19f83 2023-05-14)                                                                                                         commit-hash: eb19f837612a046d58173efae7e3b0825d475313
commit-date: 2023-05-14
build-date: 2023-05-14
release: 1.22.3
features:
$ watchexec -vvv --log-file --shell cmd -- '"C:\Users\Markus Haug\scoop\apps\tectonic\current\tectonic.exe"' -X build --open
Der Befehl "\"C:\Users\Markus Haug\scoop\apps\tectonic\current\tectonic.exe\"" ist entweder falsch geschrieben oder                           konnte nicht gefunden werden.
[[Command exited with 1]]
```

I've attached the [log file](https://github.com/watchexec/watchexec/files/11814418/watchexec.2023-06-21T06-50-42Z.log) of that run.

After some digging, I found the [`Command::raw_arg` method](https://doc.rust-lang.org/stable/std/os/windows/process/trait.CommandExt.html#tymethod.raw_arg). The documentation suggests that this a known issue when passing arguments via `cmd.exe /C`. On Windows, [this match arm](https://github.com/watchexec/watchexec/blob/2a3a3dee5f8f0936a5620be9bccccbb4077ebb75/crates/lib/src/command.rs#L101) should probably be handled specially. Unfortunately, `tokio` does not seem to have the `raw_arg` method on its `Command`, so this would probably require a conversion from `std`'s `Command`.

If you like, I can open a PR for this.

**Comment by m-haug** [comment]
I've opened https://github.com/tokio-rs/tokio/issues/5810 to hopefully get `raw_arg` on `tokio`'s `Command`.

**Comment by passcod** [comment]
As a workaround, I think use `--shell none` and handling args manually would work?

**Comment by m-haug** [comment]
In general/when using watchexec as a binary, that would work, I believe. But for the tectonic use case (watchexec), that workaround would require preprocessing the arguments using something like [`shlex`](https://crates.io/crates/shlex), which may be too much effort for a temporary workaround.

**Comment by passcod** [comment]
Yeah, fair enough. If there's a workaround that can be done in the library code until the tokio support lands I'd be happy to merge it.
