### ISSUE TITLE
bosion: `Bosion::long_version()` is missing

### ISSUE THREAD

**Issue by NobodyXu** [watchexec/watchexec#618]
I've only found `Bosion::LONG_VERSION` and `Bosion::long_version_with()` when I used `cargo-expand` to inspect the generated code.

**Comment by NobodyXu** [comment]
`Bosion::LONG_VERSION` is present in `README` but not present in actual generated code.

**Comment by passcod** [comment]
Did you disable the `std` feature?

**Comment by passcod** [comment]
Please check again, `LONG_VERSION` is always written in generated code. `long_version()` is not (was redundant but must have forgotten to update the readme).

**Comment by NobodyXu** [comment]
> Please check again, `LONG_VERSION` is [always written in generated code](https://github.com/watchexec/watchexec/blob/main/crates/bosion/src/lib.rs#L154). 

Yeah `const LONG_VERSION` is indeed present, but `long_version()` is not, though the examples in README uses latter, not former.

> `long_version()` is not (was redundant but must have forgotten to update the readme).

I guess this is a outdated doc issue then.
