### ISSUE TITLE
Panic on inotify limit

### ISSUE THREAD

**Issue by chabapok** [watchexec/watchexec#62]
OS: ubuntu x64 14.04

>$ watchexec -- ls -la
thread 'main' panicked at 'unable to create watcher: Io(Error { repr: Os { code: 28, message: "No space left on device" } })', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted (core dumped)

(There is 89G free on device)

With RUST_BACKTRACE=1 error is same, without backtracing info.

**Comment by mattgreen** [comment]
Try this:

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details

If this fixes it then we should update the error message for this specific case on Linux.

**Comment by chabapok** [comment]
With fs.inotify.max_user_watches=524288 watchexec works ok.

**Comment by usommerl** [comment]
OS: Linux Mint 18.1 x86_64
Same issue. Increasing `max_user_watches` fixes it for me.

**Comment by mattgreen** [comment]
Yeah, some distros set it way too low.

If anyone'd like to make this change I'd be happy to accept it. I would right now but I'm pretty low on free time, as we just had our first kid.
