### ISSUE TITLE
Feature request: Allow to pass changed filenames to commands

### ISSUE THREAD

**Issue by hacker-DOM** [watchexec/watchexec#628]
I propose a new option `--pass-changed-filenames`. This would:

- be by default `{}` but allow to specify an argument
- commands will be str-replaced by the special value with a list of absolute filenames of changed files
- `{}[0]`, `{}[1]`... will be replaced by the first, second files changed
- we could also have a flag `--pass-changed-filenames-format` that could potentially change absolute filenames to relative or other strategies we can think of :-)

What do you guys think?

**Comment by passcod** [comment]
This is specifically out of scope, but you can implement tooling to do it if you wish: https://github.com/watchexec/watchexec/issues/137
