### ISSUE TITLE
Ignore confused by similiarly named paths

### ISSUE THREAD

**Issue by max-sixty** [watchexec/watchexec#633]
- Watchexec's version: ` 1.22.3 (2023-08-03)`
- The OS you're using: MacOS

I have a path with:
```
cat web/book/.gitignore
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: web/book/.gitignore
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ book
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────
```

Because of this, changing a file in `web/book/src` isn't picked up by watchexec. If I change the `.gitignore` entry to `baak`, it is again picked up.

---

For reference, here's the sample command: 

```
RUST_BACKTRACE=1 watchexec -e rs,toml,md,prql -c -r --ignore='target/**' --project-origin=. -vvv --log-file ../watchexec.log -- cargo insta test -p mdbook-prql
```

And the log file is at https://gist.github.com/max-sixty/cd2f75cebbfc7db35418ade9b2f073e8

Thank you

**Comment by passcod** [comment]
Hmm, annoying. I'll put that on the pile but don't have a quick fix nor time at the moment sorry.

**Comment by TheBlek** [comment]
I'm unable to reproduce this issue on watchexec v2.1.2 under Linux (however was able at v1.24). Is this still an issue on MacOS?

**Comment by max-sixty** [comment]
Yes this seems fixed! Closing, thanks
