### ISSUE TITLE
[1.24.1] Command is run multiple times

### ISSUE THREAD

**Issue by tminich** [watchexec/watchexec#726]
After updating to 1.24.0/1.24.1 it seems like the command is run for each event rather than once for each batch. I hadn't used debounce so far, but even that doesn't help (technically in my case makes it even worse, as I'm running a directory sync that now runs several times at once conflicting).

OS: Windows
Command line:
```
watchexec -w "C:\devel\laravel" --project-origin "C:\devel\laravel" --no-default-ignore --no-vcs-ignore --no-project-ignore --no-global-ignore --no-meta -d 2 --ignore-file "C:\devel\exclude.watchexec" <command>
```

**Comment by passcod** [comment]
I'll look into this but as an aside you can replace `--no-default-ignore --no-vcs-ignore --no-project-ignore --no-global-ignore` with `--ignore-nothing`

**Comment by tminich** [comment]
Ah, I missed that, thanks. Trying now with a sane value =)
Nevertheless, no matter what your review yields, might be worth to consider implementing at least two execution modes, one that ensures the command never runs in parallel and one that runs the command for every update.

**Comment by tminich** [comment]
Looks good now. I suspect between versions timings subtly changed and the debounce default was fine before but now caused issues?

**Comment by passcod** [comment]
> one that ensures the command never runs in parallel and one that runs the command for every update.

That should already be the case, unless there's a race condition very early, there's no way for current Watchexec to have two simultaneous runs of a process unless the command is detaching itself.

In fact the current default is for events received during a run to _queue up_ a subsequent run when the current one stops. You may want `--on-busy-update=do-nothing` to ignore changes while the command is currently running.

**Comment by tminich** [comment]
Then indeed something seems to be wrong, the command ran multiple times in parallel. The way you describe the intended default behavior is exactly how I want it to run: if something triggers during a run, finish the run and then run again (once).

**Comment by passcod** [comment]
Well, that's annoying, but at this point I need your command, or something like your command that behaves the same if there's privacy issues here, to replicate this.

**Comment by tminich** [comment]
```
rclone.exe sync -M -v --local-no-preallocate --local-no-sparse --exclude .env --fast-list --exclude-from C:\devel\exclude.rclone C:\devel\laravel \\WSL$\UBUNTU-22.04\home\tminich\devel\laravel
```
I cut the paths down a bit, but that shouldn't matter. Any somewhat sizable repository as a sync source should work.

**Comment by passcod** [comment]
Aight, got a reproduction, I'll get a fix out soon
![image](https://github.com/watchexec/watchexec/assets/155787/b007f6ba-c8b0-44ec-be44-d63c7caff5e2)

**Comment by tminich** [comment]
Thanks, I'll check when I'm back at work early January.
