### ISSUE TITLE
Why cargo-binstall download gnu but not musl version?

### ISSUE THREAD

**Issue by owenstake** [watchexec/watchexec#741]
Execution of the cmd `cargo binstall watchexec-cli` will download the `watchexec-1.24.2-x86_64-unknown-linux-gnu.tar.xz` , but what I want is `watchexec-1.24.2-x86_64-unknown-linux-musl.tar.xz` . How to achieve this ?

**Comment by passcod** [comment]
I see you got your answer in cargo-binstall's issue tracker, please don't double post. Why do you want the musl version if you're running on a gnu system?
