### ISSUE TITLE
Suggestion: Remove README and README.md from project-origin signaling

### ISSUE THREAD

**Issue by alanwsmith** [watchexec/watchexec#744]
**Is your feature request related to a problem? Please describe.**

Yes. I have a directory structure that looks like this:

~/workshop/README.md
~/workshop/project_alfa
~/workshop/project_beta
~/workshop/lots_more_projects

I could never get watchexec to work properly in my project directories. After digging into the logs and source code I found that "README" and "README.md" are used to identify the project origin. So, when I'd run watchexec in ~/workshop/project_alfa it would find the README.md and use ~/workshop as the project-origin instead.

I've got a ton of projects in my workshop so the net effect is that watchexec would take so long to start I though it was bugged and killed it. 

Once I figured out what was going on and removed the ~/workshop/README.md file everything worked great. 

I use README.md files all over the place and would love it if I could use it in my ~/workshop directory without that setting the watchexec to use it as the project-origin. 

**Describe the solution you'd like**

The solution I'd like to see is to remove README and README.md as signals for the project-origin.

**Describe alternatives you've considered**

A possible alternative would be to set up a config to determine which files are used to define a project-origin. (I don't think that currently exists)

**Additional context**

N/A

**Comment by passcod** [comment]
Done and will be out in 1.25.0 soon
