### ISSUE TITLE
Panic with permission denied

### ISSUE THREAD

**Issue by vorner** [watchexec/watchexec#75]
Hello

I learned to rely on this wonderful tool for a day to day development. However, I seem to have hit an annoying bug.

Whenever there's a file or directory watchexec doesn't have rights to open, it crashes with a panic:

```
mkdir x
cd x
touch a
sudo mkdir b
sudo mod 0500 b
watchexec 'echo yes'
```

```
thread 'main' panicked at 'unable to create watcher: Io(Error { repr: Os { code: 13, message: "Permission denied" } })', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0:     0x5610746cda63 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1e86e3497d1acae9
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5610746cbc91 - std::panicking::default_hook::{{closure}}::h779316f5456da2f6
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   2:     0x5610746cb4e3 - std::panicking::rust_panic_with_hook::h70730c24f61a71c3
                               at /checkout/src/libstd/panicking.rs:397
                               at /checkout/src/libstd/panicking.rs:577
   3:     0x5610746cafc0 - std::panicking::begin_panic::he24287dee3b14edc
                               at /checkout/src/libstd/panicking.rs:538
   4:     0x5610746caf59 - std::panicking::begin_panic_fmt::h43bf7625e09c9b1b
                               at /checkout/src/libstd/panicking.rs:522
   5:     0x5610746dd85a - core::panicking::panic_fmt::ha1102276931c190d
                               at /checkout/src/libstd/panicking.rs:498
   6:     0x5610745a1752 - core::result::unwrap_failed::h3aa5a78e82f8950f
   7:     0x5610746f8751 - watchexec::run::run::hf5b50be1065edbbf
   8:     0x5610745b4ae6 - watchexec::main::h378cdc176b0c5c77
   9:     0x5610745b4fa9 - main
  10:     0x7fe10f35f010 - __libc_start_main
  11:     0x56107459c739 - _start
  12:                0x0 - <unknown>
```

I believe this is wrong on several levels:

* I'd have expected to at least get an error message stating *which* file it doesn't have permission to read (it actually happened in real usage to me and it took some time finding the file). I haven't checked against master, this might be already fixed in #74.
* I think this is one of the kinds of errors that should allow the tool to continue (eg. if you don't see into the directory, don't watch changes in there, but watch other directories around), possibly with a warning. This situation makes it harder to run the tool in a project which needs to do tests with root privileges.
* It also happens if I explicitly ask to ignore the directory, eg `watchexec -i b 'echo yes'` also crashes.

**Comment by mattgreen** [comment]
Thanks for the excellent bug report. I will look into this and see what I can do.

What I'm not sure about is whether the file system watcher will handle this gracefully. Need to experiment and see.

**Comment by passcod** [comment]
This has been fixed. I'm not sure when, but it's fixed.
