### ISSUE TITLE
.gitignore files in subdirectories are not taken into account when watching a parent directory with the `..` notation

### ISSUE THREAD

**Issue by thomasetter** [watchexec/watchexec#759]
Tried this with `1.25.0` on an Arch container, but it may also affect older versions.

Created a repro example at [thomasetter/watchexec-parent-ignore-fail](https://github.com/thomasetter/watchexec-parent-ignore-fail/tree/main) with instructions to run there.

```
tree  -a -I .git watchexec-parent-ignore-fail/
watchexec-parent-ignore-fail/
├── .gitignore
├── README.md
├── parent-watching-out
├── self-watching-out
└── subdir0
    ├── .gitignore                   # Ignores ignored-from-child-gitignore
    └── ignored-from-child-gitignore # Inconsistently ignored
```

When watching for changes to `-w .` in `watchexec-parent-ignore-fail/`, everything behaves as expected.

However, when watching for changes to `-w ..` in `watchexec-parent-ignore-fail/subdir0`, changes to `watchexec-parent-ignore-fail/subdir0/ignored-from-child-gitignore` are not ignored and trigger reruns.

Specifying an absolute path for `-w` works, but is cumbersome.

Some projects have tests in subdirectories which depend on parent directories, and being able to watch on parent directories without resorting to absolute paths would be convenient.

Working: [self-watching-out.log](https://github.com/watchexec/watchexec/files/13814705/self-watching-out.log)
Broken: [parent-watching-out.log](https://github.com/watchexec/watchexec/files/13814707/parent-watching-out.log)

**Comment by passcod** [comment]
Hmm. Can you try with 1.24.2, to see if it's a regression given 1.25 did touch this area?

**Comment by thomasetter** [comment]
I tried with `1.24.2` and it worked correctly, so this seems to be a regression in `1.25.0`

**Comment by passcod** [comment]
gah, sorry about that! i'll look into it tomorrow
