### ISSUE TITLE
rpm package file conflict

### ISSUE THREAD

**Issue by vrischmann** [watchexec/watchexec#766]
**What used to happen**

I could install the watchexec-cli rpm package alongside the fish package on fedora. 

**What happens now**

Since [fish 3.7.0](https://github.com/fish-shell/fish-shell/pull/10027/files) there's a conflict between the fish package on Fedora (which shipped recently) and watchexec-cli package: both want to create the `/usr/share/fish/completions/watchexec.fish` file:

```
$ sudo dnf install ./watchexec-1.25.1-x86_64-unknown-linux-gnu.rpm 
...
Running transaction test
Error: Transaction test error:
  file /usr/share/fish/completions/watchexec.fish from install of watchexec-cli-0:1.25.1-1.x86_64 conflicts with file from package fish-3.7.0-1.fc39.x86_64
```

It's not _really_ a bug with watchexec but I thought I'd still open this issue to let you know.

**Comment by passcod** [comment]
Oh, it's for... all distros, too. That will affect everyone once they ship the new fish. Alright, well, I think I need to remove the fish completion from the rpm and deb.

**Comment by passcod** [comment]
Ah, looking at the arch packaging https://archlinux.org/packages/extra/x86_64/watchexec/ there's a folder for vendor-provided completion, I'll use that in the deb/rpm packages to avoid the conflict instead!
