### ISSUE TITLE
some REPLs don't work

### ISSUE THREAD

**Issue by nburns** [watchexec/watchexec#768]
It looks like some recent changes have caused some REPLs to break that were working before. `python` for example does not work anymore, although it used to, possibly before changes related to this: https://github.com/watchexec/watchexec/issues/655

```
> ~/Downloads/watchexec-1.25.1-aarch64-apple-darwin/watchexec -- python
[Running: python]
```
Note the lack of output from 1.25

```
> ~/Downloads/watchexec-1.23.0-aarch64-apple-darwin/watchexec -- python
Python 3.12.1 (main, Jan 16 2024, 23:58:41) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
note that the repl is able to output and we can interact with it

- Watchexec's version: 1.25.1
- The OS you're using: Sonoma 14.1.1 (23B81)
- A log with `-vvv --log-file` [1.23.log](https://github.com/watchexec/watchexec/files/13969537/1.23.log)
[1.25.log](https://github.com/watchexec/watchexec/files/13969538/1.25.log)
- A sample command that you've run that has the issue: `watchexec -- python`

**Comment by nburns** [comment]
also, just wanted to say thanks for building watchexec I use it a lot and really appreciate it

**Comment by passcod** [comment]
Does `--no-process-group` help?

**Comment by nburns** [comment]
yes it does, thanks!

**Comment by passcod** [comment]
FTR this is the same as #743, you can find a longer explanation there.
