### ISSUE TITLE
system wide / global `.ignore` file

### ISSUE THREAD

**Issue by colemickens** [watchexec/watchexec#778]
**Is your feature request related to a problem? Please describe.**

I use `watchman` to provide `fsmonitor` for git. I also use `jj` which uses `.jj`.

**Describe the solution you'd like**
I'd like to put ignores for each of their files into a global ignore.

**Describe alternatives you've considered**
Putting an `.ignore` in all of my teams projects, even though none of them use these other tools.

Different approach: `--ignore-from-file` that will read a `.ignore` by path.

**Additional context**

I'm hoping maybe either approach is easier or more straightforward than dealing with gitignore. If so, it might be something I can contribute.

Thanks!

**Comment by colemickens** [comment]
Oh, I don't know if watchexec already uses XDG, but hopefully this would look in XDG_CONFIG_HOME, etc, as appropriate.

**Comment by passcod** [comment]
See the help page for `--no-global-ignore`:

> the first found of `$XDG_CONFIG_HOME/watchexec/ignore`, `%APPDATA%/watchexec/ignore`, `%USERPROFILE%/.watchexec/ignore`, `$HOME/.watchexec/ignore`.
