### ISSUE TITLE
Duplicate Events for file change

### ISSUE THREAD

**Issue by jkavalec** [watchexec/watchexec#791]
Hi, I have some issues with watchexec duplicating events for changed files.
- I change test file and get correctly generated event regarding its change
- If I change anther file within few seconds, there will be change with both files in the change list
- If change ocurs after few more seconds instead, I get change for only one file as expected

I wonder whether this has to do anything with how watching for multiple files changed at the same is implemented, then again I would expect that if file is in one changeset it should not appear again

Command: watchexec -e ts test-command
Watchexec 1.25.0
MacOs Ventura 13.5

**Comment by passcod** [comment]
MacOS's FSEvents (the OS API watchexec uses) is weird™ and does this. It's not a Watchexec issue.
