### ISSUE TITLE
$WATCHEXEC_CREATED_PATH

### ISSUE THREAD

**Issue by Gianlucas94** [watchexec/watchexec#793]
Hello,
The variable $WATCHEXEC_CREATED_PATH don't seems to be filled when I create new folders in the watched folder.

**- Watchexec's version:** 1.25.1
**- The OS you're using:** Windows 11
- [watchexec.2024-02-29T06-37-44Z.log](https://github.com/watchexec/watchexec/files/14443870/watchexec.2024-02-29T06-37-44Z.log)
- **A sample command that you've run that has the issue:**
`watchexec --watch C:\test --print-events -r --shell=pwsh -- 'Write-Host "=========
=`n`$env:WATCHEXEC_CREATED_PATH           => $env:WATCHEXEC_CREATED_PATH`n`$env:WATCHEXEC_REMOVED_PATH           => $env:WATCHEXEC_REMOVED_PATH`n`$env:WATCHEXEC_RENAMED_PATH           => $env:WATCHEXEC_RENAMED_PATH`n`$env:WATCHEXEC_WRITTEN_PATH           => $env:WATCHEXEC_WRITTEN_PATH`n`$env:WATCHEXEC_META_CHANGED_PATH      => $env:WATCHEXEC_META_CHANGED_PATH`n`$env:WATCHEXEC_OTHERWISE_CHANGED_PATH => $env:WATCHEXEC_OTHERWISE_CHANGED_PATH"`n=========='`

Thank you

**Comment by passcod** [comment]
The variable is inserted, but to an empty string:

```
{"timestamp":"2024-02-29T06:37:51.947766Z","level":"DEBUG","fields":{"message":"inserting environment variable","k":"\"WATCHEXEC_COMMON_PATH\"","v":"\"C:\\\\test\\\\Nova pasta (2)\""},"target":"watchexec_cli::config"}
{"timestamp":"2024-02-29T06:37:51.947777Z","level":"DEBUG","fields":{"message":"inserting environment variable","k":"\"WATCHEXEC_CREATED_PATH\"","v":"\"\""},"target":"watchexec_cli::config"}
```

You're meant to prepend `WATCHEXEC_COMMON_PATH` to obtain the full paths. Prefer to use the `stdio` or `file` modes of `--emit-events-to` instead of these environment variables.
