### ISSUE TITLE
$WATCHEXEC_UPDATED_PATH not working?

### ISSUE THREAD

**Issue by mike-hearn** [watchexec/watchexec#81]
Hi Matt & co - first off, I love watchexec and use it every day.

Now, it's very possible (likely) I'm missing something extremely simple, but I cannot figure out how to get `$WATCHEXEC_UPDATED_PATH` to display the changed file.

I made a Docker container ([Dockerfile here](https://gist.githubusercontent.com/mike-hearn/ebc6cbd69d848075ca708112af550087/raw/0457e166a0f563f352fec8d0c5d593d4ccada23f/Dockerfile)) to verify/reproduce exactly what I'm doing.

Run this command:

```
docker run --rm --name watchexec-container mikehearn/watchexec-example
```

This will start a container running watchexec on all files in the `/test` dir (inside the container). The command is `watchexec -- 'echo changed $WATCHEXEC_UPDATED_PATH'`.

In a separate shell, run a command via `docker exec` inside the container to update a watched file:

```
docker exec watchexec-container touch /test/example.txt
```

Since the command being run is `'echo changed $WATCHEXEC_UPDATED_PATH'`, what I would *expect* it to print out is `changed /test/example.txt`. What does get printed out is:

```
changed
```

Here's an [exciting GIF](https://i.imgur.com/pb1ejiZ.gif) where I do exactly these steps, and you can see it's not spitting out the file name. Is there something specific I have to do to get it to print the name?

![watchexec issue reproduction gif](https://i.imgur.com/pb1ejiZ.gif)

**Comment by mike-hearn** [comment]
Looks like it was removed in https://github.com/mattgreen/watchexec/commit/8bd9bb3 and the docs weren't updated.

**Comment by raxod502** [comment]
This issue can be closed now, I guess.

**Comment by passcod** [comment]
Ah, thank you.
