### ISSUE TITLE
Ability to configure the location of temporary files

### ISSUE THREAD

**Issue by ForestEckhardt** [watchexec/watchexec#814]
## Problem Description

I am trying to run watchexec in an environment where the user does not have write permissions to `/tmp`. This is a problem because when watchexec tries to start it creates a new `RotatingTempFile` by default and cause the process to crash with the following error.
```
Error:   x Permission denied (os error 13) at path "/tmp/.tmpa7Y2Qr"
```

## Solution

Having a way to either disable the need for that file to be created or allow for the file to be created in a directory that I can configure (either through a flag or an environment). I have no strong preference on the name.

## Alternatives

There is a less than ideal workaround which is by setting `TMPDIR` to a directory that can be written to, however setting this environment variable feels a bit overreaching and I would prefer to  be able to specify for just watchexec.

---
Watchexec version: v1.25.1

**Comment by passcod** [comment]
Will be fixed in 2.0.0
