### ISSUE TITLE
docs: the v2.0.0 help text lists wrong default for `--on-busy-update` 

### ISSUE THREAD

**Issue by nestor-custodio** [watchexec/watchexec#824]
Help text (`watchexec --help`) under v2.0.0 still states the default value for `--on-busy-update` is `'queue'`, and that *a future release* will be changing this to `'do-nothing'`.

---

- OS: Ubuntu 23.10
- `watchexec --version`:
  ```
  watchexec 2.0.0 (0ef8782 2024-04-20) +pid1
  commit-hash: 0ef87821f240bb9d4434367e7dcc17e89e6d1bed
  commit-date: 2024-04-20
  build-date: 2024-04-20
  release: 2.0.0
  features: default,pid1
  ```

**Comment by passcod** [comment]
Oh, good catch
