### ISSUE TITLE
Possible missed "tracing::info"

### ISSUE THREAD

**Issue by gc-victor** [watchexec/watchexec#829]
Is it intentional?

https://github.com/watchexec/watchexec/blob/72f069a8477c679e45f845219276b0bfe22fed79/crates/lib/src/sources/fs.rs#L159

**Comment by passcod** [comment]
Yes: https://github.com/watchexec/watchexec/blob/main/crates/lib/src/lib.rs#L48-L51

> Note that the library generates a _lot_ of debug messaging with [tracing]. **You should not
> enable printing even `error`-level log messages for this crate unless it's for debugging.**
> Instead, make use of the [`Config::on_error()`] method to define a handler for errors
> occurring at runtime that are _meant_ for you to handle (by printing out or otherwise).
