### ISSUE TITLE
Pass changed file name to the command

### ISSUE THREAD

**Issue by curioustolearn** [watchexec/watchexec#834]
- Watchexec's version
```
watchexec 1.25.1 (d3949cc 2024-01-05) +pid1
commit-hash: d3949cc6e9879225ab8191ad558691da97d28a23
commit-date: 2024-01-05
build-date: 2024-01-05
release: 1.25.1
features: default,pid1
```

- The OS you're using
 macOS Monterey

I want to pass the name of the changed file to a command. In my case, I am running the `pdflatex` command and want to pass the changed `tex` file to this command. I searched the issues here that were asking similar question. However, it is not clear how to do this and would appreciate a simple example. Based on what I read in a couple of issues, I tried the following. However, as you can see below, the name of the changed file is not echoed. Is this a bug, or am I doing something wrong? 

```
watchexec "echo $WATCHEXEC_WRITTEN_PATH modified"
[Running: echo  modified]
modified
[Command was successful]
[Running: echo  modified]
modified
[Command was successful]
```

Thank you very much.

**Comment by passcod** [comment]
This is described in the help page, at [`--emit-events-to`](https://github.com/watchexec/watchexec/blob/main/doc/watchexec.1#L258-L359)

You need to set an event emission mode with `--emit-events-to=MODE`. The legacy `environment` mode requires using something like `$WATCHEXEC_COMMON_PATH/$WATCHEXEC_MODIFIED_PATH` and also handling multiple paths. The `file` and `json` modes give you less clunky access and are recommended.

You're also using Watchexec 1.x; note that 2.x is out.
