### ISSUE TITLE
Release x86_64 DEB installs manpage to incorrect path

### ISSUE THREAD

**Issue by sagi-glacia** [watchexec/watchexec#847]
When installing from `watchexec-2.1.1-x86_64-unknown-linux-gnu.deb`, the manpage is installed to `/usr/share/man/man1/watchexec.1.html.gz`, instead of `/usr/share/man/man1/watchexec.1.gz`.  This causes man (at least on Ubuntu 22.04) to ignore it when you run `man watchexec`.

```text
$ man watchexec
man: warning: /usr/share/man/man1/watchexec.1.html.gz: ignoring bogus filename
No manual entry for watchexec
```

The file is formatted correctly, and man can read it if given the full path, however since it is installed with an incorrect `.html` component to its filename, it cannot be used normally.

**Comment by passcod** [comment]
Fixed in 2.1.2
