### ISSUE TITLE
Investigate the possibility of tracing which files the child process touches (in the optics of ignoring those changes to avoid infinite restart loops)

### ISSUE THREAD

**Issue by michalrus** [watchexec/watchexec#85]
## Problem

Let’s say I would want to run `hindent` or `scalafmt` or `gofmt` or anything like that, after a successful test run triggered by `watchexec`.

But this formatting will retrigger `watchexec`.

At the same time it would be wonderful to be able to SIGKILL the autoformatter and restart everything after hitting Save in my editor.

## Potential solution?…

So maybe `watchexec` could know to not retrigger for changes done by a certain process name.

Perhaps we could have an option to run:

```
$ watchexec -rs SIGKILL --ignore-changes-by-procname=gofmt 'exec make -j1 test autoformat'
````

**Comment by passcod** [comment]
There is no information available about what process made a change to a file. It is possible in some cases to tell what files a process has open, but that doesn't really help.

**Comment by michalrus** [comment]
I was afraid of that… Updated the description accordingly.

Maybe there’ll be some other better ideas, but I frankly have none.

**Comment by passcod** [comment]
What could be done, but I'm not sure would be reliable and/or in scope for this tool, would be the inverse. Accepting a performance penalty, one could trace or watch the _child_ for any file handle opened or written to. Then those would be ignored until the child is done.

It's not quite the same behaviour, and would be a large project, especially to make it work across platforms. But that would be one avenue.

**Comment by michalrus** [comment]
Oh! Ignoring all writes done by all child processes (and grand-child, i.e. all descendant processes) of `watchexec` itself — that would be amazing. ♥

**Comment by passcod** [comment]
Duplicate of #40
