### ISSUE TITLE
Release patch version with `gix` CVE fixes

### ISSUE THREAD

**Issue by DaniPopes** [watchexec/watchexec#852]
`watchexec` as a library has a transitive dependency on `gix` through `ignore-files`. Currently used versions of the `gix` crates in this repository are marked vulnerable to:
- https://github.com/Byron/gitoxide/security/advisories/GHSA-49jc-r788-3fc9
- https://github.com/Byron/gitoxide/security/advisories/GHSA-7w47-3wg8-547c

However I don't think this affects `watchexec` directly.

Would it be possible to make a patch release that includes updating `gix`? Thanks!

**Comment by passcod** [comment]
Thanks for letting me know. `ignore-files` neither fetches nor checks out repos, so is not affected. The next routine patch will pull in updates, but I'm not going to go out of my way to "fix" a vulnerability that doesn't exist.
