### ISSUE TITLE
Environment variable documentation badly out of date

### ISSUE THREAD

**Issue by raxod502** [watchexec/watchexec#86]
I see in the documentation:

> * Sets the following environment variables in the child process:
>     * `$WATCHEXEC_UPDATED_PATH` the path of the first file that triggered a change
>     * `$WATCHEXEC_COMMON_PATH` the longest common path of all of the files that triggered a change

I'm trying:

    $ watchexec 'echo "Got $WATCHEXEC_UPDATED_PATH modified"'
    $ watchexec 'echo "Got $WATCHEXEC_COMMON_PATH modified"'
    
But when I modify a file, it just prints:

    Got  modified
    
What am I doing wrong here?

**Comment by raxod502** [comment]
After further testing (and reading the source code), I found that the actual behavior is:

* If only one file changed, set one of `$WATCHEXEC_CREATED_PATH`, `$WATCHEXEC_REMOVED_PATH`, `$WATCHEXEC_RENAMED_PATH`, `$WATCHEXEC_WRITTEN_PATH`, `$WATCHEXEC_META_CHANGED_PATH`.
* If multiple files changed, set only `$WATCHEXEC_COMMON_PATH`.

The documentation flatly contradicts this, so it should probably be updated.

**Comment by mattgreen** [comment]
PRs gladly accepted :)
