### ISSUE TITLE
-n flag does not work as expected

### ISSUE THREAD

**Issue by raxod502** [watchexec/watchexec#87]
As expected:

```
$ /bin/echo "foo  bar"
foo  bar
```

Not as expected:

```
$ watchexec -n /bin/echo "foo  bar"
foo bar
```

I would assume the two to be equivalent since `-n` is passed. Why is this different from just running the command?

It seems as if something is going wrong with the quoting and the `foo  bar` argument is being passed as two arguments instead of one.

**Comment by passcod** [comment]
Might be related to #82

**Comment by raxod502** [comment]
Looks like the same issue to me, yes.
