### ISSUE TITLE
--project-origin . is not equivalent to --project-origin `pwd`

### ISSUE THREAD

**Issue by jackc** [watchexec/watchexec#886]
Over a year ago I added `--project-origin .` to resolve slowness due to project origin not being properly detected.

I'm using a command like this:

    watchexec --project-origin . -f "postgresql/code/**" -- mycmd

It used to trigger whenever I changed a file inside `postgresql/code/`. It no longer does.

However, it does work if instead I use the absolute path for project origin.

    watchexec --project-origin `pwd` -f "postgresql/code/**" -- mycmd

I would expect these to be equivalent.

---

watchexec version:
```
$ watchexec --version
watchexec 2.2.0 (2024-10-14) +pid1
build-date: 2024-10-14
release: 2.2.0
features: default,pid1
```

OS version:
```
$ sw_vers
ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91
```
[watchexec.2024-12-13T19-19-52Z.log](https://github.com/user-attachments/files/18131009/watchexec.2024-12-13T19-19-52Z.log)
[watchexec.2024-12-13T19-20-19Z.log](https://github.com/user-attachments/files/18131010/watchexec.2024-12-13T19-20-19Z.log)

**Comment by passcod** [comment]
I would too and will look into that, but... no longer since when? There hasn't been a release since October, and there's also been 12 releases since a year ago, including a major. It would help if the behaviour change is mapped to a particular version change.

**Comment by jackc** [comment]
I did a bit of manual bisecting and it appears the problem was introduced in v2.1.0. It works in v2.0.0, but not in v2.1.0.

**Comment by passcod** [comment]
Thanks

**Comment by passcod** [comment]
Can you check whether 2.2.1 fixes your usecase?

**Comment by jackc** [comment]
Yes, it works. Thanks!
