### ISSUE TITLE
watchexec no longer supports interactive programs (REPL etc)

### ISSUE THREAD

**Issue by lddllddl** [watchexec/watchexec#888]
**What used to happen**

Previously in 1.22.2, 
`watchexec -r ...... -- ipython -i abc.py` would work just fine, which drops into ipython REPL as what would expected when running
`ipython -i abc.py` alone

**What happens now**

Now I am at 2.2.0 due to whole system upgrade.

The above won't lead to an REPL anymore, as with
`watchexec -r .... -- ipython` or
`watchexec -r .... -- python` or
`watchexec -r .... -- ipython -i` or
`watchexec -r .... -- python -i` or
`watchexec -r .... -- bash`

My guess is that the changed happened when bumping the version from 1.* to 2.* .

By the way the default 10s wait to shutdown the command in this case is also extremely annoying - personal opinion.

**Details**
- Latest version that worked: 1.22.2
- Earliest version that doesn't: 2.2.0
- OS:
- NixOS 24.11

**Comment by lddllddl** [comment]
By the way when 
`watchexec -r -- python`
the Python interpreter actually recognizes that it is supposed to be an interactive session and prints the welcome message (which would not be printed with say `echo | python`), but I don't get the `>>>`.

**Comment by lddllddl** [comment]
Actually I just found out that
`watchexec --wrap-process=session -- python` 
Not sure if this still counts as a regression in this case

**Comment by passcod** [comment]
This has been called out in the release notes.
