### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by sanga** [watchexec/watchexec#94]
Activity on watchexec seems to have basically stopped (is that fair comment @mattgreen?). Which seems a bit tragic to me, as of all the "watcher" type programs I've used, watchexec is my favourite and would like it to keep moving forward. Would it be possible to perhaps give a couple more people that admin bit?

**Comment by sanga** [comment]
To be clear: I'm not proposing myself as an admin. I'm far from being a rust coder. Just that we'd have some more people involved to get PRs merged etc.

**Comment by mattgreen** [comment]
Hi, thanks for poking me. I'm glad you like watchexec and would like it to continue. 

I'd like to pass maintainer status on to someone else. Right now I'm working as a full-time dev and part-time PM while also being a dad, so open source is a bit hard to slot time for. I'm sorry for the languishing PRs and such.

If anyone would like to take it over, please let me know. If you'd like a little bit of guidance I can provide that, I just can't help out with code at the moment.

**Comment by passcod** [comment]
Completely understand and wish you good continuation with your other activities!

I'd be happy to take it over, especially as part of the notify and cargo-watch ecosystem (while of course letting watchexec remain agnostic as per its purpose), though I'll work with the community to get more people involved if possible so there's a more healthy balance and future, given my own state of occupation.

How should we do this? The least work for you would be to add me as a collaborator and give me publish rights on crates.io, but perhaps a more robust thing would be to move watchexec into its own Github organisation. Up to you.

**Comment by sanga** [comment]
No need to apologise at @mattgreen. Thank you sincerely for this project and the hours of your free time that you have given over it's lifetime. All the best.

**Comment by mattgreen** [comment]
Current status on this:

- Created an organization for watchexec
- Moved the repository over
- Added passcod to org
- Added passcod as owner on crates.io 
- Changed org permissions to default to admin

Everything look OK?

**Comment by passcod** [comment]
It does! Thank you Matt. I'll get on PRs asap / this weekend :)
