### ISSUE TITLE
Issues with `--ignore` option

### ISSUE THREAD

**Issue by behnam** [watchexec/watchexec#97]
I'm testing the command with --ignore on a directory and seems to be not working at all.

The system is: `Linux * Ubuntu SMP Fri Jul 13 07:23:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Besides passing the directory name (from the current directory), I have also tried glob patterns for the specific files. No luck.

Also, doing so, realized that the documentation (https://github.com/watchexec/watchexec) is not clear at all about what kind of "pattern" it's supporting. Would be great to improve that to be clear if it's glob, regex, or something else.

**Comment by passcod** [comment]
We use globset: https://docs.rs/globset/0.4.2/globset/#syntax

**Comment by passcod** [comment]
Also would be very useful to have:
- the layout of the directories you're trying this on
- what ignore string you're using
- a verbose log, using `--verbose`

**Comment by behnam** [comment]
Thanks, @passcod! Knowing that it's a glob pattern, and checking with `--verbose`, looksl ike I got it working and there are no issues with matching.

So, maybe you just want to update the docs to mention the patterns are standard globs?

**Comment by passcod** [comment]
Sure, I'll do that.

**Comment by sergeevabc** [comment]
Aggrrhh, it took me a hour already, but still no luck with ignoring all subfolders of the chosen folder. How??

**Comment by passcod** [comment]
What are you trying?

**Comment by sergeevabc** [comment]
I have a folder ```C:\Downloads``` to be watched for new files. Once a new file is spotted, a sorting routing is invoked (e.g. ```C:\Tools\sortfiles.cmd```), which moves ```*.jpg``` into ```C:\Downloads\Pictures```, ```*.mp4``` into ```C:\Downloads\Videos```, etc. I don’t like the idea of listing all subfolders as some kind of ignoring regex ```(Pictures|Videos|etc)```, there must be an easier way to ignore **all** subfolders.

I tried ```-i Downloads\**\```, ```-i Downloads\**\*``` and ```-i Downloads\**\*.*``` with no luck.

**Comment by passcod** [comment]
What does the debug log look like for those?

Also I'm thinking that the issue is less your ending and more your
beginning (e.g. "**\Documents\**" may work).

**Comment by passcod** [comment]
Sorry, "**\Downloads\**"

**Comment by sergeevabc** [comment]
Nope, it does not work either. Obvious task to exclude subfolders turns out to be a nightmare, alas.

```
$ watchexec.exe --verbose --postpone -n -w C:\Downloads -i **\Downloads\** C:\Tools\sortfiles.cmd

*** Adding ignore: "**\.DS_Store"
*** Adding ignore: "*.py[co]"
*** Adding ignore: "**\#*#"
*** Adding ignore: "**\.#*"
*** Adding ignore: "**\.*.sw?"
*** Adding ignore: "**\.*.sw?x"
*** Adding ignore: "**\.git\**"
*** Adding ignore: "**\.hg\**"
*** Adding ignore: "**\.svn\**"
*** Adding ignore: "**\Downloads\**"
*** glob converted to regex: Glob { glob: "*.py[co]", re: "(?-u)^.*\\.py[co]$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([ZeroOrMore, Literal('.'), Literal('p'), Literal('y'), Class{ negated: false, ranges: [('c', 'c'), ('o', 'o')] }]) }
*** glob converted to regex: Glob { glob: "**\\#*#", re: "(?-u)^(?:/?|.*/)\\#.*\\#$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('#'), ZeroOrMore, Literal('#')]) }
*** glob converted to regex: Glob { glob: "**\\.#*", re: "(?-u)^(?:/?|.*/)\\.\\#.*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('#'), ZeroOrMore]) }
*** glob converted to regex: Glob { glob: "**\\.*.sw?", re: "(?-u)^(?:/?|.*/)\\..*\\.sw.$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('.'), ZeroOrMore, Literal('.'), Literal('s'), Literal('w'), Any]) }
*** glob converted to regex: Glob { glob: "**\\.*.sw?x", re: "(?-u)^(?:/?|.*/)\\..*\\.sw.x$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('.'), ZeroOrMore, Literal('.'), Literal('s'), Literal('w'), Any, Literal('x')]) }
*** glob converted to regex: Glob { glob: "**\\.git\\**", re: "(?-u)^(?:/?|.*/)\\.git(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('g'), Literal('i'), Literal('t'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**\\.hg\\**", re: "(?-u)^(?:/?|.*/)\\.hg(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('h'), Literal('g'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**\\.svn\\**", re: "(?-u)^(?:/?|.*/)\\.svn(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('s'), Literal('v'), Literal('n'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**\\Downloads\\**", re: "(?-u)^(?:/?|.*/)Downloads(?:/?|/.*)$", opts: GlobOptions {case_insensitive: false, literal_separator: false, backslash_escape: false }, tokens: Tokens([RecursivePrefix, Literal('D'), Literal('o'), Literal('w'), Literal('n'), Literal('l'), Literal('o'), Literal('a'), Literal('d'), Literal('s'), RecursiveSuffix]) }
*** built glob set; 0 literals, 1 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 9 regexes
*** Watching "\\\\?\\C:\\Downloads"
*** Waiting for filesystem activity
```

Check involves copying some files into ```C:\Downloads\``` and into ```C:\Downloads\Pictures\```.

```
*** Ignoring "\\\\?\\C:\\Downloads\\Readme.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Readme.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Readme.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures\\License.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures\\License.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures\\License.txt": matched ignore filter
```

Obviously, the check is not passed.

**Comment by passcod** [comment]
Alright, so I'm just going to assume here that what we're seeing is that
the first three are false positives, and the last four are correct. Is that
right?

That is, **\Downloads\** is matching everything in Downloads, not just
everything in subfolders of Download. That is consistent with the syntax
[1] {which is linked from the readme}. We're hitting the second variant of
the ** rule:

"if the glob ends with /**, then it matches all sub-entries. For example,
foo/** matches foo/a and foo/a/b, but not foo."

What I think we want is the third variant:

"if the glob contains /**/ anywhere within the pattern, then it matches
zero or more directories."

Therefore please try using ***\Downloads\**\*

[1]: https://docs.rs/globset/*/globset/#syntax

**Comment by sergeevabc** [comment]
```***\Downloads\**\*``` (with three asterisks in the beginning) crushes the app.

```
*** Adding ignore: "**\.DS_Store"
*** Adding ignore: "*.py[co]"
*** Adding ignore: "**\#*#"
*** Adding ignore: "**\.#*"
*** Adding ignore: "**\.*.sw?"
*** Adding ignore: "**\.*.sw?x"
*** Adding ignore: "**\.git\**"
*** Adding ignore: "**\.hg\**"
*** Adding ignore: "**\.svn\**"
Error:
thread 'main' has overflowed its stack
```

As for ```**\Downloads\**\*```, it does not work as expected either, still ignoring everything.

```
*** Waiting for filesystem activity
*** Ignoring "\\\\?\\C:\\Downloads\\Readme.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Readme.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Readme.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures\\History.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures\\History.txt": matched ignore filter
*** Ignoring "\\\\?\\C:\\Downloads\\Pictures\\History.txt": matched ignore filter
```

**Comment by passcod** [comment]
My apologies, that's formatting not coming through. This should be `**\Downloads\**\`

**Comment by passcod** [comment]
Oops, I meant `**\Downloads\*\**\*`

**Comment by passcod** [comment]
Reading as "any folder", "zero or more folders from that", "zero or more files or folders from that"

**Comment by passcod** [comment]
I can certainly agree that the current glob and ignore behaviour can be
improved. This is I think the number one issue that people hit when using
watchexec or derivatives.

However, I'm less convinced about adding a switch for this particular
usecase. If the option can be made a bit more generic, perhaps...

**Comment by sergeevabc** [comment]
@passcod, so we’ve found a way to ignore files within subfolders, but not subfolders per se. What now?

**Comment by passcod** [comment]
So, I had to sleep in the meantime, which helped lots.

The fundamental thing here, and this is something that the docs and help page should explain more (or at all) clearly, is that ignores and filters operate on paths. That's why they can't tell between folders and files.

Now, having a general switch to ignore folders in the event stream (or, more generically, a switch that filters on file types rather than just one thing, because I can see this spiraling) would mean one file access per event, which has implications. Performance and otherwise. There are other various and diverse considerations for inclusion directly into watchexec (which would take longer to sort through).

~~But the good news here, is that this is something you can do right now without modifying the tool! It might feel a bit unwieldy, but you get all the flexibility you want.

See, we give you, through environment variables, the paths that triggered this change. See the docs for what they're named and what they do. You can do your own postfiltering using those, for example ignoring all paths that resolve to folders.~~ 

Or rather, you _could_ do that in an ideal world, but I've just read the docs again and we don't give you all the paths that changed in the case of multiple events being bunched up, which will likely be your case.

I think you could try this approach anyway, see if it works for you. If it doesn't, I could see about adding an environment variable for "all paths changed" (which would be truncated for when lots of changes occur, due to limits on env vars... about 2000 characters).

**Comment by sergeevabc** [comment]
@passcod, until now I used Wildcards (*.*), RegEx (e.g. [Ripgrep][2] to intelligently grep, Userstyles+Userscripts to modify chosen webpages, etc), also [Keypirinha][1] (Windows launcher) uses glob-like syntax to include ```C:\Tools\**``` but exclude ``` *\App\*``` and ```*\uninst*.*```. So I see there are ways to solve this. Even tried another watcher [Modd][3] and it works out of the box with ```C:\Downloads\*.*``` (however consumes RAM 75 Mb vs Wachexec 3 Mb)

[1]: http://keypirinha.com/
[2]: https://github.com/BurntSushi/ripgrep
[3]: https://github.com/cortesi/modd#quick-start

**Comment by passcod** [comment]
I suspect but did not check that the difference is that Modd reports only files while watchexec also reports folders.
